{
  "hash": "5ff68c3b8ccb0bfdd090492768732fb4",
  "result": {
    "engine": "knitr",
    "markdown": "# Test di ipotesi e valore-*p* {#sec-freq-hypothesis-testing}\n\n::: {.callout-note title=\"In sintesi\"}\n**Da sapere**  Un test frequentista confronta una statistica osservata con la sua distribuzione sotto un'ipotesi nulla. Il valore-*p* misura quanto il risultato sia incompatibile con quel modello, ma non assegna una probabilità all'ipotesi. La pratica contemporanea combina spesso la significatività fisheriana con le decisioni e il controllo degli errori di Neyman--Pearson.\n\n**Da saper fare**  Distinguere ipotesi, statistica test, distribuzione nulla, valore-*p* e livello $\\alpha$; interpretare correttamente errori di tipo I, errori di tipo II e potenza; separare significatività statistica, dimensione dell'effetto e rilevanza sostanziale.\n:::\n\n## Introduzione {.unnumbered .unlisted}\n\nNei capitoli precedenti abbiamo costruito una progressione:\n\n$$\n\\text{stima puntuale}\n\\longrightarrow\n\\text{errore standard}\n\\longrightarrow\n\\text{intervallo di confidenza}.\n$$\n\nIl test di ipotesi usa gli stessi elementi per affrontare una domanda diversa:\n\n> Quanto è incompatibile il risultato osservato con un modello di riferimento?\n\nNella ricerca psicologica, i test vengono usati per studiare differenze tra gruppi, associazioni tra variabili, effetti di interventi e scostamenti da valori teorici o normativi. La loro diffusione rende indispensabile comprenderne sia la logica sia i limiti.\n\nIl test frequentista standard non calcola la probabilità che un'ipotesi sia vera dopo aver osservato i dati. Costruisce invece una distribuzione dei risultati possibili sotto un'ipotesi nulla e colloca il risultato osservato all'interno di quella distribuzione.\n\n## Perché è facile fraintendere un test?\n\nIl linguaggio ordinario invita a leggere un test come un confronto diretto tra due spiegazioni:\n\n- l'ipotesi nulla è vera;\n- l'ipotesi alternativa è vera.\n\nLa procedura standard non assegna però probabilità posteriori a queste possibilità. La sua domanda è condizionale:\n\n> Se l'ipotesi nulla e le altre assunzioni del modello fossero appropriate, quanto sarebbe estremo il risultato osservato?\n\nL'inversione tra\n\n$$\nP(\\text{dati}\\mid H_0)\n$$\n\ne\n\n$$\nP(H_0\\mid\\text{dati})\n$$\n\nè una delle principali fonti di errore interpretativo.\n\n::: {.callout-important title=\"La direzione del condizionamento\"}\nIl valore-*p* riguarda la distribuzione dei dati o della statistica test **assumendo $H_0$**. Non è la probabilità di $H_0$ dopo avere osservato i dati.\n:::\n\n::: {.callout-tip title=\"Prerequisiti\"}\nÈ utile avere letto:\n\n- @sec-freq-stime-parametri, per stimatore, distribuzione campionaria ed errore standard;\n- @sec-frequentism-confidence-intervals, per copertura, valori critici e livello $\\alpha$;\n- il capitolo [Probabilità condizionata](https://ccaudek.github.io/utet-prob/chapters/probability/04_conditional_prob_bayesian.html), per distinguere $P(A\\mid B)$ da $P(B\\mid A)$.\n\nLa potenza viene introdotta qui come proprietà del test e sarà approfondita nel capitolo successivo sulla numerosità campionaria.\n:::\n\n## Panoramica del capitolo {.unnumbered .unlisted}\n\nIl capitolo procede in nove passaggi:\n\n1. distingue la significatività fisheriana dalla teoria dei test di Neyman--Pearson;\n2. identifica gli elementi che definiscono un test;\n3. introduce il valore-*p* e il livello $\\alpha$;\n4. presenta errori di tipo I, errori di tipo II e potenza;\n5. applica la logica al test del chi-quadrato;\n6. applica la stessa struttura a un test *t* per una media;\n7. chiarisce test monodirezionali e bidirezionali;\n8. separa significatività, grandezza dell'effetto e rilevanza sostanziale;\n9. confronta il tipo di domanda frequentista con quello bayesiano.\n\n::: {.callout-note title=\"Preparazione del notebook\"}\nPer eseguire gli esempi, prepara l'ambiente comune del progetto:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |>\n  source()\n```\n:::\n\n:::\n\n## Due tradizioni nella pratica contemporanea {#sec-freq-two-testing-traditions}\n\nLa pratica comunemente chiamata *NHST* (*Null Hypothesis Significance Testing*) combina spesso elementi provenienti da due tradizioni.\n\n### Fisher: significatività e incompatibilità\n\nNell'impostazione fisheriana, il valore-*p* è una misura graduata di quanto i dati risultino incompatibili con un'ipotesi nulla. Un valore piccolo segnala che il risultato osservato occupa una regione poco frequente della distribuzione nulla.\n\nQuesta lettura non richiede necessariamente una decisione automatica e definitiva. Il valore-*p* viene considerato insieme al disegno, alla qualità dei dati e alla conoscenza scientifica disponibile.\n\n### Neyman--Pearson: decisioni ed errori\n\nNell'impostazione Neyman--Pearson si specificano ipotesi, una regola decisionale e probabilità di errore valutate nelle ripetizioni. Diventano centrali:\n\n- il livello $\\alpha$;\n- l'errore di tipo I;\n- l'errore di tipo II;\n- la potenza;\n- la regione di rifiuto.\n\nLa decisione non dichiara che una delle ipotesi sia probabilmente vera. Applica una procedura progettata per controllare gli errori nel lungo periodo.\n\n::: {.callout-note title=\"Una procedura ibrida\"}\nLa regola\n\n> «calcolo un valore-*p* e, se $p\\leq0.05$, dichiaro il risultato significativo»\n\ncombina una misura fisheriana di incompatibilità con una soglia e una decisione di tipo Neyman--Pearson.\n\nQuesta pratica è diffusa, ma interpretarla correttamente richiede sapere che valore-*p* e livello $\\alpha$ non sono la stessa quantità.\n:::\n\n## Anatomia di un test {#sec-freq-test-anatomy}\n\nUn test è definito da più elementi. Il solo valore-*p* non basta a descriverlo.\n\n### Ipotesi nulla e alternativa\n\nL'**ipotesi nulla** $H_0$ specifica il modello di riferimento. L'**ipotesi alternativa** $H_1$ descrive i valori o i modelli rispetto ai quali la procedura deve essere sensibile.\n\nPer una media:\n\n$$\nH_0:\\mu=24.\n$$\n\nUn'alternativa bilaterale è:\n\n$$\nH_1:\\mu\\neq24,\n$$\n\nmentre un'alternativa unilaterale può essere:\n\n$$\nH_1:\\mu>24.\n$$\n\nL'ipotesi nulla non deve necessariamente rappresentare una teoria scientifica completa o «assenza di qualunque effetto». È una restrizione precisa del modello usata per derivare la distribuzione di riferimento.\n\n### Statistica test\n\nLa **statistica test** è una funzione dei dati progettata per misurare una discrepanza rilevante rispetto a $H_0$.\n\nEsempi comuni sono:\n\n- una statistica $z$;\n- una statistica $t$;\n- una statistica $\\chi^2$;\n- una statistica $F$;\n- una differenza, un rapporto o un coefficiente standardizzato.\n\nPer interpretare l'estremità occorre sapere quali valori della statistica siano più incompatibili con $H_0$.\n\n### Distribuzione sotto l'ipotesi nulla\n\nLa **distribuzione nulla** descrive i valori che la statistica test assumerebbe se $H_0$, il modello e il piano di analisi fossero corretti.\n\nPuò essere:\n\n- derivata esattamente;\n- ottenuta mediante un'approssimazione asintotica;\n- costruita attraverso permutazioni o simulazioni.\n\n### Regola di estremità\n\nIl valore-*p* dipende anche dalla regola che stabilisce quali risultati siano «almeno altrettanto estremi» di quello osservato.\n\nIn un test unilaterale superiore si considera una coda. In un test bilaterale si considerano discrepanze in entrambe le direzioni, secondo la procedura specificata.\n\n::: {.callout-warning title=\"Il valore-p non è determinato dai soli dati\"}\nDipende anche da:\n\n- ipotesi nulla;\n- statistica test;\n- distribuzione di riferimento;\n- scelta unilaterale o bilaterale;\n- regola di arresto, quando rilevante;\n- correzioni per confronti multipli;\n- altre decisioni previste dal piano di analisi.\n:::\n\n## Il valore-*p* {#sec-freq-p-value}\n\nIn forma generale, il valore-*p* è:\n\n> la probabilità, calcolata sotto $H_0$, di ottenere un valore della statistica test almeno altrettanto incompatibile con $H_0$ quanto quello osservato.\n\nIn simboli schematici:\n\n$$\np\n=\nP_{H_0}\n\\left(\nT(Y)\\text{ almeno altrettanto estremo di }T(y_{\\mathrm{obs}})\n\\right).\n$$\n\nUn valore-*p* piccolo indica che il risultato osservato occupa una regione rara della distribuzione nulla. Segnala quindi incompatibilità tra i dati e l'insieme delle assunzioni usate per costruire il test.\n\nNon identifica da solo quale assunzione sia inadeguata. Un valore piccolo può riflettere:\n\n- una deviazione reale dal valore nullo;\n- una specificazione errata del modello;\n- dipendenza o eterogeneità ignorata;\n- bias di campionamento o misurazione;\n- selezione analitica o confronti multipli non corretti.\n\n### Valore-*p* e livello $\\alpha$\n\nIl **valore-*p*** è calcolato dai dati. Il **livello $\\alpha$** è una soglia decisionale scelta prima dell'analisi.\n\nLa regola convenzionale è:\n\n- se $p\\leq\\alpha$, rifiutare $H_0$;\n- se $p>\\alpha$, non rifiutare $H_0$.\n\n«Non rifiutare» è intenzionale. Un risultato non significativo non prova che $H_0$ sia vera.\n\n::: {.callout-warning title=\"Che cosa non è un valore-p\"}\nIl valore-*p* non è:\n\n- $P(H_0\\mid\\text{dati})$;\n- la probabilità che il risultato sia «dovuto al caso»;\n- la probabilità che $H_1$ sia vera;\n- la dimensione dell'effetto;\n- la probabilità di replicare la significatività;\n- il tasso di falsi positivi tra tutti i risultati significativi pubblicati.\n:::\n\n## Errori di tipo I, errori di tipo II e potenza {#sec-freq-errors-power}\n\nUna procedura decisionale può produrre quattro combinazioni:\n\n| Stato rispetto alle ipotesi specificate | Rifiutare $H_0$ | Non rifiutare $H_0$ |\n|---|---:|---:|\n| $H_0$ vera | Errore di tipo I | Decisione corretta |\n| Alternativa specificata vera | Decisione corretta | Errore di tipo II |\n\n### Errore di tipo I\n\nL'errore di tipo I consiste nel rifiutare $H_0$ quando è vera. Sotto le condizioni previste dalla procedura:\n\n$$\nP(\\text{rifiutare }H_0\\mid H_0)=\\alpha.\n$$\n\nIl controllo vale per la procedura e per la famiglia di analisi definita. Se vengono provati molti test e riportati soltanto quelli significativi, il tasso effettivo di falsi positivi può superare quello nominale.\n\n### Errore di tipo II e potenza\n\nPer una specifica alternativa, l'errore di tipo II ha probabilità:\n\n$$\n\\beta\n=\nP(\\text{non rifiutare }H_0\\mid H_1).\n$$\n\nLa potenza è:\n\n$$\n1-\\beta\n=\nP(\\text{rifiutare }H_0\\mid H_1).\n$$\n\nLa potenza non è un unico numero indipendente dall'effetto. Dipende dal valore del parametro sotto l'alternativa, oltre che da:\n\n- numerosità campionaria;\n- variabilità;\n- livello $\\alpha$;\n- struttura del disegno;\n- test unilaterale o bilaterale;\n- qualità della misurazione.\n\n::: {.callout-note title=\"Perché la potenza viene ripresa nel prossimo capitolo\"}\nQui la potenza serve a comprendere la logica degli errori. Il capitolo successivo discuterà come scegliere un effetto bersaglio e una numerosità adeguata prima di raccogliere i dati.\n:::\n\n## Esempio 1: test del chi-quadrato di indipendenza {#sec-freq-chi-square-example}\n\nSupponiamo di studiare la relazione tra **stress percepito** e **qualità del sonno**.\n\n\n::: {#tbl-stress-sleep-observed .cell layout-align=\"center\" tbl-cap='Frequenze osservate per stress percepito e qualità del sonno.'}\n\n```{.r .cell-code}\nosservati <- matrix(\n  c(\n    42, 40,\n    19, 39\n  ),\n  nrow = 2,\n  byrow = TRUE,\n  dimnames = list(\n    Stress = c(\"Basso\", \"Alto\"),\n    Sonno = c(\"Buono\", \"Scarso\")\n  )\n)\n\nknitr::kable(osservati)\n```\n\n::: {.cell-output-display}\n\n\n|      | Buono| Scarso|\n|:-----|-----:|------:|\n|Basso |    42|     40|\n|Alto  |    19|     39|\n\n\n:::\n:::\n\n\nLe ipotesi sono:\n\n$$\nH_0:\n\\text{stress e qualità del sonno sono indipendenti},\n$$\n\n$$\nH_1:\n\\text{stress e qualità del sonno non sono indipendenti}.\n$$\n\n### Frequenze attese\n\nSotto l'indipendenza, la frequenza attesa nella cella $ij$ è:\n\n$$\nE_{ij}\n=\n\\frac{R_iC_j}{N},\n$$\n\ndove $R_i$ è il totale della riga, $C_j$ quello della colonna e $N$ il totale complessivo.\n\n\n::: {#tbl-stress-sleep-expected .cell layout-align=\"center\" tbl-cap='Frequenze attese sotto l\\'ipotesi nulla di indipendenza.'}\n\n```{.r .cell-code}\ntotali_riga <- rowSums(osservati)\ntotali_colonna <- colSums(osservati)\ntotale <- sum(osservati)\n\nattesi <- outer(totali_riga, totali_colonna) / totale\ndimnames(attesi) <- dimnames(osservati)\n\nknitr::kable(round(attesi, 2))\n```\n\n::: {.cell-output-display}\n\n\n|      | Buono| Scarso|\n|:-----|-----:|------:|\n|Basso |  35.7|   46.3|\n|Alto  |  25.3|   32.7|\n\n\n:::\n:::\n\n\n### Statistica test\n\nLa statistica è:\n\n$$\n\\chi^2\n=\n\\sum_{i=1}^{r}\n\\sum_{j=1}^{c}\n\\frac{(O_{ij}-E_{ij})^2}{E_{ij}}.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchi2_osservato <- sum((osservati - attesi)^2 / attesi)\ngradi_liberta <- (nrow(osservati) - 1) * (ncol(osservati) - 1)\np_chi <- pchisq(\n  chi2_osservato,\n  df = gradi_liberta,\n  lower.tail = FALSE\n)\n\nc(\n  chi_quadrato = chi2_osservato,\n  gradi_liberta = gradi_liberta,\n  valore_p = p_chi\n)\n#>  chi_quadrato gradi_liberta      valore_p \n#>          4.71          1.00          0.03\n```\n:::\n\n\nIl calcolo produce circa:\n\n$$\n\\chi^2(1)=4.71,\n\\qquad\np=0.030.\n$$\n\nVerifichiamo con R:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchisq.test(osservati, correct = FALSE)\n#> \n#> \tPearson's Chi-squared test\n#> \n#> data:  osservati\n#> X-squared = 5, df = 1, p-value = 0.03\n```\n:::\n\n\nDisattiviamo la correzione di continuità per riprodurre il calcolo manuale.\n\n### Visualizzazione\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx_massimo <- qchisq(0.999, df = gradi_liberta)\n\ndati_chi <- data.frame(\n  x = seq(0.001, x_massimo, length.out = 2000)\n)\n\ndati_chi$densita <- dchisq(dati_chi$x, df = gradi_liberta)\n\nggplot(dati_chi, aes(x = x, y = densita)) +\n  geom_line(linewidth = 0.9) +\n  geom_area(\n    data = subset(dati_chi, x >= chi2_osservato),\n    alpha = 0.35\n  ) +\n  geom_vline(\n    xintercept = chi2_osservato,\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  labs(\n    x = expression(chi^2),\n    y = \"Densità\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzione chi-quadrato sotto l'ipotesi nulla. L'area oltre la statistica osservata rappresenta il valore-p.](04_test_ipotesi_files/figure-html/fig-chi-square-p-value-1.png){#fig-chi-square-p-value fig-align='center' fig-alt='Curva della distribuzione chi-quadrato con una linea verticale sulla statistica osservata e la coda destra evidenziata.' width=85%}\n:::\n:::\n\n\nIn @fig-chi-square-p-value, l'area a destra di $\\chi^2_{\\mathrm{obs}}$ è circa 0.030. Al livello $\\alpha=0.05$, la procedura rifiuta l'ipotesi di indipendenza.\n\nUna formulazione appropriata è:\n\n> Nel campione è emersa un'associazione statisticamente significativa tra stress percepito e qualità del sonno, $\\chi^2(1)=4.71$, $p=0.030$.\n\nQuesta conclusione non indica:\n\n- la probabilità che le variabili siano associate;\n- la grandezza dell'associazione;\n- una relazione causale;\n- la validità delle categorie utilizzate.\n\nPer completare l'analisi occorre stimare la dimensione dell'associazione e discuterne il significato sostantivo.\n\n## Esempio 2: test *t* per una media {#sec-freq-one-sample-t-test}\n\nConsideriamo dieci punteggi di benessere psicologico e un valore normativo pari a 24.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npunteggi <- c(28, 22, 26, 18, 30, 24, 27, 17, 21, 25)\n\nn <- length(punteggi)\nmedia <- mean(punteggi)\ndeviazione_standard <- sd(punteggi)\nerrore_standard <- deviazione_standard / sqrt(n)\n\nc(\n  media = media,\n  deviazione_standard = deviazione_standard,\n  errore_standard = errore_standard,\n  n = n\n)\n#>               media deviazione_standard     errore_standard                   n \n#>               23.80                4.26                1.35               10.00\n```\n:::\n\n\nSupponiamo che l'ipotesi, formulata prima di osservare i dati, sia:\n\n$$\nH_0:\\mu=24,\n$$\n\n$$\nH_1:\\mu>24.\n$$\n\nLa statistica è:\n\n$$\nt\n=\n\\frac{\\bar X-\\mu_0}{S/\\sqrt n}.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmu_0 <- 24\n\nt_osservato <- (media - mu_0) / errore_standard\ngradi_liberta_t <- n - 1\np_unilaterale <- pt(\n  t_osservato,\n  df = gradi_liberta_t,\n  lower.tail = FALSE\n)\n\nc(\n  t = t_osservato,\n  gradi_liberta = gradi_liberta_t,\n  valore_p = p_unilaterale\n)\n#>             t gradi_liberta      valore_p \n#>        -0.148         9.000         0.557\n```\n:::\n\n\nOtteniamo circa:\n\n$$\nt(9)=-0.15,\n\\qquad\np=0.557.\n$$\n\nLa media osservata, 23.8, non è nella direzione dell'alternativa superiore. Non rifiutiamo $H_0$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(\n  punteggi,\n  mu = 24,\n  alternative = \"greater\"\n)\n#> \n#> \tOne Sample t-test\n#> \n#> data:  punteggi\n#> t = -0.1, df = 9, p-value = 0.6\n#> alternative hypothesis: true mean is greater than 24\n#> 95 percent confidence interval:\n#>  21.3  Inf\n#> sample estimates:\n#> mean of x \n#>      23.8\n```\n:::\n\n\nUna formulazione adeguata è:\n\n> I dati non forniscono evidenza, secondo questo test unilaterale, che la media sia superiore a 24, $t(9)=-0.15$, $p=0.557$.\n\nNon è adeguato concludere:\n\n> Abbiamo dimostrato che la media è uguale a 24.\n\nIl test non significativo lascia aperte molte possibilità, comprese una differenza piccola, dati poco informativi o una deviazione nella direzione opposta.\n\n## Test unilaterali e bilaterali {#sec-freq-one-two-sided}\n\nUn test bilaterale considera deviazioni in entrambe le direzioni:\n\n$$\nH_1:\\mu\\neq\\mu_0.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(\n  punteggi,\n  mu = 24,\n  alternative = \"two.sided\"\n)\n#> \n#> \tOne Sample t-test\n#> \n#> data:  punteggi\n#> t = -0.1, df = 9, p-value = 0.9\n#> alternative hypothesis: true mean is not equal to 24\n#> 95 percent confidence interval:\n#>  20.8 26.8\n#> sample estimates:\n#> mean of x \n#>      23.8\n```\n:::\n\n\nPer gli stessi dati, il valore-*p* bilaterale è circa 0.885.\n\nLa scelta tra test unilaterale e bilaterale deve essere motivata dalla domanda e definita prima di osservare i risultati. Scegliere a posteriori la coda favorevole altera il controllo dell'errore di tipo I.\n\nUn test unilaterale non dovrebbe essere usato soltanto per ottenere maggiore potenza. Deve essere scientificamente sensato escludere, dalla regola di evidenza, una deviazione nella direzione opposta.\n\n## Interpretare un risultato {#sec-freq-interpreting-test-result}\n\nUna lettura completa separa almeno quattro livelli.\n\n### Compatibilità con il modello nullo\n\nIl valore-*p* descrive quanto il risultato sia estremo sotto $H_0$ e le assunzioni del test.\n\n### Decisione procedurale\n\nIl confronto con $\\alpha$ applica una regola di rifiuto o non rifiuto.\n\n### Grandezza e precisione dell'effetto\n\nLa stima e l'intervallo di confidenza mostrano quanto è grande l'effetto e con quale precisione è stato stimato.\n\n### Significato scientifico\n\nLa rilevanza dipende da teoria, qualità della misura, disegno, costi, benefici e contesto applicativo.\n\n::: {.callout-important title=\"Significativo non significa importante\"}\nUn risultato può essere statisticamente significativo ma troppo piccolo per avere rilievo teorico o pratico.\n\nUn risultato non significativo può essere compatibile sia con effetti trascurabili sia con effetti rilevanti stimati con scarsa precisione.\n:::\n\n## Limiti e usi appropriati {#sec-freq-testing-limits}\n\n### La soglia crea una discontinuità decisionale\n\n$p=0.049$ e $p=0.051$ rappresentano livelli di incompatibilità molto simili. Trasformarli in categorie opposte può esagerare la differenza tra i risultati.\n\nLa soglia può essere utile in una procedura decisionale, ma non deve sostituire la lettura continua dei dati.\n\n### L'ipotesi nulla puntuale può essere poco informativa\n\nIn molti contesti, sapere che un effetto non è esattamente zero è meno utile che sapere se sia:\n\n- sufficientemente grande;\n- praticamente rilevante;\n- compatibile con una regione di equivalenza;\n- stabile tra popolazioni e contesti.\n\nLa difficoltà non rende sempre illegittima un'ipotesi puntuale. Indica che la domanda deve essere scelta in funzione dello scopo scientifico.\n\n### Un risultato non significativo non dimostra equivalenza\n\nPer sostenere che un effetto sia abbastanza piccolo da essere trascurabile occorre definire che cosa significhi «abbastanza piccolo» e usare una procedura adatta, come un test di equivalenza o un'analisi con una regione di effetti praticamente trascurabili.\n\n### Il valore-*p* è sensibile al piano di analisi\n\nArresto opzionale, confronti multipli, esclusioni flessibili e scelta post hoc delle analisi modificano le proprietà nominali della procedura. Preregistrazione, trasparenza e analisi di sensibilità aiutano a rendere interpretabili i risultati.\n\n### Il test non controlla la validità scientifica\n\nUn test può essere calcolato correttamente su:\n\n- un campione non rappresentativo;\n- una misura poco valida;\n- un disegno confuso;\n- un modello inadeguato.\n\nLa significatività non corregge questi problemi.\n\n::: {.callout-note title=\"Quando il test è utile\"}\nUn test frequentista è particolarmente interpretabile quando:\n\n- la domanda decisionale è definita prima dei dati;\n- il disegno consente di collegare il parametro alla domanda scientifica;\n- il modello e l'errore standard sono adeguati;\n- la famiglia di test è chiaramente specificata;\n- vengono riportati anche stime, intervalli e misure dell'effetto.\n:::\n\n## Confronto con l'inferenza bayesiana {#sec-freq-testing-bayes}\n\nIl confronto più utile parte dalle domande, non dagli slogan.\n\nUn test frequentista standard chiede:\n\n> Quanto è estremo il risultato sotto $H_0$?\n\nUn'analisi bayesiana può chiedere:\n\n> Come si distribuisce l'incertezza sul parametro dopo avere combinato prior e dati?\n\noppure, in un modello che assegna probabilità a ipotesi discrete:\n\n> Come cambiano le probabilità relative delle ipotesi dopo i dati?\n\nQueste non sono riformulazioni dello stesso numero. Un valore-*p* non è una probabilità a posteriori, e una probabilità a posteriori non possiede automaticamente il controllo frequentista degli errori.\n\nIl Companion approfondisce la fragilità del valore-*p* e mostra come il workflow bayesiano sposti l'attenzione verso modello generativo, distribuzione a posteriori, predizioni e controllo del modello. Il modulo frequentista conserva però una funzione indispensabile: permettere di leggere correttamente la letteratura e comprendere quali proprietà procedurali vengono garantite dai metodi classici.\n\n## Verso la pianificazione dello studio {#sec-freq-testing-to-sample-size}\n\nUn risultato non significativo può dipendere da:\n\n- un effetto assente o trascurabile;\n- un campione troppo piccolo;\n- una misura poco precisa;\n- grande eterogeneità;\n- un modello o un test poco sensibile.\n\nPer valutare in anticipo quanto uno studio sia informativo, occorre specificare:\n\n1. quale effetto minimo sia scientificamente rilevante;\n2. quale livello di errore di tipo I sia accettabile;\n3. quale potenza si desideri;\n4. quale variabilità e struttura dei dati siano plausibili.\n\nQuesti elementi conducono al capitolo successivo sulla pianificazione della numerosità campionaria.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIl test di ipotesi colloca una statistica osservata nella distribuzione che avrebbe sotto un'ipotesi nulla e un insieme di assunzioni. Il valore-*p* misura l'estremità del risultato in quella distribuzione; il confronto con $\\alpha$ applica una regola decisionale.\n\nLa distinzione tra Fisher e Neyman--Pearson chiarisce perché nella pratica convivano due usi:\n\n- il valore-*p* come misura graduata di incompatibilità;\n- il test come procedura di decisione con errori controllati.\n\nNessuno dei due usi autorizza a leggere il valore-*p* come probabilità dell'ipotesi o come misura dell'importanza dell'effetto.\n\nUna comunicazione scientifica adeguata affianca al risultato del test:\n\n- stima dell'effetto;\n- intervallo di confidenza;\n- informazioni sul disegno e sulle assunzioni;\n- valutazione della rilevanza sostantiva.\n\nIl prossimo capitolo completerà la logica decisionale studiando il rapporto tra effetto bersaglio, potenza e numerosità campionaria.\n\n## Esercizi {.unnumbered .unlisted}\n\n1. Qual è la differenza tra un valore-*p* e il livello $\\alpha$?\n\n2. Perché $p=0.03$ non significa che l'ipotesi nulla abbia una probabilità del 3% di essere vera?\n\n3. Quale ruolo svolge la regola di estremità nella definizione del valore-*p*?\n\n4. Un risultato produce $p=0.18$. Qual è la conclusione frequentista corretta? Quale conclusione non è giustificata?\n\n5. Perché la potenza non può essere descritta senza specificare un effetto sotto l'alternativa?\n\n6. Nel test del chi-quadrato emerge $p=0.030$. Quali informazioni importanti non sono contenute in questo numero?\n\n7. Perché scegliere un test unilaterale dopo aver osservato la direzione dell'effetto altera l'interpretazione del test?\n\n8. In che modo un'analisi bayesiana e un test frequentista formulano domande diverse sugli stessi dati?\n\n::: {.callout-tip title=\"Soluzioni\" collapse=\"true\"}\n1. Il valore-*p* è calcolato dai dati e misura l'estremità del risultato sotto $H_0$. $\\alpha$ è una soglia decisionale scelta prima dell'analisi per controllare l'errore di tipo I della procedura.\n\n2. Il 3% riguarda la probabilità di risultati almeno altrettanto estremi sotto $H_0$. Non riguarda la probabilità di $H_0$ condizionata ai dati.\n\n3. Stabilisce quali valori della statistica siano almeno altrettanto incompatibili con $H_0$ quanto quello osservato. Cambiando test unilaterale, bilaterale o statistica, può cambiare il valore-*p*.\n\n4. Al livello convenzionale 0.05, non si rifiuta $H_0$. Non è giustificato concludere che $H_0$ sia vera, che l'effetto sia esattamente zero o che i gruppi siano equivalenti.\n\n5. La probabilità di rifiutare $H_0$ cambia con la distanza tra il parametro vero e il valore nullo. Non esiste quindi una potenza unica per tutte le possibili alternative.\n\n6. Non contiene la grandezza dell'associazione, la sua precisione, la probabilità che l'associazione esista, l'eventuale causalità o la validità delle categorie e del disegno.\n\n7. La coda viene selezionata usando informazione già contenuta nei dati, mentre il calcolo nominale presuppone che la direzione sia stata fissata in anticipo. Il controllo dell'errore di tipo I non è più quello dichiarato.\n\n8. Il test frequentista valuta l'estremità dei dati sotto $H_0$. L'analisi bayesiana rappresenta l'incertezza a posteriori su parametri o ipotesi mediante prior, verosimiglianza e dati.\n:::\n\n::: {.callout-note title=\"Punti chiave\" collapse=\"true\"}\n- Un test richiede ipotesi, statistica test, distribuzione nulla e regola di estremità.\n- Il valore-*p* è calcolato sotto $H_0$ e non è la probabilità di $H_0$.\n- Il valore-*p* e il livello $\\alpha$ svolgono funzioni diverse.\n- La pratica NHST combina spesso elementi fisheriani e Neyman--Pearson.\n- Gli errori di tipo I e II e la potenza sono proprietà della procedura sotto condizioni specificate.\n- La potenza dipende dall'effetto sotto l'alternativa.\n- Non rifiutare $H_0$ non significa accettarla o dimostrare equivalenza.\n- Significatività statistica, dimensione dell'effetto e rilevanza sostantiva sono concetti distinti.\n- La qualità di un test dipende da disegno, misurazione, modello e piano di analisi.\n- Frequentismo e bayesianesimo rispondono a domande probabilistiche differenti.\n:::\n\n::: {.callout-note title=\"Ambiente di sviluppo\" collapse=\"true\"}\nLe informazioni sull'ambiente R possono essere ottenute con:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.5.2\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.1            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.0           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.2              fastmap_1.2.0         tensorA_0.36.2.1     \n#>  [7] digest_0.6.39         timechange_0.4.0      estimability_2.0.0   \n#> [10] lifecycle_1.0.5       magrittr_2.0.5        compiler_4.6.1       \n#> [13] rlang_1.3.0           tools_4.6.1           yaml_2.3.12          \n#> [16] knitr_1.51            labeling_0.4.3        bridgesampling_1.2-1 \n#> [19] htmlwidgets_1.6.4     pkgbuild_1.4.8        curl_7.1.0           \n#> [22] RColorBrewer_1.1-3    abind_1.4-8           purrr_1.2.2          \n#> [25] grid_4.6.1            stats4_4.6.1          xtable_1.8-8         \n#> [28] inline_0.3.21         emmeans_2.0.4         scales_1.4.0         \n#> [31] cli_3.6.6             mvtnorm_1.4-2         rmarkdown_2.31       \n#> [34] generics_0.1.4        otel_0.2.0            RcppParallel_5.1.11-2\n#> [37] cachem_1.1.0          stringr_1.6.0         parallel_4.6.1       \n#> [40] vctrs_0.7.3           V8_8.2.0              Matrix_1.7-6         \n#> [43] jsonlite_2.0.0        arrayhelpers_1.1-2    glue_1.8.1           \n#> [46] codetools_0.2-20      distributional_0.8.1  lubridate_1.9.5      \n#> [49] stringi_1.8.7         gtable_0.3.6          QuickJSR_1.10.0      \n#> [52] pillar_1.11.1         htmltools_0.5.9       Brobdingnag_1.2-9    \n#> [55] R6_2.6.1              textshaping_1.0.5     rprojroot_2.1.1      \n#> [58] evaluate_1.0.5        lattice_0.22-9        backports_1.5.1      \n#> [61] memoise_2.0.1         broom_1.0.13          snakecase_0.11.1     \n#> [64] rstantools_2.6.0      coda_0.19-4.1         gridExtra_2.3.1      \n#> [67] nlme_3.1-170          checkmate_2.3.4       xfun_0.60            \n#> [70] pkgconfig_2.0.3\n```\n:::\n\n:::\n",
    "supporting": [
      "04_test_ipotesi_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}