<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Modulo introduttivo sull’inferenza frequentista in psicologia, parte del progetto UTET a supporto del manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<title>3&nbsp; Intervalli di confidenza – Inferenza frequentista in psicologia</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/frequentist_inference/04_test_ipotesi.html" rel="next">
<link href="../../chapters/frequentist_inference/02_stime_parametri.html" rel="prev">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bd31b91f9ddb1a75e3744ba9797c8182.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-662b1d839dd28a08d17be9d78b753e45.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bd31b91f9ddb1a75e3744ba9797c8182.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-3ca9c56ae126dfd2ea2ee80a8ddf12cc.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-40bbec47d005422d220f4664576d5232.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-3ca9c56ae126dfd2ea2ee80a8ddf12cc.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script><script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script><script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"headline",
  "consent_type":"express",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"it"
  });
});
</script><style>html{ scroll-behavior: smooth; }</style>
<link href="../../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../../site_libs/pagedtable-1.1/js/pagedtable.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<meta property="og:title" content="3&nbsp; Intervalli di confidenza – Inferenza frequentista in psicologia">
<meta property="og:description" content="Modulo introduttivo sull’inferenza frequentista in psicologia, parte del progetto UTET a supporto del manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<meta property="og:image" content="https://ccaudek.github.io/utet-frequentista/chapters/frequentist_inference/03_conf_interv_files/figure-html/fig-ci-coverage-1.png">
<meta property="og:site_name" content="Inferenza frequentista in psicologia">
<meta property="og:image:alt" content="Cinquanta segmenti orizzontali rappresentano intervalli di confidenza; alcuni non attraversano la linea della media vera.">
<meta property="og:image:height" content="1297">
<meta property="og:image:width" content="2100">
<meta name="twitter:title" content="3&nbsp; Intervalli di confidenza – Inferenza frequentista in psicologia">
<meta name="twitter:description" content="Modulo introduttivo sull’inferenza frequentista in psicologia, parte del progetto UTET a supporto del manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<meta name="twitter:image" content="https://ccaudek.github.io/utet-frequentista/chapters/frequentist_inference/03_conf_interv_files/figure-html/fig-ci-coverage-1.png">
<meta name="twitter:image:alt" content="Cinquanta segmenti orizzontali rappresentano intervalli di confidenza; alcuni non attraversano la linea della media vera.">
<meta name="twitter:image-height" content="1297">
<meta name="twitter:image-width" content="2100">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://ccaudek.github.io/utet-frequentista/chapters/frequentist_inference/03_conf_interv.html">
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/frequentist_inference/introduction_frequentist_inference.html">Frequentismo</a></li><li class="breadcrumb-item"><a href="../../chapters/frequentist_inference/03_conf_interv.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Intervalli di confidenza</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Inferenza frequentista in psicologia</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://ccaudek.github.io/utet-companion/" title="Manuale e companion" class="quarto-navigation-tool px-1" aria-label="Manuale e companion"><i class="bi bi-book"></i></a>
    <a href="https://github.com/ccaudek/utet-frequentista/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Attiva/disattiva la modalità oscura"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
    <div id="quarto-search" class="quarto-navigation-tool px-1" title="Ricerca"></div>
</div>
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Come usare il modulo</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Frequentismo</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/introduction_frequentist_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione all’inferenza frequentista in un percorso bayesiano</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/01_galton.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Origini storiche dell’approccio frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/02_stime_parametri.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Stime, stimatori e parametri</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/03_conf_interv.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Intervalli di confidenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/04_test_ipotesi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Test di ipotesi e valore-<em>p</em></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/05_sample_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Dimensione campionaria, precisione e potenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/06_two_ind_samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Confrontare due gruppi indipendenti</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Epilogo</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epilogo/epilogo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conclusioni</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2"><h2 id="toc-title">Sommario</h2>
   
  <ul class="collapse">
<li><a href="#perch%C3%A9-una-stima-puntuale-non-basta" id="toc-perché-una-stima-puntuale-non-basta" class="nav-link active" data-scroll-target="#perch%C3%A9-una-stima-puntuale-non-basta"><span class="header-section-number">3.1</span> Perché una stima puntuale non basta?</a></li>
  <li><a href="#sec-freq-from-point-to-interval" id="toc-sec-freq-from-point-to-interval" class="nav-link" data-scroll-target="#sec-freq-from-point-to-interval"><span class="header-section-number">3.2</span> Dalla stima all’intervallo</a></li>
  <li><a href="#sec-freq-ci-known-variance" id="toc-sec-freq-ci-known-variance" class="nav-link" data-scroll-target="#sec-freq-ci-known-variance"><span class="header-section-number">3.3</span> Caso ideale: media con varianza nota</a></li>
  <li><a href="#sec-freq-ci-unknown-variance" id="toc-sec-freq-ci-unknown-variance" class="nav-link" data-scroll-target="#sec-freq-ci-unknown-variance"><span class="header-section-number">3.4</span> Caso usuale: media con varianza ignota</a></li>
  <li><a href="#sec-freq-ci-example-r" id="toc-sec-freq-ci-example-r" class="nav-link" data-scroll-target="#sec-freq-ci-example-r"><span class="header-section-number">3.5</span> Un esempio numerico</a></li>
  <li><a href="#sec-freq-coverage-logic" id="toc-sec-freq-coverage-logic" class="nav-link" data-scroll-target="#sec-freq-coverage-logic"><span class="header-section-number">3.6</span> La logica della copertura</a></li>
  <li><a href="#sec-freq-ci-misinterpretations" id="toc-sec-freq-ci-misinterpretations" class="nav-link" data-scroll-target="#sec-freq-ci-misinterpretations"><span class="header-section-number">3.7</span> Interpretazioni corrette e fraintendimenti</a></li>
  <li><a href="#sec-freq-ci-width" id="toc-sec-freq-ci-width" class="nav-link" data-scroll-target="#sec-freq-ci-width"><span class="header-section-number">3.8</span> Che cosa determina l’ampiezza?</a></li>
  <li><a href="#sec-freq-ci-assumptions" id="toc-sec-freq-ci-assumptions" class="nav-link" data-scroll-target="#sec-freq-ci-assumptions"><span class="header-section-number">3.9</span> Intervalli e validità del modello</a></li>
  <li><a href="#sec-freq-ci-vs-credible" id="toc-sec-freq-ci-vs-credible" class="nav-link" data-scroll-target="#sec-freq-ci-vs-credible"><span class="header-section-number">3.10</span> Intervalli di confidenza e intervalli di credibilità</a></li>
  <li><a href="#sec-freq-ci-to-hypothesis-testing" id="toc-sec-freq-ci-to-hypothesis-testing" class="nav-link" data-scroll-target="#sec-freq-ci-to-hypothesis-testing"><span class="header-section-number">3.11</span> Dall’intervallo al test di ipotesi</a></li>
  </ul><div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/utet-frequentista/issues/new" class="toc-action"><i class="bi bi-github"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/frequentist_inference/introduction_frequentist_inference.html">Frequentismo</a></li><li class="breadcrumb-item"><a href="../../chapters/frequentist_inference/03_conf_interv.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Intervalli di confidenza</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-frequentism-confidence-intervals" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Intervalli di confidenza</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-default callout-note callout-titled" title="In sintesi">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>In sintesi
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Da sapere</strong> Un intervallo di confidenza combina una stima puntuale con una misura della sua variabilità campionaria. Il livello di confidenza descrive la frequenza con cui la procedura contiene il parametro nelle ripetizioni previste dal modello e non assegna una probabilità al parametro all’interno dell’intervallo osservato.</p>
<p><strong>Da saper fare</strong> Al termine del capitolo, il lettore dovrebbe saper interpretare correttamente un intervallo di confidenza, distinguere copertura, precisione e validità, spiegare il ruolo dell’errore standard, del valore critico e della dimensione campionaria e confrontare gli intervalli di confidenza con gli intervalli di credibilità senza confonderne il significato.</p>
</div>
</div>
<section id="introduzione" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="introduzione">Introduzione</h2>
<p>Nel capitolo precedente abbiamo distinto il parametro, lo stimatore e la stima. Abbiamo inoltre visto che una stima puntuale, come una media campionaria, descrive il valore assunto dallo stimatore nel campione osservato, ma non comunica quanto quel valore potrebbe cambiare se il campionamento fosse ripetuto nelle stesse condizioni.</p>
<p>L’intervallo di confidenza nasce per integrare queste due informazioni. Parte dalla distribuzione campionaria dello stimatore e costruisce, intorno alla stima osservata, un intervallo mediante una procedura progettata per raggiungere una determinata frequenza di copertura.</p>
<p>La difficoltà principale non riguarda il calcolo, ma l’interpretazione. Un intervallo di confidenza al 95% non significa che il parametro abbia il 95% di probabilità di trovarsi tra i due estremi osservati. Il 95% qualifica la procedura prima dell’osservazione dei dati: sotto il modello e il piano di campionamento assunti, il 95% degli intervalli prodotti in ripetizioni analoghe contiene il parametro vero.</p>
<p>Comprendere questa distinzione permette di usare gli intervalli in modo informativo senza attribuire loro un significato probabilistico che appartiene a un’altra costruzione inferenziale.</p>
</section><section id="perché-una-stima-puntuale-non-basta" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="perché-una-stima-puntuale-non-basta">
<span class="header-section-number">3.1</span> Perché una stima puntuale non basta?</h2>
<p>Supponiamo di osservare una media campionaria pari a 24.8. Questo numero risponde a una domanda precisa:</p>
<blockquote class="blockquote">
<p>Quale valore ha assunto lo stimatore nel campione osservato?</p>
</blockquote>
<p>Non risponde però a una seconda domanda, altrettanto importante:</p>
<blockquote class="blockquote">
<p>Quanto cambierebbe la stima se osservassimo un altro campione generato nelle stesse condizioni?</p>
</blockquote>
<p>Due studi possono produrre la stessa media e, nello stesso tempo, offrire livelli di precisione molto differenti. La stima puntuale, considerata da sola, non rende visibile questa differenza. L’intervallo di confidenza aggiunge l’informazione sulla variabilità campionaria combinando la stima, l’errore standard e un valore critico associato al livello di confidenza scelto.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Precisione, non garanzia di verità">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Precisione, non garanzia di verità
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un intervallo stretto indica che, nelle condizioni assunte, la procedura produce stime poco variabili da un campione all’altro. Non garantisce che il campione sia rappresentativo, che la misura sia valida o che il modello descriva adeguatamente il processo che ha generato i dati.</p>
<p>Una stima può essere molto precisa e, nello stesso tempo, sistematicamente fuorviante.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Prerequisiti">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Prerequisiti
</div>
</div>
<div class="callout-body-container callout-body">
<p>Per seguire il capitolo è utile avere letto <a href="02_stime_parametri.html" class="quarto-xref"><span>Capitolo 2</span></a>, dove sono state introdotte la distinzione tra parametro, stimatore e stima e la nozione di errore standard. È inoltre consigliabile richiamare il capitolo <a href="https://ccaudek.github.io/utet-prob/chapters/probability/13_from_sample_to_evidence.html">Dal campione all’evidenza</a>, dedicato alla distribuzione campionaria, e l’introduzione al modulo frequentista, nella quale è stata distinta la probabilità della procedura dall’incertezza sul parametro.</p>
<p>Qui utilizzeremo questi concetti senza ripeterne la teoria probabilistica.</p>
</div>
</div>
</section><section id="panoramica-del-capitolo" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="panoramica-del-capitolo">Panoramica del capitolo</h2>
<p>Il capitolo procede dalla forma generale di un intervallo di confidenza ai due casi fondamentali della media con varianza nota e ignota. Un esempio numerico in R mostrerà come costruire l’intervallo <em>t</em>, mentre una simulazione renderà visibile la logica della copertura. La parte successiva esaminerà i fraintendimenti più comuni e chiarirà come l’ampiezza dell’intervallo dipenda dalla variabilità, dal livello di confidenza, dalla dimensione campionaria e dalle assunzioni della procedura. Il confronto con gli intervalli di credibilità permetterà infine di distinguere due modi diversi di rappresentare l’incertezza e preparerà il passaggio ai test di ipotesi.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Preparazione del notebook">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Preparazione del notebook
</div>
</div>
<div class="callout-body-container callout-body">
<p>Per eseguire gli esempi, prepara l’ambiente comune del progetto:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</section><section id="sec-freq-from-point-to-interval" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="sec-freq-from-point-to-interval">
<span class="header-section-number">3.2</span> Dalla stima all’intervallo</h2>
<p>Molti intervalli di confidenza possono essere espressi nella forma</p>
<p><span class="math display">\[
\text{stima}
\;\pm\;
\text{valore critico}
\times
\text{errore standard}.
\]</span></p>
<p>Il prodotto tra il valore critico e l’errore standard prende il nome di <strong>margine di errore</strong>. La stima determina il centro dell’intervallo; l’errore standard descrive la variabilità campionaria dello stimatore; il valore critico stabilisce quanto occorre allontanarsi dal centro per ottenere il livello di copertura desiderato.</p>
<p>Questa forma non è universale. Esistono intervalli asimmetrici, intervalli basati sulla verosimiglianza, intervalli bootstrap e procedure specifiche per proporzioni, varianze e coefficienti di regressione. Il caso della media rimane tuttavia un punto di partenza particolarmente utile, perché rende visibile la struttura fondamentale della costruzione frequentista.</p>
</section><section id="sec-freq-ci-known-variance" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="sec-freq-ci-known-variance">
<span class="header-section-number">3.3</span> Caso ideale: media con varianza nota</h2>
<p>Consideriamo osservazioni indipendenti provenienti da una popolazione normale con media ignota <span class="math inline">\(\mu\)</span> e deviazione standard nota <span class="math inline">\(\sigma\)</span>. La media campionaria ha distribuzione</p>
<p><span class="math display">\[
\bar X
\sim
\mathcal{N}\!\left(
\mu,
\frac{\sigma^2}{n}
\right).
\]</span></p>
<p>Di conseguenza,</p>
<p><span class="math display">\[
Z
=
\frac{\bar X-\mu}{\sigma/\sqrt n}
\sim
\mathcal{N}(0,1).
\]</span></p>
<p>Per un livello di confidenza del 95% vale la relazione</p>
<p><span class="math display">\[
P(-1.96 \le Z \le 1.96)=0.95.
\]</span></p>
<p>Sostituendo la definizione di <span class="math inline">\(Z\)</span> e riordinando la disuguaglianza otteniamo</p>
<p><span class="math display">\[
P\!\left(
\bar X-1.96\frac{\sigma}{\sqrt n}
\le
\mu
\le
\bar X+1.96\frac{\sigma}{\sqrt n}
\right)
=
0.95.
\]</span></p>
<p>Prima che il campione venga osservato, gli estremi dell’intervallo sono variabili casuali perché dipendono da <span class="math inline">\(\bar X\)</span>. La procedura produce quindi un intervallo casuale che contiene il parametro nel 95% delle ripetizioni previste dal modello.</p>
<p>Dopo l’osservazione dei dati, la situazione cambia. Gli estremi diventano due valori numerici e il parametro, nel modello frequentista, rimane fisso. Il particolare intervallo ottenuto contiene il parametro oppure non lo contiene. La probabilità del 95% continua a descrivere il comportamento della procedura nel lungo periodo e non si trasferisce al parametro.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Dove si trova la probabilità?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Dove si trova la probabilità?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nell’espressione precedente, la probabilità riguarda gli estremi casuali dell’intervallo prima dell’osservazione dei dati. Non riguarda una distribuzione di probabilità assegnata a <span class="math inline">\(\mu\)</span>.</p>
</div>
</div>
</section><section id="sec-freq-ci-unknown-variance" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="sec-freq-ci-unknown-variance">
<span class="header-section-number">3.4</span> Caso usuale: media con varianza ignota</h2>
<p>Nella ricerca psicologica, la deviazione standard della popolazione <span class="math inline">\(\sigma\)</span> è quasi sempre ignota. Viene quindi sostituita con la deviazione standard campionaria <span class="math inline">\(s\)</span>.</p>
<p>Se le osservazioni sono indipendenti e provengono da una popolazione normale, la statistica</p>
<p><span class="math display">\[
T
=
\frac{\bar X-\mu}{s/\sqrt n}
\]</span></p>
<p>segue esattamente una distribuzione <em>t</em> di Student con <span class="math inline">\(n-1\)</span> gradi di libertà:</p>
<p><span class="math display">\[
T\sim t_{n-1}.
\]</span></p>
<p>L’intervallo bilaterale al livello <span class="math inline">\(1-\alpha\)</span> è pertanto</p>
<p><span class="math display">\[
\bar X
\pm
t_{1-\alpha/2,\;n-1}
\frac{s}{\sqrt n}.
\]</span></p>
<p>La distribuzione <em>t</em> possiede code più pesanti della normale standard. Nei campioni piccoli il valore critico risulta quindi più grande e l’intervallo più ampio, perché la stima di <span class="math inline">\(\sigma\)</span> introduce un’ulteriore fonte di incertezza. All’aumentare dei gradi di libertà, la distribuzione <em>t</em> si avvicina progressivamente alla normale standard.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Esatto e approssimato">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Avviso</span>Esatto e approssimato
</div>
</div>
<div class="callout-body-container callout-body">
<p>L’intervallo <em>t</em> classico possiede copertura esatta quando le osservazioni sono indipendenti e la popolazione è normale.</p>
<p>Con campioni grandi può essere utilizzato come approssimazione anche quando la distribuzione non è perfettamente normale. La qualità dell’approssimazione dipende tuttavia dalla forma della distribuzione, dalla presenza di valori estremi e dalla struttura di dipendenza. Una numerosità elevata non rende irrilevante qualunque violazione delle assunzioni.</p>
</div>
</div>
</section><section id="sec-freq-ci-example-r" class="level2" data-number="3.5"><h2 data-number="3.5" class="anchored" data-anchor-id="sec-freq-ci-example-r">
<span class="header-section-number">3.5</span> Un esempio numerico</h2>
<p>Consideriamo dieci punteggi di benessere psicologico:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">punteggi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">28</span>, <span class="fl">22</span>, <span class="fl">26</span>, <span class="fl">18</span>, <span class="fl">30</span>, <span class="fl">24</span>, <span class="fl">27</span>, <span class="fl">17</span>, <span class="fl">21</span>, <span class="fl">25</span><span class="op">)</span></span>
<span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">punteggi</span><span class="op">)</span></span>
<span><span class="va">media</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">punteggi</span><span class="op">)</span></span>
<span><span class="va">dev_std</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">punteggi</span><span class="op">)</span></span>
<span><span class="va">errore_standard</span> <span class="op">&lt;-</span> <span class="va">dev_std</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  media <span class="op">=</span> <span class="va">media</span>,</span>
<span>  deviazione_standard <span class="op">=</span> <span class="va">dev_std</span>,</span>
<span>  errore_standard <span class="op">=</span> <span class="va">errore_standard</span>,</span>
<span>  n <span class="op">=</span> <span class="va">n</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt;               media deviazione_standard     errore_standard                   n </span></span>
<span><span class="co">#&gt;               23.80                4.26                1.35               10.00</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>La media osservata è 23.8, la deviazione standard campionaria è circa 4.26 e l’errore standard è circa 1.35. Queste tre quantità descrivono aspetti differenti dei dati. La media individua il centro del campione, la deviazione standard riassume la variabilità tra i punteggi individuali e l’errore standard esprime quanto la media campionaria tenderebbe a cambiare da un campione all’altro.</p>
<p>Calcoliamo manualmente l’intervallo di confidenza al 95%:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">alpha</span> <span class="op">&lt;-</span> <span class="fl">0.05</span></span>
<span><span class="va">t_star</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">alpha</span> <span class="op">/</span> <span class="fl">2</span>, df <span class="op">=</span> <span class="va">n</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">margine_errore</span> <span class="op">&lt;-</span> <span class="va">t_star</span> <span class="op">*</span> <span class="va">errore_standard</span></span>
<span></span>
<span><span class="va">limite_inferiore</span> <span class="op">&lt;-</span> <span class="va">media</span> <span class="op">-</span> <span class="va">margine_errore</span></span>
<span><span class="va">limite_superiore</span> <span class="op">&lt;-</span> <span class="va">media</span> <span class="op">+</span> <span class="va">margine_errore</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  t_critico <span class="op">=</span> <span class="va">t_star</span>,</span>
<span>  margine_errore <span class="op">=</span> <span class="va">margine_errore</span>,</span>
<span>  limite_inferiore <span class="op">=</span> <span class="va">limite_inferiore</span>,</span>
<span>  limite_superiore <span class="op">=</span> <span class="va">limite_superiore</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt;        t_critico   margine_errore limite_inferiore limite_superiore </span></span>
<span><span class="co">#&gt;             2.26             3.05            20.75            26.85</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Otteniamo approssimativamente</p>
<p><span class="math display">\[
23.8
\pm
2.262\times1.348
=
[20.75,\;26.85].
\]</span></p>
<p>La stessa procedura è disponibile in R:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">punteggi</span>, conf.level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  One Sample t-test</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; data:  punteggi</span></span>
<span><span class="co">#&gt; t = 18, df = 9, p-value = 3e-08</span></span>
<span><span class="co">#&gt; alternative hypothesis: true mean is not equal to 0</span></span>
<span><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span><span class="co">#&gt;  20.8 26.8</span></span>
<span><span class="co">#&gt; sample estimates:</span></span>
<span><span class="co">#&gt; mean of x </span></span>
<span><span class="co">#&gt;      23.8</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>La funzione <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> restituisce anche una statistica test e un valore-<span class="math inline">\(p\)</span>. In questo capitolo utilizziamo soltanto l’intervallo; la logica dei test di ipotesi verrà introdotta nel capitolo successivo.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Come comunicare il risultato">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Come comunicare il risultato
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una formulazione appropriata è la seguente:</p>
<blockquote class="blockquote">
<p>Nel campione, il punteggio medio di benessere è 23.8. L’intervallo di confidenza al 95% per la media, costruito mediante la procedura <em>t</em>, è [20.75, 26.85].</p>
</blockquote>
<p>È opportuno riportare anche l’unità di misura, la numerosità campionaria e le condizioni dell’analisi.</p>
<p>Una formulazione da evitare è invece:</p>
<blockquote class="blockquote">
<p>C’è il 95% di probabilità che la media vera sia compresa tra 20.75 e 26.85.</p>
</blockquote>
</div>
</div>
</section><section id="sec-freq-coverage-logic" class="level2" data-number="3.6"><h2 data-number="3.6" class="anchored" data-anchor-id="sec-freq-coverage-logic">
<span class="header-section-number">3.6</span> La logica della copertura</h2>
<p>La <strong>copertura</strong> è la proporzione di intervalli che contengono il parametro quando la procedura viene ripetuta secondo il modello e il piano di campionamento specificati.</p>
<p>Per rendere visibile questa idea, simuliamo molti campioni da una popolazione normale con media nota e costruiamo un intervallo <em>t</em> per ciascun campione.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span></span>
<span></span>
<span><span class="va">mu_vero</span> <span class="op">&lt;-</span> <span class="fl">50</span></span>
<span><span class="va">sigma_vera</span> <span class="op">&lt;-</span> <span class="fl">10</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">25</span></span>
<span><span class="va">n_simulazioni</span> <span class="op">&lt;-</span> <span class="fl">1000</span></span>
<span></span>
<span><span class="va">intervalli</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">replicate</a></span><span class="op">(</span><span class="va">n_simulazioni</span>, <span class="op">{</span></span>
<span>  <span class="va">campione</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span>, mean <span class="op">=</span> <span class="va">mu_vero</span>, sd <span class="op">=</span> <span class="va">sigma_vera</span><span class="op">)</span></span>
<span>  <span class="va">ic</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">campione</span>, conf.level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span><span class="op">$</span><span class="va">conf.int</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>inferiore <span class="op">=</span> <span class="va">ic</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, superiore <span class="op">=</span> <span class="va">ic</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="op">}</span><span class="op">)</span></span>
<span></span>
<span><span class="va">contiene_mu</span> <span class="op">&lt;-</span> <span class="va">intervalli</span><span class="op">[</span><span class="st">"inferiore"</span>, <span class="op">]</span> <span class="op">&lt;=</span> <span class="va">mu_vero</span> <span class="op">&amp;</span></span>
<span>  <span class="va">intervalli</span><span class="op">[</span><span class="st">"superiore"</span>, <span class="op">]</span> <span class="op">&gt;=</span> <span class="va">mu_vero</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">contiene_mu</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0.948</span></span>
<span></span>
<span><span class="va">n_mostra</span> <span class="op">&lt;-</span> <span class="fl">50</span></span>
<span></span>
<span><span class="va">dati_grafico</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  campione <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">n_mostra</span><span class="op">)</span>,</span>
<span>  inferiore <span class="op">=</span> <span class="va">intervalli</span><span class="op">[</span><span class="st">"inferiore"</span>, <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">n_mostra</span><span class="op">)</span><span class="op">]</span>,</span>
<span>  superiore <span class="op">=</span> <span class="va">intervalli</span><span class="op">[</span><span class="st">"superiore"</span>, <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">n_mostra</span><span class="op">)</span><span class="op">]</span>,</span>
<span>  contiene <span class="op">=</span> <span class="va">contiene_mu</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">n_mostra</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span></span>
<span>  <span class="va">dati_grafico</span>,</span>
<span>  <span class="fu">aes</span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="va">campione</span>,</span>
<span>    y <span class="op">=</span> <span class="va">inferiore</span>,</span>
<span>    yend <span class="op">=</span> <span class="va">superiore</span>,</span>
<span>    linetype <span class="op">=</span> <span class="va">contiene</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_segment</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>xend <span class="op">=</span> <span class="va">campione</span><span class="op">)</span>, linewidth <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="va">mu_vero</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">coord_flip</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="st">"Campione simulato"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Intervallo di confidenza"</span>,</span>
<span>    linetype <span class="op">=</span> <span class="st">"Contiene la media vera"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-ci-coverage" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Cinquanta segmenti orizzontali rappresentano intervalli di confidenza; alcuni non attraversano la linea della media vera." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ci-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="03_conf_interv_files/figure-html/fig-ci-coverage-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figura&nbsp;3.1: Cinquanta intervalli di confidenza al 95% ottenuti da campioni ripetuti. La linea tratteggiata indica la media vera."><img src="03_conf_interv_files/figure-html/fig-ci-coverage-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%" alt="Cinquanta segmenti orizzontali rappresentano intervalli di confidenza; alcuni non attraversano la linea della media vera."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ci-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.1: Cinquanta intervalli di confidenza al 95% ottenuti da campioni ripetuti. La linea tratteggiata indica la media vera.
</figcaption></figure>
</div>
</div>
</div>
<p>In una simulazione finita, la copertura empirica oscilla intorno al 95% e non deve coincidere esattamente con 0.95. <a href="#fig-ci-coverage" class="quarto-xref">Figura&nbsp;<span>3.1</span></a> mostra inoltre che alcuni intervalli non contengono il parametro. Il livello di confidenza non permette di identificare, dopo l’osservazione, quali intervalli appartengano a questo gruppo.</p>
<p>Questo è il punto centrale della costruzione frequentista. La procedura possiede una determinata frequenza di successo nel lungo periodo, ma la proprietà di copertura non si trasforma in una probabilità riferita al singolo intervallo osservato.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Copertura nominale e copertura effettiva">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Copertura nominale e copertura effettiva
</div>
</div>
<div class="callout-body-container callout-body">
<p>Il 95% è una proprietà nominale della procedura sotto determinate assunzioni.</p>
<p>Se il modello, l’indipendenza, il piano di campionamento o il metodo di calcolo non sono appropriati, la copertura effettiva può essere diversa dal valore nominale.</p>
</div>
</div>
</section><section id="sec-freq-ci-misinterpretations" class="level2" data-number="3.7"><h2 data-number="3.7" class="anchored" data-anchor-id="sec-freq-ci-misinterpretations">
<span class="header-section-number">3.7</span> Interpretazioni corrette e fraintendimenti</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th>Affermazione</th>
<th>Valutazione</th>
<th>Motivo</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>«La procedura produce intervalli che contengono il parametro nel 95% delle ripetizioni previste dal modello.»</td>
<td>Corretta</td>
<td>Descrive la copertura frequentista.</td>
</tr>
<tr class="even">
<td>«Il parametro ha il 95% di probabilità di trovarsi in questo intervallo.»</td>
<td>Scorretta</td>
<td>Il parametro è fisso nel modello frequentista; la probabilità riguarda la procedura.</td>
</tr>
<tr class="odd">
<td>«Il 95% dei valori individuali si trova nell’intervallo.»</td>
<td>Scorretta</td>
<td>L’intervallo riguarda un parametro, non la dispersione dei punteggi individuali.</td>
</tr>
<tr class="even">
<td>«I valori centrali sono più probabili di quelli vicini agli estremi.»</td>
<td>Non giustificata</td>
<td>L’intervallo non è una distribuzione di probabilità sul parametro.</td>
</tr>
<tr class="odd">
<td>«Un intervallo più stretto indica maggiore precisione campionaria, a parità di metodo e livello di confidenza.»</td>
<td>Corretta</td>
<td>L’ampiezza dipende dall’errore standard e dal valore critico.</td>
</tr>
<tr class="even">
<td>«Tutti i valori interni sono ugualmente plausibili.»</td>
<td>Non giustificata</td>
<td>La procedura non assegna probabilità o plausibilità ai singoli valori del parametro.</td>
</tr>
</tbody>
</table>
<p>Un intervallo di confidenza viene talvolta descritto come l’insieme dei valori <strong>compatibili con i dati</strong>. Questa formulazione può essere utile, purché venga completata. Si tratta dei valori non esclusi dalla procedura, dato il modello, le assunzioni e il livello di confidenza scelto.</p>
<p>L’espressione non implica che tutti i valori interni siano ugualmente credibili, né che quelli esterni siano impossibili. L’intervallo riassume l’esito di una regola inferenziale, non una distribuzione di plausibilità sui possibili valori del parametro.</p>
</section><section id="sec-freq-ci-width" class="level2" data-number="3.8"><h2 data-number="3.8" class="anchored" data-anchor-id="sec-freq-ci-width">
<span class="header-section-number">3.8</span> Che cosa determina l’ampiezza?</h2>
<p>L’ampiezza di un intervallo dipende dal modo in cui la procedura combina la variabilità dello stimatore con il livello di copertura desiderato.</p>
<section id="errore-standard" class="level3" data-number="3.8.1"><h3 data-number="3.8.1" class="anchored" data-anchor-id="errore-standard">
<span class="header-section-number">3.8.1</span> Errore standard</h3>
<p>A parità di valore critico, un errore standard maggiore produce un intervallo più ampio. L’errore standard dipende dalla variabilità dei dati, dalla dimensione campionaria e dalla struttura dello stimatore. Quando la procedura stima il parametro con maggiore variabilità, l’intervallo deve estendersi maggiormente intorno alla stima osservata.</p>
</section><section id="livello-di-confidenza" class="level3" data-number="3.8.2"><h3 data-number="3.8.2" class="anchored" data-anchor-id="livello-di-confidenza">
<span class="header-section-number">3.8.2</span> Livello di confidenza</h3>
<p>Aumentare il livello di confidenza richiede un valore critico più grande. Sullo stesso campione, un intervallo al 99% è quindi più ampio di uno al 95%, che a sua volta è più ampio di uno al 90%.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">livelli</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.80</span>, <span class="fl">0.90</span>, <span class="fl">0.95</span>, <span class="fl">0.99</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  livello <span class="op">=</span> <span class="va">livelli</span>,</span>
<span>  t_critico <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">livelli</span><span class="op">)</span> <span class="op">/</span> <span class="fl">2</span>, df <span class="op">=</span> <span class="va">n</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/transform.html">transform</a></span><span class="op">(</span></span>
<span>    limite_inferiore <span class="op">=</span></span>
<span>      <span class="va">media</span> <span class="op">-</span> <span class="va">t_critico</span> <span class="op">*</span> <span class="va">errore_standard</span>,</span>
<span>    limite_superiore <span class="op">=</span></span>
<span>      <span class="va">media</span> <span class="op">+</span> <span class="va">t_critico</span> <span class="op">*</span> <span class="va">errore_standard</span>,</span>
<span>    ampiezza <span class="op">=</span></span>
<span>      <span class="fl">2</span> <span class="op">*</span> <span class="va">t_critico</span> <span class="op">*</span> <span class="va">errore_standard</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["livello"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["t_critico"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["limite_inferiore"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["limite_superiore"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["ampiezza"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"0.80","2":"1.32","3":"22.0","4":"25.6","5":"3.55"},{"1":"0.90","2":"1.71","3":"21.5","4":"26.1","5":"4.61"},{"1":"0.95","2":"2.06","3":"21.0","4":"26.6","5":"5.57"},{"1":"0.99","2":"2.80","3":"20.0","4":"27.6","5":"7.54"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Una copertura nominale più elevata viene dunque ottenuta al prezzo di un intervallo più largo. Il compromesso è inevitabile: per aumentare la frequenza con cui la procedura contiene il parametro, occorre accettare una minore precisione intervallare.</p>
</section><section id="dimensione-campionaria" class="level3" data-number="3.8.3"><h3 data-number="3.8.3" class="anchored" data-anchor-id="dimensione-campionaria">
<span class="header-section-number">3.8.3</span> Dimensione campionaria</h3>
<p>Nel caso elementare della media indipendente,</p>
<p><span class="math display">\[
\operatorname{SE}(\bar X)
=
\frac{\sigma}{\sqrt n}.
\]</span></p>
<p>A parità di variabilità e di metodo, quadruplicare <span class="math inline">\(n\)</span> dimezza l’errore standard. Ottenere intervalli sensibilmente più stretti richiede quindi aumenti sostanziali della numerosità campionaria.</p>
<p>L’aumento di <span class="math inline">\(n\)</span> riduce la variabilità campionaria, ma non corregge automaticamente un campionamento distorto, una misurazione inadeguata, una dipendenza ignorata o un modello mal specificato. Una grande quantità di dati può rendere molto precisa una conclusione che rimane sistematicamente errata.</p>
</section></section><section id="sec-freq-ci-assumptions" class="level2" data-number="3.9"><h2 data-number="3.9" class="anchored" data-anchor-id="sec-freq-ci-assumptions">
<span class="header-section-number">3.9</span> Intervalli e validità del modello</h2>
<p>La copertura non è una proprietà autonoma dei due estremi numerici. Dipende dall’intero procedimento che ha condotto alla costruzione dell’intervallo: dalla definizione della popolazione e dal disegno di campionamento o di assegnazione, dallo stimatore utilizzato, dalla formula dell’errore standard, dalla distribuzione di riferimento e dal modo in cui vengono trattate dipendenza, eterogeneità e osservazioni estreme.</p>
<p>Nel semplice intervallo <em>t</em> per una media, per esempio, l’indipendenza svolge un ruolo essenziale. Se i dati provengono da studenti raggruppati nelle stesse classi o da misure ripetute sulle medesime persone, la formula <span class="math inline">\(s/\sqrt n\)</span> può trattare come indipendente informazione che in realtà condivide fonti di variabilità. L’errore standard risulta allora sottostimato e la copertura effettiva può scendere al di sotto di quella nominale.</p>
<p>La valutazione dell’intervallo richiede quindi di considerare non soltanto il calcolo, ma anche il processo che ha generato i dati e la relazione tra il parametro statistico e la domanda scientifica.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Un intervallo ben calcolato può rispondere alla domanda sbagliata">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Avviso</span>Un intervallo ben calcolato può rispondere alla domanda sbagliata
</div>
</div>
<div class="callout-body-container callout-body">
<p>La copertura riguarda il parametro definito dal modello e dal processo di campionamento. Non garantisce che quel parametro corrisponda al costrutto psicologico che interessa realmente.</p>
<p>Precisione statistica e validità sostantiva devono essere valutate separatamente.</p>
</div>
</div>
</section><section id="sec-freq-ci-vs-credible" class="level2" data-number="3.10"><h2 data-number="3.10" class="anchored" data-anchor-id="sec-freq-ci-vs-credible">
<span class="header-section-number">3.10</span> Intervalli di confidenza e intervalli di credibilità</h2>
<p>Gli intervalli di confidenza e gli intervalli di credibilità possono talvolta produrre estremi numericamente simili. Questa somiglianza non deve però nascondere la differenza tra le loro costruzioni probabilistiche.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th>Aspetto</th>
<th>Intervallo di confidenza</th>
<th>Intervallo di credibilità</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Oggetto probabilistico immediato</td>
<td>Intervallo casuale sotto campionamenti ripetuti</td>
<td>Parametro sotto la distribuzione a posteriori</td>
</tr>
<tr class="even">
<td>Significato del 95%</td>
<td>Copertura della procedura, sotto le assunzioni</td>
<td>Massa a posteriori contenuta nell’intervallo</td>
</tr>
<tr class="odd">
<td>Dipendenza da una prior</td>
<td>Non nella procedura standard</td>
<td>Sì</td>
</tr>
<tr class="even">
<td>Dipendenza dal modello dei dati</td>
<td>Sì</td>
<td>Sì</td>
</tr>
<tr class="odd">
<td>Interpretazione del singolo intervallo</td>
<td>Non assegna probabilità al parametro</td>
<td>Assegna probabilità a posteriori al parametro, condizionatamente a prior, modello e dati</td>
</tr>
</tbody>
</table>
<p>Un intervallo di credibilità al 95% contiene il 95% della massa di una distribuzione a posteriori scelta. La sua interpretazione riguarda direttamente il parametro, ma rimane condizionata alla distribuzione a priori, alla verosimiglianza e all’adeguatezza del modello.</p>
<p>Un intervallo di confidenza, invece, conserva il proprio significato procedurale. Il 95% descrive la frequenza di copertura nelle ripetizioni specificate e non la probabilità che il parametro appartenga al particolare intervallo osservato.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Non basta cambiare il nome">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Non basta cambiare il nome
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un intervallo di confidenza non diventa un intervallo di credibilità perché viene interpretato in modo intuitivo. Allo stesso modo, un intervallo bayesiano non è automaticamente affidabile soltanto perché consente un’affermazione probabilistica sul parametro.</p>
<p>Entrambi richiedono un modello adeguato e una comunicazione coerente con la procedura che li ha generati.</p>
</div>
</div>
</section><section id="sec-freq-ci-to-hypothesis-testing" class="level2" data-number="3.11"><h2 data-number="3.11" class="anchored" data-anchor-id="sec-freq-ci-to-hypothesis-testing">
<span class="header-section-number">3.11</span> Dall’intervallo al test di ipotesi</h2>
<p>Per molte procedure standard, un intervallo bilaterale al livello <span class="math inline">\(1-\alpha\)</span> è collegato al corrispondente test bilaterale di livello <span class="math inline">\(\alpha\)</span>.</p>
<p>Nel caso della media con test <em>t</em>, se il valore ipotizzato <span class="math inline">\(\mu_0\)</span> si trova al di fuori dell’intervallo al 95%, il test bilaterale di livello 0.05 rifiuta l’ipotesi <span class="math inline">\(H_0:\mu=\mu_0\)</span>. Se invece <span class="math inline">\(\mu_0\)</span> appartiene all’intervallo, il test non rifiuta l’ipotesi nulla allo stesso livello.</p>
<p>Questa corrispondenza esprime una relazione tra procedure costruite in modo coerente. Non implica che i valori interni all’intervallo siano veri, che quelli esterni siano impossibili o che tutti i valori non esclusi ricevano lo stesso sostegno dai dati.</p>
<p>Il capitolo successivo svilupperà questa logica introducendo l’ipotesi nulla e l’ipotesi alternativa, la statistica test, il livello <span class="math inline">\(\alpha\)</span>, il valore-<span class="math inline">\(p\)</span>, gli errori di tipo I e di tipo II e la potenza statistica.</p>
</section><section id="riflessioni-conclusive" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="riflessioni-conclusive">Riflessioni conclusive</h2>
<p>Un intervallo di confidenza collega una stima puntuale alla distribuzione campionaria dello stimatore. Il suo livello descrive la frequenza con cui la procedura contiene il parametro nelle ripetizioni definite dal modello e dal disegno.</p>
<p>La distinzione fondamentale riguarda l’oggetto della probabilità. Nel quadro frequentista, la probabilità descrive il comportamento della procedura casuale prima dell’osservazione dei dati. Non viene assegnata direttamente al parametro fisso dopo che il particolare intervallo è stato calcolato.</p>
<p>L’ampiezza dell’intervallo informa sulla precisione campionaria, ma non certifica la rappresentatività del campione, la validità della misura o la correttezza del modello. Anche la copertura nominale rimane affidabile soltanto nella misura in cui la procedura e le sue assunzioni risultano adeguate al processo che ha generato i dati.</p>
<p>Questo capitolo completa il passaggio dalla stima puntuale all’inferenza intervallare. Il prossimo utilizzerà le stesse distribuzioni di riferimento per introdurre i test di ipotesi e chiarire il significato dei valori-<span class="math inline">\(p\)</span> e degli errori decisionali.</p>
</section><section id="esercizi" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="esercizi">Esercizi</h2>
<ol type="1">
<li><p>Che cosa aggiunge un intervallo di confidenza rispetto a una stima puntuale?</p></li>
<li><p>Che cosa significa affermare che una procedura ha copertura del 95%?</p></li>
<li><p>Perché non è corretto dire che il parametro ha il 95% di probabilità di trovarsi nell’intervallo osservato?</p></li>
<li><p>Due studi riportano la stessa stima e lo stesso livello di confidenza. Il primo intervallo è molto più stretto. Che cosa puoi concludere e che cosa non puoi concludere?</p></li>
<li><p>Perché quadruplicare la dimensione campionaria dimezza approssimativamente l’errore standard della media?</p></li>
<li><p>Un intervallo al 99% è più ampio dell’intervallo al 95% costruito sugli stessi dati. Quale compromesso esprime questa differenza?</p></li>
<li><p>Perché ignorare la dipendenza tra osservazioni può compromettere la copertura?</p></li>
<li><p>Qual è la differenza fondamentale tra il 95% di un intervallo di confidenza e il 95% di un intervallo di credibilità?</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzioni">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Soluzioni
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>L’intervallo aggiunge informazione sulla precisione campionaria della procedura, combinando la stima, l’errore standard e un valore critico.</p></li>
<li><p>Significa che, sotto il modello e il piano di campionamento assunti, il 95% degli intervalli costruiti in ripetizioni analoghe contiene il parametro vero.</p></li>
<li><p>Dopo l’osservazione, gli estremi sono fissi e il parametro è trattato come fisso nel modello frequentista. Il 95% qualifica il comportamento della procedura prima dell’osservazione, non una distribuzione di probabilità sul parametro.</p></li>
<li><p>Il primo studio possiede una maggiore precisione campionaria, a parità di metodo e assunzioni. Dai soli estremi non si può concludere che la stima sia più accurata, che il campione sia più rappresentativo o che la misura sia più valida.</p></li>
<li><p>L’errore standard della media è proporzionale a <span class="math inline">\(1/\sqrt n\)</span>. Sostituendo <span class="math inline">\(4n\)</span> a <span class="math inline">\(n\)</span>, si ottiene <span class="math inline">\(1/\sqrt{4n}=1/(2\sqrt n)\)</span>.</p></li>
<li><p>Una copertura nominale più alta richiede un valore critico maggiore e produce quindi un intervallo più ampio. Si guadagna copertura procedurale e si perde precisione.</p></li>
<li><p>La formula standard può trattare come indipendenti osservazioni che condividono fonti di variabilità. L’errore standard può risultare troppo piccolo e la copertura effettiva inferiore a quella nominale.</p></li>
<li><p>Nel primo caso, il 95% descrive la frequenza di copertura della procedura. Nel secondo descrive la massa della distribuzione a posteriori contenuta nell’intervallo, condizionatamente alla prior, al modello e ai dati.</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Punti chiave">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Punti chiave
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Un intervallo di confidenza combina una stima, un errore standard e un valore critico. Il livello di confidenza è una proprietà della procedura e non assegna una probabilità al parametro nel singolo intervallo osservato. L’intervallo <em>t</em> classico possiede copertura esatta sotto indipendenza e normalità, mentre violazioni delle assunzioni possono produrre una copertura effettiva diversa da quella nominale. Un intervallo stretto segnala una maggiore precisione campionaria, ma non garantisce accuratezza, rappresentatività o validità. L’ampiezza cresce con il livello di confidenza e tende a diminuire all’aumentare della dimensione campionaria. Gli intervalli di confidenza e di credibilità possono essere numericamente simili, ma rispondono a costruzioni e interpretazioni differenti. Per molte procedure standard, infine, gli intervalli bilaterali e i corrispondenti test di ipotesi sono legati da una relazione di dualità.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Ambiente di sviluppo">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Ambiente di sviluppo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Le informazioni sull’ambiente R possono essere ottenute con:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.6.1 (2026-06-24)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin23</span></span>
<span><span class="co">#&gt; Running under: macOS Tahoe 26.5.2</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Zagreb</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          </span></span>
<span><span class="co">#&gt;  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         </span></span>
<span><span class="co">#&gt;  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        </span></span>
<span><span class="co">#&gt; [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      </span></span>
<span><span class="co">#&gt; [13] loo_2.10.1            rstan_2.32.7          StanHeaders_2.32.10  </span></span>
<span><span class="co">#&gt; [16] brms_2.23.0           Rcpp_1.1.2            sessioninfo_1.2.4    </span></span>
<span><span class="co">#&gt; [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    </span></span>
<span><span class="co">#&gt; [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          </span></span>
<span><span class="co">#&gt; [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         </span></span>
<span><span class="co">#&gt;  [4] S7_0.2.2              fastmap_1.2.0         tensorA_0.36.2.1     </span></span>
<span><span class="co">#&gt;  [7] digest_0.6.39         timechange_0.4.0      estimability_2.0.0   </span></span>
<span><span class="co">#&gt; [10] lifecycle_1.0.5       magrittr_2.0.5        compiler_4.6.1       </span></span>
<span><span class="co">#&gt; [13] rlang_1.3.0           tools_4.6.1           yaml_2.3.12          </span></span>
<span><span class="co">#&gt; [16] knitr_1.51            labeling_0.4.3        bridgesampling_1.2-1 </span></span>
<span><span class="co">#&gt; [19] htmlwidgets_1.6.4     pkgbuild_1.4.8        curl_7.1.0           </span></span>
<span><span class="co">#&gt; [22] RColorBrewer_1.1-3    abind_1.4-8           purrr_1.2.2          </span></span>
<span><span class="co">#&gt; [25] grid_4.6.1            stats4_4.6.1          xtable_1.8-8         </span></span>
<span><span class="co">#&gt; [28] inline_0.3.21         emmeans_2.0.4         scales_1.4.0         </span></span>
<span><span class="co">#&gt; [31] cli_3.6.6             mvtnorm_1.4-2         rmarkdown_2.31       </span></span>
<span><span class="co">#&gt; [34] generics_0.1.4        otel_0.2.0            RcppParallel_5.1.11-2</span></span>
<span><span class="co">#&gt; [37] cachem_1.1.0          stringr_1.6.0         parallel_4.6.1       </span></span>
<span><span class="co">#&gt; [40] vctrs_0.7.3           V8_8.2.0              Matrix_1.7-6         </span></span>
<span><span class="co">#&gt; [43] jsonlite_2.0.0        arrayhelpers_1.1-2    glue_1.8.1           </span></span>
<span><span class="co">#&gt; [46] codetools_0.2-20      distributional_0.8.1  lubridate_1.9.5      </span></span>
<span><span class="co">#&gt; [49] stringi_1.8.7         gtable_0.3.6          QuickJSR_1.10.0      </span></span>
<span><span class="co">#&gt; [52] pillar_1.11.1         htmltools_0.5.9       Brobdingnag_1.2-9    </span></span>
<span><span class="co">#&gt; [55] R6_2.6.1              textshaping_1.0.5     rprojroot_2.1.1      </span></span>
<span><span class="co">#&gt; [58] evaluate_1.0.5        lattice_0.22-9        backports_1.5.1      </span></span>
<span><span class="co">#&gt; [61] memoise_2.0.1         broom_1.0.13          snakecase_0.11.1     </span></span>
<span><span class="co">#&gt; [64] rstantools_2.6.0      coda_0.19-4.1         gridExtra_2.3.1      </span></span>
<span><span class="co">#&gt; [67] nlme_3.1-170          checkmate_2.3.4       xfun_0.60            </span></span>
<span><span class="co">#&gt; [70] pkgconfig_2.0.3</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</div>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:https?:)?//ccaudek\.github\.io/utet-prob/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/frequentist_inference/02_stime_parametri.html" class="pagination-link" aria-label="Stime, stimatori e parametri">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Stime, stimatori e parametri</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/frequentist_inference/04_test_ipotesi.html" class="pagination-link" aria-label="Test di ipotesi e valore-*p*">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Test di ipotesi e valore-<em>p</em></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Inferenza frequentista in psicologia</strong> — Modulo del progetto UTET a supporto del manuale <em>Inferenza bayesiana in psicologia: Ragionare con l’incertezza</em>.</p>
</div>   
    <div class="nav-footer-center">

<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/utet-frequentista/issues/new" class="toc-action"><i class="bi bi-github"></i>Segnala un problema</a></li></ul></div><div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Preferenze cookie</a></div></div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>