<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Modulo introduttivo sull’inferenza frequentista in psicologia, parte del progetto UTET a supporto del manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<title>4&nbsp; Test di ipotesi e valore-p – Inferenza frequentista in psicologia</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/frequentist_inference/05_sample_size.html" rel="next">
<link href="../../chapters/frequentist_inference/03_conf_interv.html" rel="prev">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bd31b91f9ddb1a75e3744ba9797c8182.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-662b1d839dd28a08d17be9d78b753e45.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bd31b91f9ddb1a75e3744ba9797c8182.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-656e41c40711b9d7156bc514cdbc1101.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-887124665b495401b57de95ea3ab5285.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-656e41c40711b9d7156bc514cdbc1101.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script><script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script><script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"headline",
  "consent_type":"express",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"it"
  });
});
</script><style>html{ scroll-behavior: smooth; }</style>
<link href="../../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../../site_libs/pagedtable-1.1/js/pagedtable.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<meta property="og:title" content="4&nbsp; Test di ipotesi e valore-p – Inferenza frequentista in psicologia">
<meta property="og:description" content="Modulo introduttivo sull’inferenza frequentista in psicologia, parte del progetto UTET a supporto del manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<meta property="og:image" content="https://ccaudek.github.io/utet-frequentista/chapters/frequentist_inference/04_test_ipotesi_files/figure-html/fig-chi-square-p-value-1.png">
<meta property="og:site_name" content="Inferenza frequentista in psicologia">
<meta property="og:image:alt" content="Curva della distribuzione chi-quadrato con una linea verticale sulla statistica osservata e la coda destra evidenziata.">
<meta property="og:image:height" content="1297">
<meta property="og:image:width" content="2100">
<meta name="twitter:title" content="4&nbsp; Test di ipotesi e valore-p – Inferenza frequentista in psicologia">
<meta name="twitter:description" content="Modulo introduttivo sull’inferenza frequentista in psicologia, parte del progetto UTET a supporto del manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<meta name="twitter:image" content="https://ccaudek.github.io/utet-frequentista/chapters/frequentist_inference/04_test_ipotesi_files/figure-html/fig-chi-square-p-value-1.png">
<meta name="twitter:image:alt" content="Curva della distribuzione chi-quadrato con una linea verticale sulla statistica osservata e la coda destra evidenziata.">
<meta name="twitter:image-height" content="1297">
<meta name="twitter:image-width" content="2100">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://ccaudek.github.io/utet-frequentista/chapters/frequentist_inference/04_test_ipotesi.html">
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/frequentist_inference/introduction_frequentist_inference.html">Frequentismo</a></li><li class="breadcrumb-item"><a href="../../chapters/frequentist_inference/04_test_ipotesi.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Test di ipotesi e valore-<em>p</em></span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Inferenza frequentista in psicologia</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://ccaudek.github.io/utet-companion/" title="Manuale e companion" class="quarto-navigation-tool px-1" aria-label="Manuale e companion"><i class="bi bi-book"></i></a>
    <a href="https://github.com/ccaudek/utet-frequentista/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Attiva/disattiva la modalità oscura"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
    <div id="quarto-search" class="quarto-navigation-tool px-1" title="Ricerca"></div>
</div>
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Come usare il modulo</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Frequentismo</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/introduction_frequentist_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione all’inferenza frequentista in un percorso bayesiano</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/01_galton.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Origini storiche dell’approccio frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/02_stime_parametri.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Stime, stimatori e parametri</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/03_conf_interv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Intervalli di confidenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/04_test_ipotesi.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Test di ipotesi e valore-<em>p</em></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/05_sample_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Dimensione campionaria, precisione e potenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/06_two_ind_samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Confrontare due gruppi indipendenti</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Epilogo</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epilogo/epilogo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conclusioni</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2"><h2 id="toc-title">Sommario</h2>
   
  <ul class="collapse">
<li><a href="#perch%C3%A9-%C3%A8-facile-fraintendere-un-test" id="toc-perché-è-facile-fraintendere-un-test" class="nav-link active" data-scroll-target="#perch%C3%A9-%C3%A8-facile-fraintendere-un-test"><span class="header-section-number">4.1</span> Perché è facile fraintendere un test?</a></li>
  <li><a href="#sec-freq-two-testing-traditions" id="toc-sec-freq-two-testing-traditions" class="nav-link" data-scroll-target="#sec-freq-two-testing-traditions"><span class="header-section-number">4.2</span> Due tradizioni nella pratica contemporanea</a></li>
  <li><a href="#sec-freq-test-anatomy" id="toc-sec-freq-test-anatomy" class="nav-link" data-scroll-target="#sec-freq-test-anatomy"><span class="header-section-number">4.3</span> Anatomia di un test</a></li>
  <li><a href="#sec-freq-p-value" id="toc-sec-freq-p-value" class="nav-link" data-scroll-target="#sec-freq-p-value"><span class="header-section-number">4.4</span> Il valore-<em>p</em></a></li>
  <li><a href="#sec-freq-errors-power" id="toc-sec-freq-errors-power" class="nav-link" data-scroll-target="#sec-freq-errors-power"><span class="header-section-number">4.5</span> Errori di tipo I, errori di tipo II e potenza</a></li>
  <li><a href="#sec-freq-chi-square-example" id="toc-sec-freq-chi-square-example" class="nav-link" data-scroll-target="#sec-freq-chi-square-example"><span class="header-section-number">4.6</span> Esempio 1: test del chi-quadrato di indipendenza</a></li>
  <li><a href="#sec-freq-one-sample-t-test" id="toc-sec-freq-one-sample-t-test" class="nav-link" data-scroll-target="#sec-freq-one-sample-t-test"><span class="header-section-number">4.7</span> Esempio 2: test <em>t</em> per una media</a></li>
  <li><a href="#sec-freq-one-two-sided" id="toc-sec-freq-one-two-sided" class="nav-link" data-scroll-target="#sec-freq-one-two-sided"><span class="header-section-number">4.8</span> Test unilaterali e bilaterali</a></li>
  <li><a href="#sec-freq-interpreting-test-result" id="toc-sec-freq-interpreting-test-result" class="nav-link" data-scroll-target="#sec-freq-interpreting-test-result"><span class="header-section-number">4.9</span> Interpretare un risultato</a></li>
  <li><a href="#sec-freq-testing-limits" id="toc-sec-freq-testing-limits" class="nav-link" data-scroll-target="#sec-freq-testing-limits"><span class="header-section-number">4.10</span> Limiti e usi appropriati</a></li>
  <li><a href="#sec-freq-testing-bayes" id="toc-sec-freq-testing-bayes" class="nav-link" data-scroll-target="#sec-freq-testing-bayes"><span class="header-section-number">4.11</span> Confronto con l’inferenza bayesiana</a></li>
  <li><a href="#sec-freq-testing-to-sample-size" id="toc-sec-freq-testing-to-sample-size" class="nav-link" data-scroll-target="#sec-freq-testing-to-sample-size"><span class="header-section-number">4.12</span> Verso la pianificazione dello studio</a></li>
  </ul><div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/utet-frequentista/issues/new" class="toc-action"><i class="bi bi-github"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/frequentist_inference/introduction_frequentist_inference.html">Frequentismo</a></li><li class="breadcrumb-item"><a href="../../chapters/frequentist_inference/04_test_ipotesi.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Test di ipotesi e valore-<em>p</em></span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-freq-hypothesis-testing" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Test di ipotesi e valore-<em>p</em></span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-default callout-note callout-titled" title="In sintesi">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>In sintesi
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Da sapere</strong> Un test frequentista confronta una statistica osservata con la distribuzione che essa avrebbe sotto un’ipotesi nulla e un insieme di assunzioni. Il valore-<em>p</em> descrive quanto il risultato sia incompatibile con quel modello di riferimento, ma non assegna una probabilità all’ipotesi. La pratica contemporanea combina spesso la concezione fisheriana della significatività con la teoria delle decisioni e degli errori sviluppata da Neyman e Pearson.</p>
<p><strong>Da saper fare</strong> Al termine del capitolo, il lettore dovrebbe saper distinguere ipotesi, statistica test, distribuzione nulla, valore-<em>p</em> e livello <span class="math inline">\(\alpha\)</span>; interpretare correttamente gli errori di tipo I e di tipo II e la potenza; separare la significatività statistica dalla dimensione dell’effetto e dalla sua rilevanza sostantiva.</p>
</div>
</div>
<section id="introduzione" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="introduzione">Introduzione</h2>
<p>Nei capitoli precedenti abbiamo seguito un percorso che dalla stima puntuale conduce alla quantificazione della sua incertezza:</p>
<p><span class="math display">\[
\text{stima puntuale}
\longrightarrow
\text{errore standard}
\longrightarrow
\text{intervallo di confidenza}.
\]</span></p>
<p>Il test di ipotesi utilizza gli stessi elementi, ma li organizza attorno a una domanda differente:</p>
<blockquote class="blockquote">
<p>Quanto è incompatibile il risultato osservato con un modello assunto come riferimento?</p>
</blockquote>
<p>Nella ricerca psicologica, questa domanda compare ogni volta che si confrontano gruppi, si studiano associazioni tra variabili, si valutano gli effetti di un intervento o si esamina lo scostamento da un valore teorico o normativo. La diffusione dei test rende quindi indispensabile comprenderne non soltanto il calcolo, ma anche la logica e i limiti interpretativi.</p>
<p>Un test frequentista standard non determina la probabilità che un’ipotesi sia vera dopo avere osservato i dati. Costruisce invece la distribuzione dei risultati che sarebbero possibili sotto un’ipotesi nulla e colloca al suo interno il risultato effettivamente osservato. Il significato dell’analisi dipende da questa direzione del ragionamento.</p>
</section><section id="perché-è-facile-fraintendere-un-test" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="perché-è-facile-fraintendere-un-test">
<span class="header-section-number">4.1</span> Perché è facile fraintendere un test?</h2>
<p>Nel linguaggio ordinario, verificare un’ipotesi sembra significare scegliere direttamente tra due spiegazioni: l’ipotesi nulla oppure l’ipotesi alternativa. La procedura frequentista standard non attribuisce però probabilità posteriori a queste possibilità. La domanda che formula è condizionale:</p>
<blockquote class="blockquote">
<p>Se l’ipotesi nulla e le altre assunzioni del modello fossero appropriate, quanto sarebbe estremo il risultato osservato?</p>
</blockquote>
<p>La differenza tra questa domanda e quella che spesso vorremmo porre può essere espressa distinguendo</p>
<p><span class="math display">\[
P(\text{dati}\mid H_0)
\]</span></p>
<p>da</p>
<p><span class="math display">\[
P(H_0\mid\text{dati}).
\]</span></p>
<p>La prima quantità riguarda la distribuzione dei dati sotto l’ipotesi nulla. La seconda riguarda la probabilità dell’ipotesi dopo avere osservato i dati. Confondere le due direzioni del condizionamento costituisce una delle principali fonti di errore nell’interpretazione dei test.</p>
<div class="callout callout-style-default callout-important callout-titled" title="La direzione del condizionamento">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>La direzione del condizionamento
</div>
</div>
<div class="callout-body-container callout-body">
<p>Il valore-<em>p</em> riguarda la distribuzione dei dati, o della statistica test, <strong>assumendo <span class="math inline">\(H_0\)</span></strong>. Non rappresenta la probabilità di <span class="math inline">\(H_0\)</span> dopo avere osservato i dati.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Prerequisiti">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Prerequisiti
</div>
</div>
<div class="callout-body-container callout-body">
<p>Per seguire il capitolo è utile avere letto <a href="02_stime_parametri.html" class="quarto-xref"><span>Capitolo 2</span></a>, dove sono stati introdotti stimatore, distribuzione campionaria ed errore standard, e <a href="03_conf_interv.html" class="quarto-xref"><span>Capitolo 3</span></a>, dedicato a copertura, valori critici e livello <span class="math inline">\(\alpha\)</span>. Il capitolo <a href="https://ccaudek.github.io/utet-prob/chapters/probability/04_conditional_prob_bayesian.html">Probabilità condizionata</a> aiuta inoltre a distinguere <span class="math inline">\(P(A\mid B)\)</span> da <span class="math inline">\(P(B\mid A)\)</span>.</p>
<p>La potenza verrà introdotta qui come proprietà del test e approfondita nel capitolo successivo, dedicato alla pianificazione della numerosità campionaria.</p>
</div>
</div>
</section><section id="panoramica-del-capitolo" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="panoramica-del-capitolo">Panoramica del capitolo</h2>
<p>Il capitolo parte dalla distinzione tra la significatività fisheriana e la teoria dei test di Neyman–Pearson. Verranno quindi identificati gli elementi che definiscono una procedura di test e chiarito il diverso ruolo del valore-<em>p</em> e del livello <span class="math inline">\(\alpha\)</span>. Su questa base sarà possibile introdurre gli errori di tipo I e di tipo II e la potenza statistica.</p>
<p>La logica generale verrà applicata prima a un test del chi-quadrato e poi a un test <em>t</em> per una media. La discussione dei test unilaterali e bilaterali permetterà di mostrare come la definizione dell’estremità dipenda dalla domanda formulata prima dell’analisi. L’ultima parte distinguerà significatività, grandezza dell’effetto e rilevanza sostantiva e metterà a confronto la domanda frequentista con quella bayesiana.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Preparazione del notebook">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Preparazione del notebook
</div>
</div>
<div class="callout-body-container callout-body">
<p>Per eseguire gli esempi, prepara l’ambiente comune del progetto:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</section><section id="sec-freq-two-testing-traditions" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="sec-freq-two-testing-traditions">
<span class="header-section-number">4.2</span> Due tradizioni nella pratica contemporanea</h2>
<p>La pratica comunemente indicata come <em>NHST</em>, acronimo di <em>Null Hypothesis Significance Testing</em>, non coincide perfettamente con una singola teoria. Essa combina elementi provenienti da due tradizioni storicamente e concettualmente distinte.</p>
<section id="fisher-significatività-e-incompatibilità" class="level3" data-number="4.2.1"><h3 data-number="4.2.1" class="anchored" data-anchor-id="fisher-significatività-e-incompatibilità">
<span class="header-section-number">4.2.1</span> Fisher: significatività e incompatibilità</h3>
<p>Nell’impostazione fisheriana, il valore-<em>p</em> fornisce una misura graduata dell’incompatibilità tra i dati e un’ipotesi nulla. Un valore piccolo indica che il risultato osservato si trova in una regione poco frequente della distribuzione prevista sotto quell’ipotesi.</p>
<p>Questa lettura non richiede necessariamente una decisione automatica e definitiva. Il valore-<em>p</em> viene considerato insieme alla qualità del disegno, all’affidabilità delle misure, alle caratteristiche dei dati e alle conoscenze scientifiche disponibili. Esso rappresenta quindi un elemento dell’argomentazione, non un verdetto autosufficiente.</p>
</section><section id="neymanpearson-decisioni-ed-errori" class="level3" data-number="4.2.2"><h3 data-number="4.2.2" class="anchored" data-anchor-id="neymanpearson-decisioni-ed-errori">
<span class="header-section-number">4.2.2</span> Neyman–Pearson: decisioni ed errori</h3>
<p>Nella teoria di Neyman e Pearson, l’attenzione si sposta verso il comportamento di una regola decisionale nelle ripetizioni. Vengono specificate le ipotesi, la regione di rifiuto e le probabilità di commettere errori quando si applica la procedura. Il livello <span class="math inline">\(\alpha\)</span> controlla l’errore di tipo I, mentre l’errore di tipo II e la potenza descrivono il comportamento del test sotto alternative specificate.</p>
<p>La decisione di rifiutare o non rifiutare l’ipotesi nulla non dichiara che una delle ipotesi sia probabilmente vera. Applica una regola progettata per produrre determinate frequenze di errore nel lungo periodo.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Una procedura ibrida">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Una procedura ibrida
</div>
</div>
<div class="callout-body-container callout-body">
<p>La regola</p>
<blockquote class="blockquote">
<p>«calcolo un valore-<em>p</em> e, se <span class="math inline">\(p\leq0.05\)</span>, dichiaro il risultato significativo»</p>
</blockquote>
<p>combina una misura fisheriana di incompatibilità con una soglia e una decisione di tipo Neyman–Pearson. Questa pratica è molto diffusa, ma può essere interpretata correttamente soltanto ricordando che il valore-<em>p</em> e il livello <span class="math inline">\(\alpha\)</span> sono quantità diverse e svolgono funzioni differenti.</p>
</div>
</div>
</section></section><section id="sec-freq-test-anatomy" class="level2" data-number="4.3"><h2 data-number="4.3" class="anchored" data-anchor-id="sec-freq-test-anatomy">
<span class="header-section-number">4.3</span> Anatomia di un test</h2>
<p>Un test non è definito dal solo valore-<em>p</em>. Per comprenderne il significato occorre ricostruire l’intera procedura: l’ipotesi nulla, l’alternativa, la statistica test, la distribuzione di riferimento e la regola che stabilisce quali risultati siano almeno altrettanto estremi di quello osservato.</p>
<section id="ipotesi-nulla-e-alternativa" class="level3" data-number="4.3.1"><h3 data-number="4.3.1" class="anchored" data-anchor-id="ipotesi-nulla-e-alternativa">
<span class="header-section-number">4.3.1</span> Ipotesi nulla e alternativa</h3>
<p>L’<strong>ipotesi nulla</strong> <span class="math inline">\(H_0\)</span> specifica il modello di riferimento. L’<strong>ipotesi alternativa</strong> <span class="math inline">\(H_1\)</span> descrive invece i valori o i modelli rispetto ai quali la procedura deve essere sensibile.</p>
<p>Nel caso di una media, l’ipotesi nulla può essere</p>
<p><span class="math display">\[
H_0:\mu=24.
\]</span></p>
<p>Un’alternativa bilaterale è</p>
<p><span class="math display">\[
H_1:\mu\neq24,
\]</span></p>
<p>mentre un’alternativa unilaterale superiore può essere espressa come</p>
<p><span class="math display">\[
H_1:\mu&gt;24.
\]</span></p>
<p>L’ipotesi nulla non deve necessariamente rappresentare una teoria scientifica completa, né coincide sempre con l’assenza di qualunque effetto. È una restrizione precisa del modello che consente di derivare una distribuzione di riferimento per la statistica test.</p>
</section><section id="statistica-test" class="level3" data-number="4.3.2"><h3 data-number="4.3.2" class="anchored" data-anchor-id="statistica-test">
<span class="header-section-number">4.3.2</span> Statistica test</h3>
<p>La <strong>statistica test</strong> è una funzione dei dati costruita per quantificare una discrepanza rilevante rispetto a <span class="math inline">\(H_0\)</span>. Può assumere la forma di una statistica <span class="math inline">\(z\)</span>, <span class="math inline">\(t\)</span>, <span class="math inline">\(\chi^2\)</span> o <span class="math inline">\(F\)</span>, oppure di una differenza, un rapporto o un coefficiente standardizzato.</p>
<p>Il suo valore non è interpretabile isolatamente. Per stabilire quanto sia estremo occorre conoscere la distribuzione che la statistica avrebbe sotto l’ipotesi nulla e sapere quali direzioni o valori rappresentino una maggiore incompatibilità con il modello di riferimento.</p>
</section><section id="distribuzione-sotto-lipotesi-nulla" class="level3" data-number="4.3.3"><h3 data-number="4.3.3" class="anchored" data-anchor-id="distribuzione-sotto-lipotesi-nulla">
<span class="header-section-number">4.3.3</span> Distribuzione sotto l’ipotesi nulla</h3>
<p>La <strong>distribuzione nulla</strong> descrive i valori che la statistica test assumerebbe se l’ipotesi nulla, il modello e il piano di analisi fossero corretti. A seconda del problema, questa distribuzione può essere derivata esattamente, approssimata mediante risultati asintotici oppure costruita attraverso permutazioni o simulazioni.</p>
<p>Essa traduce l’ipotesi nulla in una previsione sul comportamento della statistica. Soltanto grazie a questa distribuzione è possibile valutare la posizione del risultato osservato.</p>
</section><section id="regola-di-estremità" class="level3" data-number="4.3.4"><h3 data-number="4.3.4" class="anchored" data-anchor-id="regola-di-estremità">
<span class="header-section-number">4.3.4</span> Regola di estremità</h3>
<p>Il valore-<em>p</em> dipende anche dalla regola che definisce quali risultati siano almeno altrettanto incompatibili con <span class="math inline">\(H_0\)</span> quanto quello osservato. In un test unilaterale superiore si considera una sola coda della distribuzione; in un test bilaterale si considerano discrepanze in entrambe le direzioni, secondo la procedura stabilita.</p>
<p>La nozione di risultato estremo non è quindi contenuta nei dati in modo automatico. Dipende dalla domanda, dalla statistica scelta e dal piano di analisi.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Il valore-p non è determinato dai soli dati">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Avviso</span>Il valore-p non è determinato dai soli dati
</div>
</div>
<div class="callout-body-container callout-body">
<p>A parità di dati, il valore-<em>p</em> può cambiare quando cambiano l’ipotesi nulla, la statistica test, la distribuzione di riferimento, la scelta tra test unilaterale e bilaterale, la regola di arresto, le correzioni per confronti multipli o altre decisioni previste dal piano di analisi.</p>
</div>
</div>
</section></section><section id="sec-freq-p-value" class="level2" data-number="4.4"><h2 data-number="4.4" class="anchored" data-anchor-id="sec-freq-p-value">
<span class="header-section-number">4.4</span> Il valore-<em>p</em>
</h2>
<p>In forma generale, il valore-<em>p</em> può essere definito come</p>
<blockquote class="blockquote">
<p>la probabilità, calcolata sotto <span class="math inline">\(H_0\)</span>, di ottenere un valore della statistica test almeno altrettanto incompatibile con <span class="math inline">\(H_0\)</span> quanto quello osservato.</p>
</blockquote>
<p>In simboli schematici,</p>
<p><span class="math display">\[
p
=
P_{H_0}
\left(
T(Y)\text{ almeno altrettanto estremo di }T(y_{\mathrm{obs}})
\right).
\]</span></p>
<p>Un valore-<em>p</em> piccolo indica che il risultato osservato occupa una regione rara della distribuzione nulla. Esprime quindi una tensione tra i dati e l’insieme delle assunzioni utilizzate per costruire il test.</p>
<p>Questa tensione non identifica automaticamente quale componente sia problematica. Un valore piccolo può derivare da una deviazione reale rispetto al valore nullo, ma anche da una specificazione inadeguata del modello, da dipendenze o forme di eterogeneità ignorate, da distorsioni del campionamento o della misurazione oppure da una selezione analitica e da confronti multipli non adeguatamente considerati.</p>
<section id="valore-p-e-livello-alpha" class="level3" data-number="4.4.1"><h3 data-number="4.4.1" class="anchored" data-anchor-id="valore-p-e-livello-alpha">
<span class="header-section-number">4.4.1</span> Valore-<em>p</em> e livello <span class="math inline">\(\alpha\)</span>
</h3>
<p>Il <strong>valore-<em>p</em></strong> viene calcolato a partire dai dati. Il <strong>livello <span class="math inline">\(\alpha\)</span></strong> è invece una soglia decisionale stabilita prima dell’analisi.</p>
<p>La regola convenzionale prevede di rifiutare <span class="math inline">\(H_0\)</span> quando <span class="math inline">\(p\leq\alpha\)</span> e di non rifiutarla quando <span class="math inline">\(p&gt;\alpha\)</span>. L’espressione <em>non rifiutare</em> è intenzionale: un risultato non significativo non dimostra che l’ipotesi nulla sia vera.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Che cosa non è un valore-p">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Avviso</span>Che cosa non è un valore-p
</div>
</div>
<div class="callout-body-container callout-body">
<p>Il valore-<em>p</em> non è <span class="math inline">\(P(H_0\mid\text{dati})\)</span>, non rappresenta la probabilità che il risultato sia «dovuto al caso» e non esprime la probabilità che <span class="math inline">\(H_1\)</span> sia vera. Non misura la dimensione dell’effetto, non indica la probabilità di replicare la significatività e non coincide con il tasso di falsi positivi tra tutti i risultati significativi pubblicati.</p>
</div>
</div>
</section></section><section id="sec-freq-errors-power" class="level2" data-number="4.5"><h2 data-number="4.5" class="anchored" data-anchor-id="sec-freq-errors-power">
<span class="header-section-number">4.5</span> Errori di tipo I, errori di tipo II e potenza</h2>
<p>Quando un test viene utilizzato come regola decisionale, il suo risultato può essere classificato in relazione allo stato specificato dalle ipotesi:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead><tr class="header">
<th>Stato rispetto alle ipotesi specificate</th>
<th style="text-align: right;">Rifiutare <span class="math inline">\(H_0\)</span>
</th>
<th style="text-align: right;">Non rifiutare <span class="math inline">\(H_0\)</span>
</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>
<span class="math inline">\(H_0\)</span> vera</td>
<td style="text-align: right;">Errore di tipo I</td>
<td style="text-align: right;">Decisione corretta</td>
</tr>
<tr class="even">
<td>Alternativa specificata vera</td>
<td style="text-align: right;">Decisione corretta</td>
<td style="text-align: right;">Errore di tipo II</td>
</tr>
</tbody>
</table>
<section id="errore-di-tipo-i" class="level3" data-number="4.5.1"><h3 data-number="4.5.1" class="anchored" data-anchor-id="errore-di-tipo-i">
<span class="header-section-number">4.5.1</span> Errore di tipo I</h3>
<p>L’errore di tipo I consiste nel rifiutare <span class="math inline">\(H_0\)</span> quando essa è vera. Sotto le condizioni previste dalla procedura,</p>
<p><span class="math display">\[
P(\text{rifiutare }H_0\mid H_0)=\alpha.
\]</span></p>
<p>Il controllo riguarda la procedura e la famiglia di analisi effettivamente definita. Se vengono eseguiti numerosi test e riportati soltanto quelli significativi, oppure se le analisi vengono modificate dopo avere osservato i risultati, il tasso effettivo di falsi positivi può superare il livello nominale.</p>
</section><section id="errore-di-tipo-ii-e-potenza" class="level3" data-number="4.5.2"><h3 data-number="4.5.2" class="anchored" data-anchor-id="errore-di-tipo-ii-e-potenza">
<span class="header-section-number">4.5.2</span> Errore di tipo II e potenza</h3>
<p>Per una specifica alternativa, la probabilità di errore di tipo II è</p>
<p><span class="math display">\[
\beta
=
P(\text{non rifiutare }H_0\mid H_1).
\]</span></p>
<p>La <strong>potenza</strong> è il suo complemento:</p>
<p><span class="math display">\[
1-\beta
=
P(\text{rifiutare }H_0\mid H_1).
\]</span></p>
<p>La potenza non è un unico numero valido per qualunque alternativa. Cambia al variare del parametro sotto <span class="math inline">\(H_1\)</span> e dipende anche dalla numerosità campionaria, dalla variabilità, dal livello <span class="math inline">\(\alpha\)</span>, dalla struttura del disegno, dalla scelta tra test unilaterale e bilaterale e dalla qualità della misurazione.</p>
<p>Un effetto molto distante dal valore nullo è generalmente più facile da rilevare di un effetto piccolo. Allo stesso modo, un campione più ampio o una misura più precisa rendono la procedura più sensibile, a parità delle altre condizioni.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Perché la potenza viene ripresa nel prossimo capitolo">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Perché la potenza viene ripresa nel prossimo capitolo
</div>
</div>
<div class="callout-body-container callout-body">
<p>In questo capitolo la potenza serve a completare la logica degli errori decisionali. Nel capitolo successivo verrà utilizzata per discutere come scegliere un effetto bersaglio e una numerosità campionaria adeguata prima della raccolta dei dati.</p>
</div>
</div>
</section></section><section id="sec-freq-chi-square-example" class="level2" data-number="4.6"><h2 data-number="4.6" class="anchored" data-anchor-id="sec-freq-chi-square-example">
<span class="header-section-number">4.6</span> Esempio 1: test del chi-quadrato di indipendenza</h2>
<p>Supponiamo di studiare la relazione tra <strong>stress percepito</strong> e <strong>qualità del sonno</strong>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">osservati</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="fl">42</span>, <span class="fl">40</span>,</span>
<span>    <span class="fl">19</span>, <span class="fl">39</span></span>
<span>  <span class="op">)</span>,</span>
<span>  nrow <span class="op">=</span> <span class="fl">2</span>,</span>
<span>  byrow <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  dimnames <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>    Stress <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Basso"</span>, <span class="st">"Alto"</span><span class="op">)</span>,</span>
<span>    Sonno <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Buono"</span>, <span class="st">"Scarso"</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">osservati</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div id="tbl-stress-sleep-observed" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stress-sleep-observed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabella&nbsp;4.1: Frequenze osservate per stress percepito e qualità del sonno.
</figcaption><div aria-describedby="tbl-stress-sleep-observed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Buono</th>
<th style="text-align: right;">Scarso</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Basso</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alto</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">39</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>L’ipotesi nulla afferma che stress e qualità del sonno siano indipendenti:</p>
<p><span class="math display">\[
H_0:
\text{stress e qualità del sonno sono indipendenti}.
\]</span></p>
<p>L’alternativa sostiene invece che tra le due variabili vi sia un’associazione:</p>
<p><span class="math display">\[
H_1:
\text{stress e qualità del sonno non sono indipendenti}.
\]</span></p>
<section id="frequenze-attese" class="level3" data-number="4.6.1"><h3 data-number="4.6.1" class="anchored" data-anchor-id="frequenze-attese">
<span class="header-section-number">4.6.1</span> Frequenze attese</h3>
<p>Sotto l’ipotesi di indipendenza, la frequenza attesa nella cella <span class="math inline">\(ij\)</span> è</p>
<p><span class="math display">\[
E_{ij}
=
\frac{R_iC_j}{N},
\]</span></p>
<p>dove <span class="math inline">\(R_i\)</span> indica il totale della riga, <span class="math inline">\(C_j\)</span> quello della colonna e <span class="math inline">\(N\)</span> il totale complessivo. Le frequenze attese descrivono quindi la tabella che ci aspetteremmo di osservare, salvo la variabilità campionaria, se la distribuzione di una variabile non dipendesse dall’altra.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">totali_riga</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="va">osservati</span><span class="op">)</span></span>
<span><span class="va">totali_colonna</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span><span class="op">(</span><span class="va">osservati</span><span class="op">)</span></span>
<span><span class="va">totale</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">osservati</span><span class="op">)</span></span>
<span></span>
<span><span class="va">attesi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/outer.html">outer</a></span><span class="op">(</span><span class="va">totali_riga</span>, <span class="va">totali_colonna</span><span class="op">)</span> <span class="op">/</span> <span class="va">totale</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dimnames.html">dimnames</a></span><span class="op">(</span><span class="va">attesi</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/dimnames.html">dimnames</a></span><span class="op">(</span><span class="va">osservati</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">attesi</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div id="tbl-stress-sleep-expected" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stress-sleep-expected-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabella&nbsp;4.2: Frequenze attese sotto l’ipotesi nulla di indipendenza.
</figcaption><div aria-describedby="tbl-stress-sleep-expected-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Buono</th>
<th style="text-align: right;">Scarso</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Basso</td>
<td style="text-align: right;">35.7</td>
<td style="text-align: right;">46.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alto</td>
<td style="text-align: right;">25.3</td>
<td style="text-align: right;">32.7</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section><section id="statistica-test-1" class="level3" data-number="4.6.2"><h3 data-number="4.6.2" class="anchored" data-anchor-id="statistica-test-1">
<span class="header-section-number">4.6.2</span> Statistica test</h3>
<p>La statistica del chi-quadrato confronta sistematicamente frequenze osservate e attese:</p>
<p><span class="math display">\[
\chi^2
=
\sum_{i=1}^{r}
\sum_{j=1}^{c}
\frac{(O_{ij}-E_{ij})^2}{E_{ij}}.
\]</span></p>
<p>Le discrepanze vengono elevate al quadrato, rapportate alle frequenze attese e sommate. Valori più grandi indicano una maggiore distanza dalla configurazione prevista sotto l’indipendenza.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">chi2_osservato</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">osservati</span> <span class="op">-</span> <span class="va">attesi</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="va">attesi</span><span class="op">)</span></span>
<span><span class="va">gradi_liberta</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">osservati</span><span class="op">)</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">ncol</a></span><span class="op">(</span><span class="va">osservati</span><span class="op">)</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">p_chi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq</a></span><span class="op">(</span></span>
<span>  <span class="va">chi2_osservato</span>,</span>
<span>  df <span class="op">=</span> <span class="va">gradi_liberta</span>,</span>
<span>  lower.tail <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  chi_quadrato <span class="op">=</span> <span class="va">chi2_osservato</span>,</span>
<span>  gradi_liberta <span class="op">=</span> <span class="va">gradi_liberta</span>,</span>
<span>  valore_p <span class="op">=</span> <span class="va">p_chi</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt;  chi_quadrato gradi_liberta      valore_p </span></span>
<span><span class="co">#&gt;          4.71          1.00          0.03</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Il calcolo produce approssimativamente</p>
<p><span class="math display">\[
\chi^2(1)=4.71,
\qquad
p=0.030.
\]</span></p>
<p>Possiamo verificare il risultato mediante la funzione disponibile in R:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span><span class="op">(</span><span class="va">osservati</span>, correct <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Pearson's Chi-squared test</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; data:  osservati</span></span>
<span><span class="co">#&gt; X-squared = 5, df = 1, p-value = 0.03</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>La correzione di continuità viene disattivata per riprodurre il calcolo manuale.</p>
</section><section id="visualizzazione" class="level3" data-number="4.6.3"><h3 data-number="4.6.3" class="anchored" data-anchor-id="visualizzazione">
<span class="header-section-number">4.6.3</span> Visualizzazione</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x_massimo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">qchisq</a></span><span class="op">(</span><span class="fl">0.999</span>, df <span class="op">=</span> <span class="va">gradi_liberta</span><span class="op">)</span></span>
<span></span>
<span><span class="va">dati_chi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0.001</span>, <span class="va">x_massimo</span>, length.out <span class="op">=</span> <span class="fl">2000</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">dati_chi</span><span class="op">$</span><span class="va">densita</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">dchisq</a></span><span class="op">(</span><span class="va">dati_chi</span><span class="op">$</span><span class="va">x</span>, df <span class="op">=</span> <span class="va">gradi_liberta</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">dati_chi</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">densita</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_line</span><span class="op">(</span>linewidth <span class="op">=</span> <span class="fl">0.9</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_area</span><span class="op">(</span></span>
<span>    data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">dati_chi</span>, <span class="va">x</span> <span class="op">&gt;=</span> <span class="va">chi2_osservato</span><span class="op">)</span>,</span>
<span>    alpha <span class="op">=</span> <span class="fl">0.35</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_vline</span><span class="op">(</span></span>
<span>    xintercept <span class="op">=</span> <span class="va">chi2_osservato</span>,</span>
<span>    linetype <span class="op">=</span> <span class="st">"dashed"</span>,</span>
<span>    linewidth <span class="op">=</span> <span class="fl">0.8</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="va">chi</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Densità"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-chi-square-p-value" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" alt="Curva della distribuzione chi-quadrato con una linea verticale sulla statistica osservata e la coda destra evidenziata.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-chi-square-p-value-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="04_test_ipotesi_files/figure-html/fig-chi-square-p-value-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figura&nbsp;4.1: Distribuzione chi-quadrato sotto l’ipotesi nulla. L’area oltre la statistica osservata rappresenta il valore-p."><img src="04_test_ipotesi_files/figure-html/fig-chi-square-p-value-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%" alt="Curva della distribuzione chi-quadrato con una linea verticale sulla statistica osservata e la coda destra evidenziata."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chi-square-p-value-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.1: Distribuzione chi-quadrato sotto l’ipotesi nulla. L’area oltre la statistica osservata rappresenta il valore-p.
</figcaption></figure>
</div>
</div>
</div>
<p>In <a href="#fig-chi-square-p-value" class="quarto-xref">Figura&nbsp;<span>4.1</span></a>, l’area a destra di <span class="math inline">\(\chi^2_{\mathrm{obs}}\)</span> è pari a circa 0.030. Se il livello <span class="math inline">\(\alpha\)</span> è stato fissato a 0.05, la procedura conduce al rifiuto dell’ipotesi di indipendenza.</p>
<p>Il risultato può essere comunicato nel modo seguente:</p>
<blockquote class="blockquote">
<p>Nel campione è emersa un’associazione statisticamente significativa tra stress percepito e qualità del sonno, <span class="math inline">\(\chi^2(1)=4.71\)</span>, <span class="math inline">\(p=0.030\)</span>.</p>
</blockquote>
<p>Questa conclusione non fornisce la probabilità che le variabili siano associate, non quantifica la grandezza dell’associazione e non dimostra una relazione causale. Non garantisce neppure che le categorie utilizzate siano valide o che il disegno consenta una generalizzazione appropriata. Per completare l’analisi occorre stimare la dimensione dell’associazione e discuterne il significato sostantivo.</p>
</section></section><section id="sec-freq-one-sample-t-test" class="level2" data-number="4.7"><h2 data-number="4.7" class="anchored" data-anchor-id="sec-freq-one-sample-t-test">
<span class="header-section-number">4.7</span> Esempio 2: test <em>t</em> per una media</h2>
<p>Consideriamo dieci punteggi di benessere psicologico e un valore normativo pari a 24.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">punteggi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">28</span>, <span class="fl">22</span>, <span class="fl">26</span>, <span class="fl">18</span>, <span class="fl">30</span>, <span class="fl">24</span>, <span class="fl">27</span>, <span class="fl">17</span>, <span class="fl">21</span>, <span class="fl">25</span><span class="op">)</span></span>
<span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">punteggi</span><span class="op">)</span></span>
<span><span class="va">media</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">punteggi</span><span class="op">)</span></span>
<span><span class="va">deviazione_standard</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">punteggi</span><span class="op">)</span></span>
<span><span class="va">errore_standard</span> <span class="op">&lt;-</span> <span class="va">deviazione_standard</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  media <span class="op">=</span> <span class="va">media</span>,</span>
<span>  deviazione_standard <span class="op">=</span> <span class="va">deviazione_standard</span>,</span>
<span>  errore_standard <span class="op">=</span> <span class="va">errore_standard</span>,</span>
<span>  n <span class="op">=</span> <span class="va">n</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt;               media deviazione_standard     errore_standard                   n </span></span>
<span><span class="co">#&gt;               23.80                4.26                1.35               10.00</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Supponiamo che, prima di osservare i dati, sia stata formulata l’ipotesi nulla</p>
<p><span class="math display">\[
H_0:\mu=24
\]</span></p>
<p>e che l’alternativa di interesse sia</p>
<p><span class="math display">\[
H_1:\mu&gt;24.
\]</span></p>
<p>La statistica test confronta la distanza tra la media osservata e il valore nullo con l’errore standard stimato:</p>
<p><span class="math display">\[
t
=
\frac{\bar X-\mu_0}{S/\sqrt n}.
\]</span></p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mu_0</span> <span class="op">&lt;-</span> <span class="fl">24</span></span>
<span></span>
<span><span class="va">t_osservato</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">media</span> <span class="op">-</span> <span class="va">mu_0</span><span class="op">)</span> <span class="op">/</span> <span class="va">errore_standard</span></span>
<span><span class="va">gradi_liberta_t</span> <span class="op">&lt;-</span> <span class="va">n</span> <span class="op">-</span> <span class="fl">1</span></span>
<span><span class="va">p_unilaterale</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">pt</a></span><span class="op">(</span></span>
<span>  <span class="va">t_osservato</span>,</span>
<span>  df <span class="op">=</span> <span class="va">gradi_liberta_t</span>,</span>
<span>  lower.tail <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  t <span class="op">=</span> <span class="va">t_osservato</span>,</span>
<span>  gradi_liberta <span class="op">=</span> <span class="va">gradi_liberta_t</span>,</span>
<span>  valore_p <span class="op">=</span> <span class="va">p_unilaterale</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt;             t gradi_liberta      valore_p </span></span>
<span><span class="co">#&gt;        -0.148         9.000         0.557</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Otteniamo approssimativamente</p>
<p><span class="math display">\[
t(9)=-0.15,
\qquad
p=0.557.
\]</span></p>
<p>La media osservata, pari a 23.8, non si trova nella direzione indicata dall’alternativa superiore. La procedura non conduce quindi al rifiuto di <span class="math inline">\(H_0\)</span>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span></span>
<span>  <span class="va">punteggi</span>,</span>
<span>  mu <span class="op">=</span> <span class="fl">24</span>,</span>
<span>  alternative <span class="op">=</span> <span class="st">"greater"</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  One Sample t-test</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; data:  punteggi</span></span>
<span><span class="co">#&gt; t = -0.1, df = 9, p-value = 0.6</span></span>
<span><span class="co">#&gt; alternative hypothesis: true mean is greater than 24</span></span>
<span><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span><span class="co">#&gt;  21.3  Inf</span></span>
<span><span class="co">#&gt; sample estimates:</span></span>
<span><span class="co">#&gt; mean of x </span></span>
<span><span class="co">#&gt;      23.8</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Una formulazione adeguata è:</p>
<blockquote class="blockquote">
<p>I dati non forniscono evidenza, secondo questo test unilaterale, che la media sia superiore a 24, <span class="math inline">\(t(9)=-0.15\)</span>, <span class="math inline">\(p=0.557\)</span>.</p>
</blockquote>
<p>Non sarebbe invece corretto affermare di avere dimostrato che la media sia uguale a 24. Il risultato non significativo lascia aperte possibilità differenti: la differenza potrebbe essere piccola, i dati potrebbero essere poco informativi oppure lo scostamento potrebbe trovarsi nella direzione opposta a quella specificata.</p>
</section><section id="sec-freq-one-two-sided" class="level2" data-number="4.8"><h2 data-number="4.8" class="anchored" data-anchor-id="sec-freq-one-two-sided">
<span class="header-section-number">4.8</span> Test unilaterali e bilaterali</h2>
<p>Un test bilaterale considera deviazioni in entrambe le direzioni:</p>
<p><span class="math display">\[
H_1:\mu\neq\mu_0.
\]</span></p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span></span>
<span>  <span class="va">punteggi</span>,</span>
<span>  mu <span class="op">=</span> <span class="fl">24</span>,</span>
<span>  alternative <span class="op">=</span> <span class="st">"two.sided"</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  One Sample t-test</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; data:  punteggi</span></span>
<span><span class="co">#&gt; t = -0.1, df = 9, p-value = 0.9</span></span>
<span><span class="co">#&gt; alternative hypothesis: true mean is not equal to 24</span></span>
<span><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span><span class="co">#&gt;  20.8 26.8</span></span>
<span><span class="co">#&gt; sample estimates:</span></span>
<span><span class="co">#&gt; mean of x </span></span>
<span><span class="co">#&gt;      23.8</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Per gli stessi dati, il valore-<em>p</em> bilaterale è circa 0.885. La differenza rispetto al valore unilaterale non dipende da un cambiamento dei dati, ma dalla diversa definizione dei risultati considerati estremi.</p>
<p>La scelta tra un test unilaterale e uno bilaterale deve essere motivata dalla domanda scientifica e stabilita prima di osservare i risultati. Se la coda favorevole viene scelta soltanto dopo avere visto la direzione dell’effetto, il controllo nominale dell’errore di tipo I non è più valido.</p>
<p>Un test unilaterale non dovrebbe dunque essere utilizzato semplicemente perché offre maggiore potenza nella direzione prevista. Deve essere scientificamente sensato escludere dalla regola di evidenza una deviazione nella direzione opposta, anche qualora essa risultasse ampia.</p>
</section><section id="sec-freq-interpreting-test-result" class="level2" data-number="4.9"><h2 data-number="4.9" class="anchored" data-anchor-id="sec-freq-interpreting-test-result">
<span class="header-section-number">4.9</span> Interpretare un risultato</h2>
<p>Una lettura completa di un test richiede di mantenere distinti quattro livelli dell’interpretazione.</p>
<section id="compatibilità-con-il-modello-nullo" class="level3" data-number="4.9.1"><h3 data-number="4.9.1" class="anchored" data-anchor-id="compatibilità-con-il-modello-nullo">
<span class="header-section-number">4.9.1</span> Compatibilità con il modello nullo</h3>
<p>Il valore-<em>p</em> descrive quanto il risultato osservato sia estremo sotto <span class="math inline">\(H_0\)</span> e sotto le altre assunzioni necessarie per costruire la distribuzione di riferimento. Esso informa quindi sulla compatibilità tra dati e modello nullo, non sulla probabilità dell’ipotesi.</p>
</section><section id="decisione-procedurale" class="level3" data-number="4.9.2"><h3 data-number="4.9.2" class="anchored" data-anchor-id="decisione-procedurale">
<span class="header-section-number">4.9.2</span> Decisione procedurale</h3>
<p>Il confronto con <span class="math inline">\(\alpha\)</span> applica una regola di rifiuto o di non rifiuto. Questa decisione possiede proprietà di errore definite nelle ripetizioni, ma non coincide con una dichiarazione di verità o falsità dell’ipotesi.</p>
</section><section id="grandezza-e-precisione-delleffetto" class="level3" data-number="4.9.3"><h3 data-number="4.9.3" class="anchored" data-anchor-id="grandezza-e-precisione-delleffetto">
<span class="header-section-number">4.9.3</span> Grandezza e precisione dell’effetto</h3>
<p>La stima e l’intervallo di confidenza mostrano quanto l’effetto sia grande e con quale precisione sia stato stimato. Queste informazioni non sono sostituite dal valore-<em>p</em>: risultati con lo stesso livello di significatività possono corrispondere a effetti e precisioni molto differenti.</p>
</section><section id="significato-scientifico" class="level3" data-number="4.9.4"><h3 data-number="4.9.4" class="anchored" data-anchor-id="significato-scientifico">
<span class="header-section-number">4.9.4</span> Significato scientifico</h3>
<p>La rilevanza del risultato dipende dalla teoria, dalla qualità della misura, dal disegno, dai costi e benefici e dal contesto applicativo. La significatività statistica non stabilisce da sola se una differenza sia importante sul piano psicologico, clinico o sociale.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Significativo non significa importante">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Significativo non significa importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un risultato può essere statisticamente significativo ma troppo piccolo per avere rilievo teorico o pratico. Al contrario, un risultato non significativo può essere compatibile sia con effetti trascurabili sia con effetti rilevanti stimati con scarsa precisione.</p>
</div>
</div>
</section></section><section id="sec-freq-testing-limits" class="level2" data-number="4.10"><h2 data-number="4.10" class="anchored" data-anchor-id="sec-freq-testing-limits">
<span class="header-section-number">4.10</span> Limiti e usi appropriati</h2>
<section id="la-soglia-crea-una-discontinuità-decisionale" class="level3" data-number="4.10.1"><h3 data-number="4.10.1" class="anchored" data-anchor-id="la-soglia-crea-una-discontinuità-decisionale">
<span class="header-section-number">4.10.1</span> La soglia crea una discontinuità decisionale</h3>
<p>Valori come <span class="math inline">\(p=0.049\)</span> e <span class="math inline">\(p=0.051\)</span> rappresentano livelli di incompatibilità molto simili. La loro trasformazione in categorie opposte può far apparire una differenza sostanziale dove esiste soltanto un piccolo scarto numerico.</p>
<p>Una soglia può essere utile quando occorre applicare una regola decisionale prestabilita, ma non dovrebbe sostituire la lettura continua dei risultati né la considerazione della grandezza dell’effetto e della sua incertezza.</p>
</section><section id="lipotesi-nulla-puntuale-può-essere-poco-informativa" class="level3" data-number="4.10.2"><h3 data-number="4.10.2" class="anchored" data-anchor-id="lipotesi-nulla-puntuale-può-essere-poco-informativa">
<span class="header-section-number">4.10.2</span> L’ipotesi nulla puntuale può essere poco informativa</h3>
<p>In molti contesti, sapere che un effetto non è esattamente uguale a zero è meno utile che stabilire se sia abbastanza grande da avere rilevanza pratica, se ricada all’interno di una regione di equivalenza oppure se rimanga stabile tra popolazioni e contesti differenti.</p>
<p>Ciò non rende sempre illegittima un’ipotesi nulla puntuale. Mostra piuttosto che l’ipotesi deve essere scelta in funzione della domanda scientifica e della decisione che si intende sostenere.</p>
</section><section id="un-risultato-non-significativo-non-dimostra-equivalenza" class="level3" data-number="4.10.3"><h3 data-number="4.10.3" class="anchored" data-anchor-id="un-risultato-non-significativo-non-dimostra-equivalenza">
<span class="header-section-number">4.10.3</span> Un risultato non significativo non dimostra equivalenza</h3>
<p>Per sostenere che un effetto sia sufficientemente piccolo da poter essere considerato trascurabile occorre definire in anticipo che cosa significhi <em>sufficientemente piccolo</em> e utilizzare una procedura coerente con questa domanda, come un test di equivalenza o un’analisi basata su una regione di effetti praticamente trascurabili.</p>
<p>Il semplice mancato rifiuto di un’ipotesi nulla puntuale non fornisce questa informazione.</p>
</section><section id="il-valore-p-è-sensibile-al-piano-di-analisi" class="level3" data-number="4.10.4"><h3 data-number="4.10.4" class="anchored" data-anchor-id="il-valore-p-è-sensibile-al-piano-di-analisi">
<span class="header-section-number">4.10.4</span> Il valore-<em>p</em> è sensibile al piano di analisi</h3>
<p>Arresto opzionale della raccolta, confronti multipli, criteri flessibili di esclusione e selezione post hoc delle analisi modificano le proprietà nominali della procedura. Lo stesso valore-<em>p</em> può quindi assumere significati diversi a seconda di come lo studio è stato condotto e analizzato.</p>
<p>Preregistrazione, trasparenza nelle scelte e analisi di sensibilità contribuiscono a rendere il risultato interpretabile, perché permettono di ricostruire il processo che ha prodotto la statistica osservata.</p>
</section><section id="il-test-non-controlla-la-validità-scientifica" class="level3" data-number="4.10.5"><h3 data-number="4.10.5" class="anchored" data-anchor-id="il-test-non-controlla-la-validità-scientifica">
<span class="header-section-number">4.10.5</span> Il test non controlla la validità scientifica</h3>
<p>Un test può essere calcolato correttamente anche quando il campione non è rappresentativo, la misura possiede scarsa validità, il disegno è confuso o il modello è inadeguato. La significatività statistica non corregge questi problemi e non può trasformare un disegno debole in una fonte affidabile di conoscenza.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Quando il test è utile">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Quando il test è utile
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un test frequentista è particolarmente interpretabile quando la domanda decisionale è definita prima dei dati, il disegno collega chiaramente il parametro alla domanda scientifica, il modello e l’errore standard sono adeguati, la famiglia di test è specificata e il risultato viene accompagnato da stime, intervalli e misure della dimensione dell’effetto.</p>
</div>
</div>
</section></section><section id="sec-freq-testing-bayes" class="level2" data-number="4.11"><h2 data-number="4.11" class="anchored" data-anchor-id="sec-freq-testing-bayes">
<span class="header-section-number">4.11</span> Confronto con l’inferenza bayesiana</h2>
<p>Il confronto più utile tra frequentismo e bayesianesimo parte dalle domande che i due approcci consentono di formulare.</p>
<p>Un test frequentista standard chiede:</p>
<blockquote class="blockquote">
<p>Quanto è estremo il risultato sotto <span class="math inline">\(H_0\)</span>?</p>
</blockquote>
<p>Un’analisi bayesiana può invece chiedere:</p>
<blockquote class="blockquote">
<p>Come si distribuisce l’incertezza sul parametro dopo avere combinato la distribuzione a priori e i dati?</p>
</blockquote>
<p>Quando il modello assegna probabilità a ipotesi discrete, la domanda può riguardare anche il modo in cui cambiano le loro probabilità relative dopo l’osservazione dei dati.</p>
<p>Queste formulazioni non rappresentano interpretazioni diverse dello stesso numero. Un valore-<em>p</em> non è una probabilità a posteriori, così come una probabilità a posteriori non possiede automaticamente il controllo frequentista degli errori.</p>
<p>Il Companion approfondisce i limiti dell’uso meccanico del valore-<em>p</em> e mostra come il workflow bayesiano sposti l’attenzione verso il modello generativo, la distribuzione a posteriori, le predizioni e il controllo dell’adeguatezza del modello. Il modulo frequentista conserva tuttavia una funzione essenziale: permette di leggere correttamente la letteratura esistente e di comprendere quali proprietà procedurali siano garantite dai metodi classici.</p>
</section><section id="sec-freq-testing-to-sample-size" class="level2" data-number="4.12"><h2 data-number="4.12" class="anchored" data-anchor-id="sec-freq-testing-to-sample-size">
<span class="header-section-number">4.12</span> Verso la pianificazione dello studio</h2>
<p>Un risultato non significativo può avere origini molto differenti. L’effetto potrebbe essere assente o trascurabile, ma il campione potrebbe anche essere troppo piccolo, la misura poco precisa, l’eterogeneità elevata oppure il modello e il test poco sensibili alla differenza di interesse.</p>
<p>Per valutare in anticipo quanto uno studio potrà essere informativo è necessario specificare quale effetto minimo abbia rilevanza scientifica, quale livello di errore di tipo I sia accettabile, quale potenza si desideri e quali valori della variabilità e della struttura dei dati siano plausibili.</p>
<p>Questi elementi collegano la teoria del test alla progettazione dello studio e introducono il capitolo successivo, dedicato alla pianificazione della numerosità campionaria.</p>
</section><section id="riflessioni-conclusive" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="riflessioni-conclusive">Riflessioni conclusive</h2>
<p>Il test di ipotesi colloca una statistica osservata nella distribuzione che essa avrebbe sotto un’ipotesi nulla e un insieme di assunzioni. Il valore-<em>p</em> misura l’estremità del risultato all’interno di quella distribuzione, mentre il confronto con <span class="math inline">\(\alpha\)</span> applica una regola decisionale.</p>
<p>La distinzione tra Fisher e Neyman–Pearson chiarisce perché nella pratica contemporanea convivano due usi differenti. Il valore-<em>p</em> può essere letto come misura graduata di incompatibilità oppure inserito in una procedura di decisione dotata di errori controllati. Nessuno dei due usi autorizza tuttavia a interpretarlo come probabilità dell’ipotesi o come misura dell’importanza dell’effetto.</p>
<p>Una comunicazione scientifica adeguata non si arresta quindi alla dichiarazione di significatività. Riporta la stima dell’effetto e il relativo intervallo, descrive il disegno e le assunzioni, chiarisce il piano di analisi e valuta la rilevanza sostantiva del risultato.</p>
<p>Il prossimo capitolo completerà la logica decisionale esaminando il rapporto tra effetto bersaglio, potenza e numerosità campionaria.</p>
</section><section id="esercizi" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="esercizi">Esercizi</h2>
<ol type="1">
<li><p>Qual è la differenza tra un valore-<em>p</em> e il livello <span class="math inline">\(\alpha\)</span>?</p></li>
<li><p>Perché <span class="math inline">\(p=0.03\)</span> non significa che l’ipotesi nulla abbia una probabilità del 3% di essere vera?</p></li>
<li><p>Quale ruolo svolge la regola di estremità nella definizione del valore-<em>p</em>?</p></li>
<li><p>Un risultato produce <span class="math inline">\(p=0.18\)</span>. Qual è la conclusione frequentista corretta? Quale conclusione non è giustificata?</p></li>
<li><p>Perché la potenza non può essere descritta senza specificare un effetto sotto l’alternativa?</p></li>
<li><p>Nel test del chi-quadrato emerge <span class="math inline">\(p=0.030\)</span>. Quali informazioni importanti non sono contenute in questo numero?</p></li>
<li><p>Perché scegliere un test unilaterale dopo avere osservato la direzione dell’effetto altera l’interpretazione del test?</p></li>
<li><p>In che modo un’analisi bayesiana e un test frequentista formulano domande diverse sugli stessi dati?</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzioni">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Soluzioni
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Il valore-<em>p</em> è calcolato dai dati e misura l’estremità del risultato sotto <span class="math inline">\(H_0\)</span>. <span class="math inline">\(\alpha\)</span> è una soglia decisionale scelta prima dell’analisi per controllare l’errore di tipo I della procedura.</p></li>
<li><p>Il 3% riguarda la probabilità di risultati almeno altrettanto estremi sotto <span class="math inline">\(H_0\)</span>. Non riguarda la probabilità di <span class="math inline">\(H_0\)</span> condizionata ai dati.</p></li>
<li><p>La regola stabilisce quali valori della statistica siano almeno altrettanto incompatibili con <span class="math inline">\(H_0\)</span> quanto quello osservato. Cambiando la statistica o la scelta tra test unilaterale e bilaterale può cambiare anche il valore-<em>p</em>.</p></li>
<li><p>Al livello convenzionale 0.05, non si rifiuta <span class="math inline">\(H_0\)</span>. Non è giustificato concludere che <span class="math inline">\(H_0\)</span> sia vera, che l’effetto sia esattamente zero o che i gruppi siano equivalenti.</p></li>
<li><p>La probabilità di rifiutare <span class="math inline">\(H_0\)</span> cambia con la distanza tra il parametro vero e il valore nullo. Non esiste quindi una potenza unica per tutte le possibili alternative.</p></li>
<li><p>Il valore-<em>p</em> non contiene la grandezza dell’associazione, la sua precisione, la probabilità che l’associazione esista, l’eventuale causalità o la validità delle categorie e del disegno.</p></li>
<li><p>La coda viene selezionata usando informazione già contenuta nei dati, mentre il calcolo nominale presuppone che la direzione sia stata fissata in anticipo. Il controllo dell’errore di tipo I non è quindi più quello dichiarato.</p></li>
<li><p>Il test frequentista valuta l’estremità dei dati sotto <span class="math inline">\(H_0\)</span>. L’analisi bayesiana rappresenta l’incertezza a posteriori su parametri o ipotesi mediante distribuzione a priori, verosimiglianza e dati.</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Punti chiave">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Punti chiave
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Un test richiede un’ipotesi nulla, un’alternativa, una statistica test, una distribuzione di riferimento e una regola di estremità. Il valore-<em>p</em> viene calcolato sotto <span class="math inline">\(H_0\)</span> e non rappresenta la probabilità di <span class="math inline">\(H_0\)</span>. Il valore-<em>p</em> e il livello <span class="math inline">\(\alpha\)</span> svolgono funzioni differenti, anche se vengono spesso combinati nella pratica NHST. Gli errori di tipo I e di tipo II e la potenza sono proprietà della procedura sotto condizioni specificate, e la potenza dipende dall’effetto considerato sotto l’alternativa. Non rifiutare <span class="math inline">\(H_0\)</span> non significa accettarla o dimostrare equivalenza. Significatività statistica, dimensione dell’effetto e rilevanza sostantiva rimangono concetti distinti. La qualità dell’inferenza dipende dal disegno, dalla misurazione, dal modello e dal piano di analisi. Frequentismo e bayesianesimo rispondono infine a domande probabilistiche differenti.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Ambiente di sviluppo">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Ambiente di sviluppo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Le informazioni sull’ambiente R possono essere ottenute con:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.6.1 (2026-06-24)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin23</span></span>
<span><span class="co">#&gt; Running under: macOS Tahoe 26.5.2</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Zagreb</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          </span></span>
<span><span class="co">#&gt;  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         </span></span>
<span><span class="co">#&gt;  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        </span></span>
<span><span class="co">#&gt; [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      </span></span>
<span><span class="co">#&gt; [13] loo_2.10.1            rstan_2.32.7          StanHeaders_2.32.10  </span></span>
<span><span class="co">#&gt; [16] brms_2.23.0           Rcpp_1.1.2            sessioninfo_1.2.4    </span></span>
<span><span class="co">#&gt; [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    </span></span>
<span><span class="co">#&gt; [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          </span></span>
<span><span class="co">#&gt; [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         </span></span>
<span><span class="co">#&gt;  [4] S7_0.2.2              fastmap_1.2.0         tensorA_0.36.2.1     </span></span>
<span><span class="co">#&gt;  [7] digest_0.6.39         timechange_0.4.0      estimability_2.0.0   </span></span>
<span><span class="co">#&gt; [10] lifecycle_1.0.5       magrittr_2.0.5        compiler_4.6.1       </span></span>
<span><span class="co">#&gt; [13] rlang_1.3.0           tools_4.6.1           yaml_2.3.12          </span></span>
<span><span class="co">#&gt; [16] knitr_1.51            labeling_0.4.3        bridgesampling_1.2-1 </span></span>
<span><span class="co">#&gt; [19] htmlwidgets_1.6.4     pkgbuild_1.4.8        curl_7.1.0           </span></span>
<span><span class="co">#&gt; [22] RColorBrewer_1.1-3    abind_1.4-8           purrr_1.2.2          </span></span>
<span><span class="co">#&gt; [25] grid_4.6.1            stats4_4.6.1          xtable_1.8-8         </span></span>
<span><span class="co">#&gt; [28] inline_0.3.21         emmeans_2.0.4         scales_1.4.0         </span></span>
<span><span class="co">#&gt; [31] cli_3.6.6             mvtnorm_1.4-2         rmarkdown_2.31       </span></span>
<span><span class="co">#&gt; [34] generics_0.1.4        otel_0.2.0            RcppParallel_5.1.11-2</span></span>
<span><span class="co">#&gt; [37] cachem_1.1.0          stringr_1.6.0         parallel_4.6.1       </span></span>
<span><span class="co">#&gt; [40] vctrs_0.7.3           V8_8.2.0              Matrix_1.7-6         </span></span>
<span><span class="co">#&gt; [43] jsonlite_2.0.0        arrayhelpers_1.1-2    glue_1.8.1           </span></span>
<span><span class="co">#&gt; [46] codetools_0.2-20      distributional_0.8.1  lubridate_1.9.5      </span></span>
<span><span class="co">#&gt; [49] stringi_1.8.7         gtable_0.3.6          QuickJSR_1.10.0      </span></span>
<span><span class="co">#&gt; [52] pillar_1.11.1         htmltools_0.5.9       Brobdingnag_1.2-9    </span></span>
<span><span class="co">#&gt; [55] R6_2.6.1              textshaping_1.0.5     rprojroot_2.1.1      </span></span>
<span><span class="co">#&gt; [58] evaluate_1.0.5        lattice_0.22-9        backports_1.5.1      </span></span>
<span><span class="co">#&gt; [61] memoise_2.0.1         broom_1.0.13          snakecase_0.11.1     </span></span>
<span><span class="co">#&gt; [64] rstantools_2.6.0      coda_0.19-4.1         gridExtra_2.3.1      </span></span>
<span><span class="co">#&gt; [67] nlme_3.1-170          checkmate_2.3.4       xfun_0.60            </span></span>
<span><span class="co">#&gt; [70] pkgconfig_2.0.3</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</div>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:https?:)?//ccaudek\.github\.io/utet-prob/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/frequentist_inference/03_conf_interv.html" class="pagination-link" aria-label="Intervalli di confidenza">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Intervalli di confidenza</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/frequentist_inference/05_sample_size.html" class="pagination-link" aria-label="Dimensione campionaria, precisione e potenza">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Dimensione campionaria, precisione e potenza</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Inferenza frequentista in psicologia</strong> — Modulo del progetto UTET a supporto del manuale <em>Inferenza bayesiana in psicologia: Ragionare con l’incertezza</em>.</p>
</div>   
    <div class="nav-footer-center">

<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/utet-frequentista/issues/new" class="toc-action"><i class="bi bi-github"></i>Segnala un problema</a></li></ul></div><div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Preferenze cookie</a></div></div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>