<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Modulo introduttivo sull’inferenza frequentista in psicologia, parte del progetto UTET a supporto del manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<title>6&nbsp; Confrontare due gruppi indipendenti – Inferenza frequentista in psicologia</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/epilogo/epilogo.html" rel="next">
<link href="../../chapters/frequentist_inference/05_sample_size.html" rel="prev">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bd31b91f9ddb1a75e3744ba9797c8182.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-662b1d839dd28a08d17be9d78b753e45.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bd31b91f9ddb1a75e3744ba9797c8182.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-353ec92dc31bcb37568820202c74e1ec.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-dde258841ab64df460dbb5600124b771.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-353ec92dc31bcb37568820202c74e1ec.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script><script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script><script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"headline",
  "consent_type":"express",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"it"
  });
});
</script><style>html{ scroll-behavior: smooth; }</style>
<link href="../../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../../site_libs/pagedtable-1.1/js/pagedtable.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<meta property="og:title" content="6&nbsp; Confrontare due gruppi indipendenti – Inferenza frequentista in psicologia">
<meta property="og:description" content="Modulo introduttivo sull’inferenza frequentista in psicologia, parte del progetto UTET a supporto del manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<meta property="og:image" content="https://ccaudek.github.io/utet-frequentista/chapters/frequentist_inference/06_two_ind_samples_files/figure-html/fig-two-groups-data-1.png">
<meta property="og:site_name" content="Inferenza frequentista in psicologia">
<meta property="og:image:alt" content="Due gruppi di punti sovrapposti a boxplot; il gruppo intervento mostra punteggi medi più alti.">
<meta property="og:image:height" content="1483">
<meta property="og:image:width" content="2400">
<meta name="twitter:title" content="6&nbsp; Confrontare due gruppi indipendenti – Inferenza frequentista in psicologia">
<meta name="twitter:description" content="Modulo introduttivo sull’inferenza frequentista in psicologia, parte del progetto UTET a supporto del manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<meta name="twitter:image" content="https://ccaudek.github.io/utet-frequentista/chapters/frequentist_inference/06_two_ind_samples_files/figure-html/fig-two-groups-data-1.png">
<meta name="twitter:image:alt" content="Due gruppi di punti sovrapposti a boxplot; il gruppo intervento mostra punteggi medi più alti.">
<meta name="twitter:image-height" content="1483">
<meta name="twitter:image-width" content="2400">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://ccaudek.github.io/utet-frequentista/chapters/frequentist_inference/06_two_ind_samples.html">
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/frequentist_inference/introduction_frequentist_inference.html">Frequentismo</a></li><li class="breadcrumb-item"><a href="../../chapters/frequentist_inference/06_two_ind_samples.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Confrontare due gruppi indipendenti</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Inferenza frequentista in psicologia</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/ccaudek/utet-frequentista/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Attiva/disattiva la modalità oscura"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
    <div id="quarto-search" class="quarto-navigation-tool px-1" title="Ricerca"></div>
</div>
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Percorso e obiettivi</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Frequentismo</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/introduction_frequentist_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione all’inferenza frequentista in un percorso bayesiano</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/01_galton.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Origini storiche dell’approccio frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/02_stime_parametri.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Stime, stimatori e parametri</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/03_conf_interv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Intervalli di confidenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/04_test_ipotesi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Test di ipotesi e valore-<em>p</em></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/05_sample_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Dimensione campionaria, precisione e potenza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/frequentist_inference/06_two_ind_samples.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Confrontare due gruppi indipendenti</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Epilogo</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epilogo/epilogo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conclusioni</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2"><h2 id="toc-title">Sommario</h2>
   
  <ul class="collapse">
<li><a href="#sec-freq-two-samples-estimand" id="toc-sec-freq-two-samples-estimand" class="nav-link active" data-scroll-target="#sec-freq-two-samples-estimand"><span class="header-section-number">6.1</span> Prima del test: definire il confronto</a></li>
  <li><a href="#sec-freq-independent-paired" id="toc-sec-freq-independent-paired" class="nav-link" data-scroll-target="#sec-freq-independent-paired"><span class="header-section-number">6.2</span> Gruppi indipendenti, dati appaiati e misure ripetute</a></li>
  <li><a href="#sec-freq-two-samples-model" id="toc-sec-freq-two-samples-model" class="nav-link" data-scroll-target="#sec-freq-two-samples-model"><span class="header-section-number">6.3</span> Il modello inferenziale</a></li>
  <li><a href="#sec-freq-student-welch" id="toc-sec-freq-student-welch" class="nav-link" data-scroll-target="#sec-freq-student-welch"><span class="header-section-number">6.4</span> Test <em>t</em> classico e test di Welch</a></li>
  <li><a href="#sec-freq-two-samples-assumptions" id="toc-sec-freq-two-samples-assumptions" class="nav-link" data-scroll-target="#sec-freq-two-samples-assumptions"><span class="header-section-number">6.5</span> Assunzioni e adeguatezza</a></li>
  <li><a href="#sec-freq-two-samples-example" id="toc-sec-freq-two-samples-example" class="nav-link" data-scroll-target="#sec-freq-two-samples-example"><span class="header-section-number">6.6</span> Un esempio guidato</a></li>
  <li><a href="#sec-freq-two-samples-welch-example" id="toc-sec-freq-two-samples-welch-example" class="nav-link" data-scroll-target="#sec-freq-two-samples-welch-example"><span class="header-section-number">6.7</span> Eseguire il test di Welch</a></li>
  <li><a href="#sec-freq-two-samples-pooled-example" id="toc-sec-freq-two-samples-pooled-example" class="nav-link" data-scroll-target="#sec-freq-two-samples-pooled-example"><span class="header-section-number">6.8</span> Il caso con varianza comune</a></li>
  <li><a href="#sec-freq-two-samples-integrated" id="toc-sec-freq-two-samples-integrated" class="nav-link" data-scroll-target="#sec-freq-two-samples-integrated"><span class="header-section-number">6.9</span> Interpretare insieme le quantità</a></li>
  <li><a href="#sec-freq-two-samples-relevance" id="toc-sec-freq-two-samples-relevance" class="nav-link" data-scroll-target="#sec-freq-two-samples-relevance"><span class="header-section-number">6.10</span> Significatività, equivalenza e rilevanza pratica</a></li>
  <li><a href="#sec-freq-two-samples-causality" id="toc-sec-freq-two-samples-causality" class="nav-link" data-scroll-target="#sec-freq-two-samples-causality"><span class="header-section-number">6.11</span> Dalla differenza osservata all’effetto causale</a></li>
  <li><a href="#sec-freq-two-samples-regression" id="toc-sec-freq-two-samples-regression" class="nav-link" data-scroll-target="#sec-freq-two-samples-regression"><span class="header-section-number">6.12</span> Il test <em>t</em> come modello lineare</a></li>
  <li><a href="#sec-freq-two-samples-bayes" id="toc-sec-freq-two-samples-bayes" class="nav-link" data-scroll-target="#sec-freq-two-samples-bayes"><span class="header-section-number">6.13</span> Che cosa cambia nel modello bayesiano?</a></li>
  <li><a href="#sec-freq-two-samples-report" id="toc-sec-freq-two-samples-report" class="nav-link" data-scroll-target="#sec-freq-two-samples-report"><span class="header-section-number">6.14</span> Come riportare il risultato</a></li>
  </ul><div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/utet-frequentista/blob/main/chapters/frequentist_inference/06_two_ind_samples.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/utet-frequentista/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/frequentist_inference/introduction_frequentist_inference.html">Frequentismo</a></li><li class="breadcrumb-item"><a href="../../chapters/frequentist_inference/06_two_ind_samples.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Confrontare due gruppi indipendenti</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-freq-two-samples" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Confrontare due gruppi indipendenti</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-default callout-note callout-titled" title="In sintesi">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>In sintesi
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Da sapere</strong> Il confronto tra due gruppi indipendenti stima una differenza tra medie e ne valuta la precisione e la compatibilità con un valore nullo. Il test <em>t</em> di Welch è spesso una scelta predefinita appropriata perché non richiede l’uguaglianza delle varianze.</p>
<p><strong>Da saper fare</strong> Definire la differenza di interesse; riconoscere quando i gruppi sono indipendenti; leggere stime descrittive, intervallo di confidenza, valore-<em>p</em> e dimensione dell’effetto; distinguere associazione e causalità; collegare il test <em>t</em> a un modello di regressione con predittore dicotomico.</p>
</div>
</div>
<section id="introduzione" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="introduzione">Introduzione</h2>
<p>Il confronto tra due gruppi indipendenti è una delle situazioni più comuni nella ricerca psicologica. Possiamo confrontare un gruppo sottoposto a un intervento con un gruppo di controllo, due condizioni sperimentali oppure due gruppi definiti da una caratteristica osservata.</p>
<p>Questo capitolo riunisce i concetti introdotti nel modulo:</p>
<p><span class="math display">\[
\text{stima}
\longrightarrow
\text{errore standard}
\longrightarrow
\text{intervallo di confidenza}
\longrightarrow
\text{test}
\longrightarrow
\text{dimensione dell'effetto}.
\]</span></p>
<p>L’obiettivo non è imparare una procedura isolata. È comprendere come questi elementi descrivano aspetti differenti dello stesso confronto.</p>
<p>Nel quadro frequentista, il test <em>t</em> risponde a una domanda condizionale:</p>
<blockquote class="blockquote">
<p>Se la differenza tra le medie delle popolazioni fosse nulla e il modello fosse adeguato, quanto sarebbe estremo il risultato osservato?</p>
</blockquote>
<p>Questa domanda non coincide con la probabilità che le medie siano uguali, con la probabilità che l’intervento funzioni o con la probabilità che la differenza superi una soglia clinicamente importante.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Prerequisiti">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Prerequisiti
</div>
</div>
<div class="callout-body-container callout-body">
<p>È utile avere letto:</p>
<ul>
<li>
<a href="02_stime_parametri.html" class="quarto-xref"><span>Capitolo 2</span></a>, per stimatore, stima ed errore standard;</li>
<li>
<a href="03_conf_interv.html" class="quarto-xref"><span>Capitolo 3</span></a>, per copertura e interpretazione degli intervalli;</li>
<li>
<a href="04_test_ipotesi.html" class="quarto-xref"><span>Capitolo 4</span></a>, per valore-<em>p</em>, <span class="math inline">\(\alpha\)</span> ed errori decisionali;</li>
<li>
<a href="05_sample_size.html" class="quarto-xref"><span>Capitolo 5</span></a>, per effetto bersaglio, potenza e numerosità.</li>
</ul>
<p>Questo capitolo applica tali concetti a un unico caso e conclude la parte operativa del modulo.</p>
</div>
</div>
</section><section id="panoramica-del-capitolo" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="panoramica-del-capitolo">Panoramica del capitolo</h2>
<p>Il capitolo procede in nove passaggi:</p>
<ol type="1">
<li>definisce la quantità che si vuole confrontare;</li>
<li>distingue gruppi indipendenti, dati appaiati e misure ripetute;</li>
<li>presenta il modello del test <em>t</em> classico e quello di Welch;</li>
<li>esamina disegno, distribuzioni e valori anomali;</li>
<li>svolge un esempio completo in R;</li>
<li>integra differenza grezza, intervallo, valore-<em>p</em> ed effetto standardizzato;</li>
<li>chiarisce quando una differenza può essere interpretata causalmente;</li>
<li>mostra l’equivalenza con la regressione lineare;</li>
<li>collega il confronto frequentista ai modelli bayesiani del Companion.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Preparazione del notebook">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Preparazione del notebook
</div>
</div>
<div class="callout-body-container callout-body">
<p>Per eseguire gli esempi, prepara l’ambiente comune del progetto:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section><section id="sec-freq-two-samples-estimand" class="level2" data-number="6.1"><h2 data-number="6.1" class="anchored" data-anchor-id="sec-freq-two-samples-estimand">
<span class="header-section-number">6.1</span> Prima del test: definire il confronto</h2>
<p>Immaginiamo uno studio su un intervento di regolazione emotiva. Un gruppo riceve l’intervento e un gruppo di controllo non lo riceve. Al termine dello studio viene misurato il benessere psicologico.</p>
<p>Indichiamo con:</p>
<p><span class="math display">\[
\mu_1
=
\text{media della popolazione del gruppo intervento},
\]</span></p>
<p><span class="math display">\[
\mu_0
=
\text{media della popolazione del gruppo controllo}.
\]</span></p>
<p>La quantità bersaglio è:</p>
<p><span class="math display">\[
\Delta
=
\mu_1-\mu_0.
\]</span></p>
<p>La sua stima campionaria è:</p>
<p><span class="math display">\[
\widehat{\Delta}
=
\bar X_1-\bar X_0.
\]</span></p>
<p>Il segno dipende dall’ordine della sottrazione. Con la definizione adottata:</p>
<ul>
<li>
<span class="math inline">\(\widehat{\Delta}&gt;0\)</span> indica una media maggiore nel gruppo intervento;</li>
<li>
<span class="math inline">\(\widehat{\Delta}&lt;0\)</span> indica una media maggiore nel gruppo controllo.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled" title="Definire l'ordine prima di interpretare il segno">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Definire l’ordine prima di interpretare il segno
</div>
</div>
<div class="callout-body-container callout-body">
<p>La stessa differenza può essere scritta come intervento meno controllo oppure controllo meno intervento. Il valore assoluto non cambia, ma il segno sì.</p>
<p>L’ordine deve essere dichiarato e mantenuto coerente in stima, intervallo, dimensione dell’effetto e resoconto.</p>
</div>
</div>
<section id="quale-popolazione-rappresentano-le-medie" class="level3" data-number="6.1.1"><h3 data-number="6.1.1" class="anchored" data-anchor-id="quale-popolazione-rappresentano-le-medie">
<span class="header-section-number">6.1.1</span> Quale popolazione rappresentano le medie?</h3>
<p>Le medie <span class="math inline">\(\mu_1\)</span> e <span class="math inline">\(\mu_0\)</span> dipendono da:</p>
<ul>
<li>popolazione a cui si vuole generalizzare;</li>
<li>criteri di inclusione;</li>
<li>modalità di assegnazione ai gruppi;</li>
<li>momento e strumento di misurazione;</li>
<li>trattamento dei dati mancanti;</li>
<li>modello statistico.</li>
</ul>
<p>Una differenza tra medie non è un oggetto separato dal disegno. Prima di calcolare il test occorre chiarire che cosa rappresentano i due gruppi e quale confronto sia scientificamente rilevante.</p>
</section></section><section id="sec-freq-independent-paired" class="level2" data-number="6.2"><h2 data-number="6.2" class="anchored" data-anchor-id="sec-freq-independent-paired">
<span class="header-section-number">6.2</span> Gruppi indipendenti, dati appaiati e misure ripetute</h2>
<p>Due gruppi sono <strong>indipendenti</strong> quando l’osservazione di una persona nel primo gruppo non è naturalmente collegata a una specifica osservazione del secondo gruppo.</p>
<p>Esempi:</p>
<ul>
<li>persone differenti assegnate a intervento e controllo;</li>
<li>partecipanti provenienti da due popolazioni distinte;</li>
<li>due gruppi osservazionali senza abbinamento individuale.</li>
</ul>
<p>Non sono invece indipendenti:</p>
<ul>
<li>misure prima e dopo sulle stesse persone;</li>
<li>coppie abbinate;</li>
<li>gemelli o membri della stessa famiglia;</li>
<li>studenti nella stessa classe, quando la dipendenza del gruppo non è modellata;</li>
<li>più osservazioni prodotte dallo stesso partecipante.</li>
</ul>
<p>Nel caso di coppie o misure ripetute, la quantità rilevante è spesso la media delle differenze entro coppia. Usare il test per gruppi indipendenti ignora la struttura dei dati e può produrre errori standard inadeguati.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="L'indipendenza non si verifica con un test automatico">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Avviso</span>L’indipendenza non si verifica con un test automatico
</div>
</div>
<div class="callout-body-container callout-body">
<p>È soprattutto una proprietà del disegno e del processo di raccolta. Un grafico o un test di normalità non possono dimostrare che osservazioni provenienti dalla stessa classe, famiglia o persona siano indipendenti.</p>
</div>
</div>
</section><section id="sec-freq-two-samples-model" class="level2" data-number="6.3"><h2 data-number="6.3" class="anchored" data-anchor-id="sec-freq-two-samples-model">
<span class="header-section-number">6.3</span> Il modello inferenziale</h2>
<section id="ipotesi-nulla-e-alternativa" class="level3" data-number="6.3.1"><h3 data-number="6.3.1" class="anchored" data-anchor-id="ipotesi-nulla-e-alternativa">
<span class="header-section-number">6.3.1</span> Ipotesi nulla e alternativa</h3>
<p>Nel test bilaterale:</p>
<p><span class="math display">\[
H_0:\Delta=0,
\]</span></p>
<p><span class="math display">\[
H_1:\Delta\neq0.
\]</span></p>
<p>Un’alternativa direzionale può essere:</p>
<p><span class="math display">\[
H_1:\Delta&gt;0.
\]</span></p>
<p>La direzione deve essere scelta prima di osservare i dati e deve avere una motivazione sostantiva. Il test bilaterale è una scelta introduttiva prudente quando deviazioni in entrambe le direzioni sarebbero scientificamente rilevanti.</p>
</section><section id="struttura-generale-della-statistica" class="level3" data-number="6.3.2"><h3 data-number="6.3.2" class="anchored" data-anchor-id="struttura-generale-della-statistica">
<span class="header-section-number">6.3.2</span> Struttura generale della statistica</h3>
<p>La statistica test ha la forma:</p>
<p><span class="math display">\[
t
=
\frac{\widehat{\Delta}-0}
{\widehat{\operatorname{SE}}(\widehat{\Delta})}.
\]</span></p>
<p>Il numeratore è la differenza osservata rispetto al valore nullo. Il denominatore misura quanto la differenza tra medie varierebbe sotto campionamenti ripetuti, secondo il modello adottato.</p>
</section></section><section id="sec-freq-student-welch" class="level2" data-number="6.4"><h2 data-number="6.4" class="anchored" data-anchor-id="sec-freq-student-welch">
<span class="header-section-number">6.4</span> Test <em>t</em> classico e test di Welch</h2>
<section id="test-classico-con-varianze-uguali" class="level3" data-number="6.4.1"><h3 data-number="6.4.1" class="anchored" data-anchor-id="test-classico-con-varianze-uguali">
<span class="header-section-number">6.4.1</span> Test classico con varianze uguali</h3>
<p>Il test classico assume una varianza comune nelle due popolazioni. La deviazione standard pooled è:</p>
<p><span class="math display">\[
s_p
=
\sqrt{
\frac{
(n_1-1)s_1^2+(n_0-1)s_0^2
}{
n_1+n_0-2
}
}.
\]</span></p>
<p>L’errore standard è:</p>
<p><span class="math display">\[
\widehat{\operatorname{SE}}_{\text{pooled}}
=
s_p
\sqrt{
\frac{1}{n_1}+\frac{1}{n_0}
}.
\]</span></p>
<p>La statistica segue una distribuzione <em>t</em> con:</p>
<p><span class="math display">\[
df=n_1+n_0-2
\]</span></p>
<p>quando le assunzioni del modello sono soddisfatte.</p>
</section><section id="test-di-welch" class="level3" data-number="6.4.2"><h3 data-number="6.4.2" class="anchored" data-anchor-id="test-di-welch">
<span class="header-section-number">6.4.2</span> Test di Welch</h3>
<p>Il test di Welch non impone una varianza comune. Usa:</p>
<p><span class="math display">\[
\widehat{\operatorname{SE}}_{\text{Welch}}
=
\sqrt{
\frac{s_1^2}{n_1}
+
\frac{s_0^2}{n_0}
}.
\]</span></p>
<p>I gradi di libertà vengono approssimati mediante la formula di Welch–Satterthwaite:</p>
<p><span class="math display">\[
\nu
=
\frac{
\left(
s_1^2/n_1+s_0^2/n_0
\right)^2
}{
\frac{(s_1^2/n_1)^2}{n_1-1}
+
\frac{(s_0^2/n_0)^2}{n_0-1}
}.
\]</span></p>
<p>In R, <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> usa Welch per impostazione predefinita.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Perché Welch è una buona scelta predefinita">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Perché Welch è una buona scelta predefinita
</div>
</div>
<div class="callout-body-container callout-body">
<p>Quando varianze e numerosità sono simili, Welch e il test classico producono spesso risultati quasi identici.</p>
<p>Quando differiscono, Welch protegge meglio dall’assunzione non giustificata di una varianza comune. Non è corretto descriverlo semplicemente come «più prudente»: è una procedura costruita per un modello che consente dispersioni differenti.</p>
</div>
</div>
<p>L’uso del test classico dovrebbe derivare da una ragione per assumere una varianza comune, non dal mancato rifiuto di un test preliminare sulle varianze. Testare prima l’uguaglianza delle varianze e scegliere poi il test sulla base dello stesso campione crea una procedura in due stadi con proprietà meno trasparenti.</p>
</section></section><section id="sec-freq-two-samples-assumptions" class="level2" data-number="6.5"><h2 data-number="6.5" class="anchored" data-anchor-id="sec-freq-two-samples-assumptions">
<span class="header-section-number">6.5</span> Assunzioni e adeguatezza</h2>
<section id="indipendenza-e-disegno" class="level3" data-number="6.5.1"><h3 data-number="6.5.1" class="anchored" data-anchor-id="indipendenza-e-disegno">
<span class="header-section-number">6.5.1</span> Indipendenza e disegno</h3>
<p>L’indipendenza è essenziale per le formule standard. Clustering, abbinamento o misure ripetute richiedono procedure differenti.</p>
</section><section id="esito-quantitativo" class="level3" data-number="6.5.2"><h3 data-number="6.5.2" class="anchored" data-anchor-id="esito-quantitativo">
<span class="header-section-number">6.5.2</span> Esito quantitativo</h3>
<p>Il test confronta medie. L’esito deve quindi essere quantitativo o trattato come una misura approssimativamente quantitativa. Questa scelta deve essere sostantivamente difendibile, soprattutto per punteggi con pochi livelli o forti effetti di pavimento e soffitto.</p>
</section><section id="distribuzione-entro-i-gruppi" class="level3" data-number="6.5.3"><h3 data-number="6.5.3" class="anchored" data-anchor-id="distribuzione-entro-i-gruppi">
<span class="header-section-number">6.5.3</span> Distribuzione entro i gruppi</h3>
<p>L’esattezza del test classico e di Welch deriva da popolazioni normali. Le procedure sono spesso robuste a deviazioni moderate quando:</p>
<ul>
<li>i campioni non sono molto piccoli;</li>
<li>le distribuzioni non sono fortemente asimmetriche;</li>
<li>non sono presenti valori estremi influenti;</li>
<li>il disegno non combina forte squilibrio e forte eteroschedasticità.</li>
</ul>
<p>La robustezza non significa che la forma dei dati sia irrilevante. Con campioni piccoli, code pesanti o valori anomali, media, deviazione standard e test possono essere instabili.</p>
</section><section id="valori-anomali" class="level3" data-number="6.5.4"><h3 data-number="6.5.4" class="anchored" data-anchor-id="valori-anomali">
<span class="header-section-number">6.5.4</span> Valori anomali</h3>
<p>Un valore anomalo può:</p>
<ul>
<li>spostare una media;</li>
<li>aumentare una deviazione standard;</li>
<li>modificare l’errore standard;</li>
<li>alterare il valore-<em>p</em> e la dimensione dell’effetto.</li>
</ul>
<p>Non va eliminato automaticamente. Occorre verificare se derivi da errore, se sia plausibile per la popolazione e quanto le conclusioni dipendano dalla sua presenza.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Il controllo delle assunzioni è parte dell'analisi">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Il controllo delle assunzioni è parte dell’analisi
</div>
</div>
<div class="callout-body-container callout-body">
<p>Non consiste nel cercare un test che autorizzi meccanicamente l’uso del test <em>t</em>. Richiede di collegare grafici, disegno, qualità delle misure e conseguenze delle deviazioni al modello.</p>
</div>
</div>
</section></section><section id="sec-freq-two-samples-example" class="level2" data-number="6.6"><h2 data-number="6.6" class="anchored" data-anchor-id="sec-freq-two-samples-example">
<span class="header-section-number">6.6</span> Un esempio guidato</h2>
<p>Consideriamo dati didattici sul benessere psicologico.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">benessere_intervento</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="fl">27</span>, <span class="fl">31</span>, <span class="fl">29</span>, <span class="fl">33</span>, <span class="fl">35</span>, <span class="fl">30</span>,</span>
<span>  <span class="fl">32</span>, <span class="fl">28</span>, <span class="fl">34</span>, <span class="fl">31</span>, <span class="fl">36</span>, <span class="fl">29</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">benessere_controllo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="fl">24</span>, <span class="fl">26</span>, <span class="fl">28</span>, <span class="fl">25</span>, <span class="fl">29</span>, <span class="fl">27</span>,</span>
<span>  <span class="fl">23</span>, <span class="fl">30</span>, <span class="fl">26</span>, <span class="fl">25</span>, <span class="fl">28</span>, <span class="fl">24</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">dati_benessere</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  gruppo <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span></span>
<span>      <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Controllo"</span>, <span class="st">"Intervento"</span><span class="op">)</span>,</span>
<span>      each <span class="op">=</span> <span class="fl">12</span></span>
<span>    <span class="op">)</span>,</span>
<span>    levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Controllo"</span>, <span class="st">"Intervento"</span><span class="op">)</span></span>
<span>  <span class="op">)</span>,</span>
<span>  benessere <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="va">benessere_controllo</span>,</span>
<span>    <span class="va">benessere_intervento</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>La codifica fissa l’ordine del confronto come:</p>
<p><span class="math display">\[
\Delta
=
\mu_{\text{intervento}}
-
\mu_{\text{controllo}}.
\]</span></p>
<section id="descrizione-prima-dellinferenza" class="level3" data-number="6.6.1"><h3 data-number="6.6.1" class="anchored" data-anchor-id="descrizione-prima-dellinferenza">
<span class="header-section-number">6.6.1</span> Descrizione prima dell’inferenza</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">gruppi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/split.html">split</a></span><span class="op">(</span></span>
<span>  <span class="va">dati_benessere</span><span class="op">$</span><span class="va">benessere</span>,</span>
<span>  <span class="va">dati_benessere</span><span class="op">$</span><span class="va">gruppo</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">descrittive</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  gruppo <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">gruppi</span><span class="op">)</span>,</span>
<span>  n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">vapply</a></span><span class="op">(</span><span class="va">gruppi</span>, <span class="va">length</span>, <span class="fu"><a href="https://rdrr.io/r/base/integer.html">integer</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  media <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">vapply</a></span><span class="op">(</span><span class="va">gruppi</span>, <span class="va">mean</span>, <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">numeric</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  deviazione_standard <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">vapply</a></span><span class="op">(</span><span class="va">gruppi</span>, <span class="va">sd</span>, <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">numeric</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  row.names <span class="op">=</span> <span class="cn">NULL</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">descrittive</span><span class="op">$</span><span class="va">media</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">descrittive</span><span class="op">$</span><span class="va">media</span>, <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">descrittive</span><span class="op">$</span><span class="va">deviazione_standard</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">descrittive</span><span class="op">$</span><span class="va">deviazione_standard</span>, <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">descrittive</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-two-groups-descriptives" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-two-groups-descriptives-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabella&nbsp;6.1: Statistiche descrittive dei punteggi di benessere nei due gruppi.
</figcaption><div aria-describedby="tbl-two-groups-descriptives-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">gruppo</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">media</th>
<th style="text-align: right;">deviazione_standard</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Controllo</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">26.2</td>
<td style="text-align: right;">2.18</td>
</tr>
<tr class="even">
<td style="text-align: left;">Intervento</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">31.2</td>
<td style="text-align: right;">2.83</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Le medie campionarie sono:</p>
<p><span class="math display">\[
\bar x_{\text{intervento}}=31.25,
\]</span></p>
<p><span class="math display">\[
\bar x_{\text{controllo}}=26.25.
\]</span></p>
<p>La differenza osservata è:</p>
<p><span class="math display">\[
\widehat{\Delta}=5.00.
\]</span></p>
</section><section id="visualizzare-distribuzioni-e-osservazioni" class="level3" data-number="6.6.2"><h3 data-number="6.6.2" class="anchored" data-anchor-id="visualizzare-distribuzioni-e-osservazioni">
<span class="header-section-number">6.6.2</span> Visualizzare distribuzioni e osservazioni</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span></span>
<span>  <span class="va">dati_benessere</span>,</span>
<span>  <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">gruppo</span>, y <span class="op">=</span> <span class="va">benessere</span><span class="op">)</span></span>
<span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_boxplot</span><span class="op">(</span></span>
<span>    width <span class="op">=</span> <span class="fl">0.45</span>,</span>
<span>    alpha <span class="op">=</span> <span class="fl">0.35</span>,</span>
<span>    outlier.shape <span class="op">=</span> <span class="cn">NA</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_jitter</span><span class="op">(</span></span>
<span>    width <span class="op">=</span> <span class="fl">0.08</span>,</span>
<span>    alpha <span class="op">=</span> <span class="fl">0.8</span>,</span>
<span>    size <span class="op">=</span> <span class="fl">2</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">stat_summary</span><span class="op">(</span></span>
<span>    fun <span class="op">=</span> <span class="va">mean</span>,</span>
<span>    geom <span class="op">=</span> <span class="st">"point"</span>,</span>
<span>    shape <span class="op">=</span> <span class="fl">18</span>,</span>
<span>    size <span class="op">=</span> <span class="fl">4</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="st">"Gruppo"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Punteggio di benessere"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-two-groups-data" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Due gruppi di punti sovrapposti a boxplot; il gruppo intervento mostra punteggi medi più alti." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-two-groups-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06_two_ind_samples_files/figure-html/fig-two-groups-data-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figura&nbsp;6.1: Punteggi individuali e distribuzioni nei gruppi controllo e intervento. Il simbolo a rombo indica la media."><img src="06_two_ind_samples_files/figure-html/fig-two-groups-data-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%" alt="Due gruppi di punti sovrapposti a boxplot; il gruppo intervento mostra punteggi medi più alti."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-groups-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.1: Punteggi individuali e distribuzioni nei gruppi controllo e intervento. Il simbolo a rombo indica la media.
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-two-groups-data" class="quarto-xref">Figura&nbsp;<span>6.1</span></a> mostra posizione, dispersione, sovrapposizione e singole osservazioni. Il grafico non sostituisce l’inferenza, ma impedisce che il risultato venga ridotto a un unico numero.</p>
</section></section><section id="sec-freq-two-samples-welch-example" class="level2" data-number="6.7"><h2 data-number="6.7" class="anchored" data-anchor-id="sec-freq-two-samples-welch-example">
<span class="header-section-number">6.7</span> Eseguire il test di Welch</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_welch</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span></span>
<span>  <span class="va">benessere</span> <span class="op">~</span> <span class="va">gruppo</span>,</span>
<span>  data <span class="op">=</span> <span class="va">dati_benessere</span>,</span>
<span>  alternative <span class="op">=</span> <span class="st">"two.sided"</span>,</span>
<span>  var.equal <span class="op">=</span> <span class="cn">FALSE</span>,</span>
<span>  conf.level <span class="op">=</span> <span class="fl">0.95</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">test_welch</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Welch Two Sample t-test</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; data:  benessere by gruppo</span></span>
<span><span class="co">#&gt; t = -5, df = 21, p-value = 0.00009</span></span>
<span><span class="co">#&gt; alternative hypothesis: true difference in means between group Controllo and group Intervento is not equal to 0</span></span>
<span><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span><span class="co">#&gt;  -7.15 -2.85</span></span>
<span><span class="co">#&gt; sample estimates:</span></span>
<span><span class="co">#&gt;  mean in group Controllo mean in group Intervento </span></span>
<span><span class="co">#&gt;                     26.2                     31.2</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Poiché il primo livello del fattore è <code>Controllo</code>, la formula di R riporta inizialmente la differenza:</p>
<p><span class="math display">\[
\mu_{\text{controllo}}
-
\mu_{\text{intervento}}.
\]</span></p>
<p>Per mantenere l’ordine scelto nel capitolo, calcoliamo esplicitamente intervento meno controllo:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">n_intervento</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">benessere_intervento</span><span class="op">)</span></span>
<span><span class="va">n_controllo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">benessere_controllo</span><span class="op">)</span></span>
<span></span>
<span><span class="va">m_intervento</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">benessere_intervento</span><span class="op">)</span></span>
<span><span class="va">m_controllo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">benessere_controllo</span><span class="op">)</span></span>
<span></span>
<span><span class="va">s_intervento</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">benessere_intervento</span><span class="op">)</span></span>
<span><span class="va">s_controllo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">benessere_controllo</span><span class="op">)</span></span>
<span></span>
<span><span class="va">differenza</span> <span class="op">&lt;-</span> <span class="va">m_intervento</span> <span class="op">-</span> <span class="va">m_controllo</span></span>
<span></span>
<span><span class="va">se_welch</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span></span>
<span>  <span class="va">s_intervento</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="va">n_intervento</span> <span class="op">+</span></span>
<span>    <span class="va">s_controllo</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="va">n_controllo</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">df_welch</span> <span class="op">&lt;-</span> <span class="op">(</span></span>
<span>  <span class="va">s_intervento</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="va">n_intervento</span> <span class="op">+</span></span>
<span>    <span class="va">s_controllo</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="va">n_controllo</span></span>
<span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="op">(</span></span>
<span>  <span class="op">(</span><span class="va">s_intervento</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="va">n_intervento</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span></span>
<span>    <span class="op">(</span><span class="va">n_intervento</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="op">(</span><span class="va">s_controllo</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="va">n_controllo</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span></span>
<span>    <span class="op">(</span><span class="va">n_controllo</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">t_welch</span> <span class="op">&lt;-</span> <span class="va">differenza</span> <span class="op">/</span> <span class="va">se_welch</span></span>
<span><span class="va">p_welch</span> <span class="op">&lt;-</span> <span class="fl">2</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">pt</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">t_welch</span><span class="op">)</span>,</span>
<span>  df <span class="op">=</span> <span class="va">df_welch</span>,</span>
<span>  lower.tail <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">t_critico</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fl">0.975</span>, df <span class="op">=</span> <span class="va">df_welch</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ic_welch</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="va">differenza</span> <span class="op">-</span> <span class="va">t_critico</span> <span class="op">*</span> <span class="va">se_welch</span>,</span>
<span>  <span class="va">differenza</span> <span class="op">+</span> <span class="va">t_critico</span> <span class="op">*</span> <span class="va">se_welch</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  differenza <span class="op">=</span> <span class="va">differenza</span>,</span>
<span>  errore_standard <span class="op">=</span> <span class="va">se_welch</span>,</span>
<span>  t <span class="op">=</span> <span class="va">t_welch</span>,</span>
<span>  gradi_liberta <span class="op">=</span> <span class="va">df_welch</span>,</span>
<span>  valore_p <span class="op">=</span> <span class="va">p_welch</span>,</span>
<span>  limite_inferiore <span class="op">=</span> <span class="va">ic_welch</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>,</span>
<span>  limite_superiore <span class="op">=</span> <span class="va">ic_welch</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt;       differenza  errore_standard                t    gradi_liberta </span></span>
<span><span class="co">#&gt;        5.0000000        1.0316947        4.8463950       20.6446253 </span></span>
<span><span class="co">#&gt;         valore_p limite_inferiore limite_superiore </span></span>
<span><span class="co">#&gt;        0.0000901        2.8522224        7.1477776</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Otteniamo approssimativamente:</p>
<p><span class="math display">\[
\widehat{\Delta}=5.00,
\]</span></p>
<p><span class="math display">\[
IC_{95\%}=[2.85,\;7.15],
\]</span></p>
<p><span class="math display">\[
t(20.64)=4.85,
\qquad
p&lt;0.001.
\]</span></p>
<p>Il valore-<em>p</em> indica che, sotto l’ipotesi di differenza nulla e le altre assunzioni del test, una statistica almeno altrettanto estrema sarebbe rara.</p>
<p>Non è la probabilità che <span class="math inline">\(\Delta=0\)</span>.</p>
</section><section id="sec-freq-two-samples-pooled-example" class="level2" data-number="6.8"><h2 data-number="6.8" class="anchored" data-anchor-id="sec-freq-two-samples-pooled-example">
<span class="header-section-number">6.8</span> Il caso con varianza comune</h2>
<p>Per confronto, eseguiamo il test classico:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_pooled</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span></span>
<span>  <span class="va">benessere_intervento</span>,</span>
<span>  <span class="va">benessere_controllo</span>,</span>
<span>  alternative <span class="op">=</span> <span class="st">"two.sided"</span>,</span>
<span>  var.equal <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  conf.level <span class="op">=</span> <span class="fl">0.95</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">test_pooled</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Two Sample t-test</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; data:  benessere_intervento and benessere_controllo</span></span>
<span><span class="co">#&gt; t = 5, df = 22, p-value = 0.00008</span></span>
<span><span class="co">#&gt; alternative hypothesis: true difference in means is not equal to 0</span></span>
<span><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span><span class="co">#&gt;  2.86 7.14</span></span>
<span><span class="co">#&gt; sample estimates:</span></span>
<span><span class="co">#&gt; mean of x mean of y </span></span>
<span><span class="co">#&gt;      31.2      26.2</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In questi dati, numerosità e deviazioni standard sono simili, quindi i due test producono risultati quasi identici.</p>
<p>Questa somiglianza non dimostra che le varianze delle popolazioni siano uguali. Mostra soltanto che, per questo campione, l’assunzione aggiuntiva ha conseguenze numeriche limitate.</p>
</section><section id="sec-freq-two-samples-integrated" class="level2" data-number="6.9"><h2 data-number="6.9" class="anchored" data-anchor-id="sec-freq-two-samples-integrated">
<span class="header-section-number">6.9</span> Interpretare insieme le quantità</h2>
<section id="differenza-nella-scala-originale" class="level3" data-number="6.9.1"><h3 data-number="6.9.1" class="anchored" data-anchor-id="differenza-nella-scala-originale">
<span class="header-section-number">6.9.1</span> Differenza nella scala originale</h3>
<p>La differenza di 5 punti è la quantità più direttamente interpretabile:</p>
<blockquote class="blockquote">
<p>Nel campione, la media del gruppo intervento supera quella del gruppo controllo di 5 punti.</p>
</blockquote>
<p>La sua importanza dipende dalla scala, dall’affidabilità dello strumento e dal contesto.</p>
</section><section id="intervallo-di-confidenza" class="level3" data-number="6.9.2"><h3 data-number="6.9.2" class="anchored" data-anchor-id="intervallo-di-confidenza">
<span class="header-section-number">6.9.2</span> Intervallo di confidenza</h3>
<p>L’intervallo al 95% è:</p>
<p><span class="math display">\[
[2.85,\;7.15].
\]</span></p>
<p>Descrive la precisione della procedura frequentista. Non assegna il 95% di probabilità alla differenza vera entro questi estremi.</p>
<p>L’intervallo è utile anche per confrontare i dati con una soglia sostantiva. Se, per esempio, fossero necessari almeno 6 punti per una rilevanza pratica, l’intervallo mostrerebbe che i dati sono compatibili sia con differenze inferiori sia con differenze superiori a tale soglia.</p>
</section><section id="valore-p" class="level3" data-number="6.9.3"><h3 data-number="6.9.3" class="anchored" data-anchor-id="valore-p">
<span class="header-section-number">6.9.3</span> Valore-<em>p</em>
</h3>
<p>Il valore-<em>p</em> sintetizza l’incompatibilità con <span class="math inline">\(\Delta=0\)</span>. Non descrive la grandezza della differenza né la sua importanza.</p>
</section><section id="dimensione-delleffetto-standardizzata" class="level3" data-number="6.9.4"><h3 data-number="6.9.4" class="anchored" data-anchor-id="dimensione-delleffetto-standardizzata">
<span class="header-section-number">6.9.4</span> Dimensione dell’effetto standardizzata</h3>
<p>Una misura comune è il <span class="math inline">\(d\)</span> di Cohen:</p>
<p><span class="math display">\[
d
=
\frac{
\bar x_{\text{intervento}}
-
\bar x_{\text{controllo}}
}{
s_p
}.
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">s_pooled</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span></span>
<span>  <span class="op">(</span></span>
<span>    <span class="op">(</span><span class="va">n_intervento</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span> <span class="op">*</span> <span class="va">s_intervento</span><span class="op">^</span><span class="fl">2</span> <span class="op">+</span></span>
<span>      <span class="op">(</span><span class="va">n_controllo</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span> <span class="op">*</span> <span class="va">s_controllo</span><span class="op">^</span><span class="fl">2</span></span>
<span>  <span class="op">)</span> <span class="op">/</span></span>
<span>    <span class="op">(</span></span>
<span>      <span class="va">n_intervento</span> <span class="op">+</span></span>
<span>        <span class="va">n_controllo</span> <span class="op">-</span></span>
<span>        <span class="fl">2</span></span>
<span>    <span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">cohen_d</span> <span class="op">&lt;-</span> <span class="va">differenza</span> <span class="op">/</span> <span class="va">s_pooled</span></span>
<span></span>
<span><span class="va">correzione_hedges</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span></span>
<span>  <span class="fl">3</span> <span class="op">/</span></span>
<span>    <span class="op">(</span></span>
<span>      <span class="fl">4</span> <span class="op">*</span></span>
<span>        <span class="op">(</span></span>
<span>          <span class="va">n_intervento</span> <span class="op">+</span></span>
<span>            <span class="va">n_controllo</span></span>
<span>        <span class="op">)</span> <span class="op">-</span></span>
<span>        <span class="fl">9</span></span>
<span>    <span class="op">)</span></span>
<span></span>
<span><span class="va">hedges_g</span> <span class="op">&lt;-</span> <span class="va">correzione_hedges</span> <span class="op">*</span> <span class="va">cohen_d</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  cohen_d <span class="op">=</span> <span class="va">cohen_d</span>,</span>
<span>  hedges_g <span class="op">=</span> <span class="va">hedges_g</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt;  cohen_d hedges_g </span></span>
<span><span class="co">#&gt;     1.98     1.91</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Per questi dati:</p>
<p><span class="math display">\[
d\approx1.98,
\qquad
g\approx1.91.
\]</span></p>
<p><span class="math inline">\(g\)</span> di Hedges applica una correzione alla tendenza di <span class="math inline">\(d\)</span> a sovrastimare l’effetto standardizzato nei piccoli campioni.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="L'effetto standardizzato non sostituisce la differenza grezza">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Avviso</span>L’effetto standardizzato non sostituisce la differenza grezza
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(d\)</span> e <span class="math inline">\(g\)</span> dipendono anche dalla dispersione dei punteggi. Lo stesso cambiamento di 5 punti può produrre valori standardizzati differenti in popolazioni con variabilità diversa.</p>
<p>Quando la scala originale è interpretabile, è opportuno riportare sia la differenza grezza sia una misura standardizzata.</p>
</div>
</div>
</section></section><section id="sec-freq-two-samples-relevance" class="level2" data-number="6.10"><h2 data-number="6.10" class="anchored" data-anchor-id="sec-freq-two-samples-relevance">
<span class="header-section-number">6.10</span> Significatività, equivalenza e rilevanza pratica</h2>
<p>Un risultato significativo rispetto a zero non dimostra che l’effetto sia abbastanza grande da essere utile.</p>
<p>Un risultato non significativo, d’altra parte, non dimostra che i gruppi siano equivalenti. Per sostenere equivalenza occorrono:</p>
<ol type="1">
<li>una regione di differenze considerate praticamente trascurabili;</li>
<li>una procedura progettata per valutare quella regione;</li>
<li>dati sufficientemente precisi.</li>
</ol>
<p>La soglia di rilevanza dovrebbe essere motivata prima dell’analisi e collegata alla scala del fenomeno.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Tre domande differenti">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Tre domande differenti
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>
<strong>Esclusione dello zero:</strong> i dati sono incompatibili con <span class="math inline">\(\Delta=0\)</span> secondo il test?</li>
<li>
<strong>Precisione:</strong> quali differenze non vengono escluse dall’intervallo?</li>
<li>
<strong>Rilevanza:</strong> quali differenze cambierebbero una conclusione teorica o pratica?</li>
</ol>
<p>Rispondere alla prima non risponde automaticamente alle altre due.</p>
</div>
</div>
</section><section id="sec-freq-two-samples-causality" class="level2" data-number="6.11"><h2 data-number="6.11" class="anchored" data-anchor-id="sec-freq-two-samples-causality">
<span class="header-section-number">6.11</span> Dalla differenza osservata all’effetto causale</h2>
<p>Una differenza tra medie è sempre descrittiva del confronto definito. Diventa interpretabile come effetto causale soltanto sotto condizioni aggiuntive.</p>
<section id="studio-randomizzato" class="level3" data-number="6.11.1"><h3 data-number="6.11.1" class="anchored" data-anchor-id="studio-randomizzato">
<span class="header-section-number">6.11.1</span> Studio randomizzato</h3>
<p>Se i partecipanti sono assegnati casualmente ai gruppi, l’assegnazione è rispettata e non vi sono problemi sostanziali di attrito, aderenza o contaminazione, la differenza può sostenere un’interpretazione causale riferita alla popolazione e al trattamento definiti.</p>
</section><section id="gruppi-osservazionali" class="level3" data-number="6.11.2"><h3 data-number="6.11.2" class="anchored" data-anchor-id="gruppi-osservazionali">
<span class="header-section-number">6.11.2</span> Gruppi osservazionali</h3>
<p>Se i gruppi sono definiti da una caratteristica osservata, una differenza può dipendere da variabili confondenti.</p>
<p>Per esempio, una differenza tra persone che scelgono o non scelgono un trattamento non dimostra che il trattamento abbia prodotto la differenza. I gruppi possono differire già prima dell’intervento.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Il test t non crea causalità">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Avviso</span>Il test t non crea causalità
</div>
</div>
<div class="callout-body-container callout-body">
<p>Randomizzazione, identificazione e qualità del disegno giustificano una conclusione causale. Il valore-<em>p</em> non può compensare l’assenza di queste condizioni.</p>
</div>
</div>
</section></section><section id="sec-freq-two-samples-regression" class="level2" data-number="6.12"><h2 data-number="6.12" class="anchored" data-anchor-id="sec-freq-two-samples-regression">
<span class="header-section-number">6.12</span> Il test <em>t</em> come modello lineare</h2>
<p>Il confronto tra due gruppi può essere scritto come una regressione con un predittore dicotomico:</p>
<p><span class="math display">\[
Y_i
=
\alpha
+
\beta X_i
+
\varepsilon_i,
\]</span></p>
<p>dove:</p>
<ul>
<li>
<span class="math inline">\(X_i=0\)</span> indica il controllo;</li>
<li>
<span class="math inline">\(X_i=1\)</span> indica l’intervento.</li>
</ul>
<p>Allora:</p>
<p><span class="math display">\[
E(Y\mid X=0)=\alpha,
\]</span></p>
<p><span class="math display">\[
E(Y\mid X=1)=\alpha+\beta.
\]</span></p>
<p>La differenza è:</p>
<p><span class="math display">\[
E(Y\mid X=1)-E(Y\mid X=0)=\beta.
\]</span></p>
<p>Il coefficiente <span class="math inline">\(\beta\)</span> rappresenta quindi la stessa quantità:</p>
<p><span class="math display">\[
\beta
=
\mu_{\text{intervento}}
-
\mu_{\text{controllo}}.
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">modello_lineare</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span></span>
<span>  <span class="va">benessere</span> <span class="op">~</span> <span class="va">gruppo</span>,</span>
<span>  data <span class="op">=</span> <span class="va">dati_benessere</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">modello_lineare</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; lm(formula = benessere ~ gruppo, data = dati_benessere)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residuals:</span></span>
<span><span class="co">#&gt;    Min     1Q Median     3Q    Max </span></span>
<span><span class="co">#&gt;  -4.25  -2.25  -0.25   1.75   4.75 </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;                  Estimate Std. Error t value Pr(&gt;|t|)</span></span>
<span><span class="co">#&gt; (Intercept)         26.25       0.73   35.98  &lt; 2e-16</span></span>
<span><span class="co">#&gt; gruppoIntervento     5.00       1.03    4.85 0.000076</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Residual standard error: 2.53 on 22 degrees of freedom</span></span>
<span><span class="co">#&gt; Multiple R-squared:  0.516,  Adjusted R-squared:  0.494 </span></span>
<span><span class="co">#&gt; F-statistic: 23.5 on 1 and 22 DF,  p-value: 0.0000765</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">modello_lineare</span><span class="op">)</span></span>
<span><span class="co">#&gt;                  2.5 % 97.5 %</span></span>
<span><span class="co">#&gt; (Intercept)      24.74  27.76</span></span>
<span><span class="co">#&gt; gruppoIntervento  2.86   7.14</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Con varianza comune, il test del coefficiente del predittore è equivalente al test <em>t</em> classico per due gruppi.</p>
<p>Questa equivalenza è importante perché mostra che il test <em>t</em> non è un procedimento isolato. È il caso più semplice di una famiglia di modelli che può includere:</p>
<ul>
<li>più gruppi;</li>
<li>covariate;</li>
<li>interazioni;</li>
<li>strutture gerarchiche;</li>
<li>esiti non gaussiani.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Un ponte verso il progetto bayesiano">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Un ponte verso il progetto bayesiano
</div>
</div>
<div class="callout-body-container callout-body">
<p>Il Companion usa la stessa rappresentazione con un predittore 0–1:</p>
<ul>
<li>
<a href="https://ccaudek.github.io/utet-companion/chapters/calcolo/05_stan_two_means.html">Confrontare due medie con Stan</a>;</li>
<li>il capitolo 26, <em>Due gruppi: codifiche, differenze e rilevanza pratica</em>.</li>
</ul>
<p>Nel modello bayesiano, la distribuzione a posteriori di <span class="math inline">\(\beta\)</span> rappresenta direttamente l’incertezza sulla differenza tra le medie.</p>
</div>
</div>
</section><section id="sec-freq-two-samples-bayes" class="level2" data-number="6.13"><h2 data-number="6.13" class="anchored" data-anchor-id="sec-freq-two-samples-bayes">
<span class="header-section-number">6.13</span> Che cosa cambia nel modello bayesiano?</h2>
<p>Il confronto frequentista e quello bayesiano possono condividere:</p>
<ul>
<li>gli stessi dati;</li>
<li>lo stesso predittore dicotomico;</li>
<li>una verosimiglianza normale;</li>
<li>la stessa quantità bersaglio <span class="math inline">\(\Delta\)</span>;</li>
<li>modelli con dispersione comune o differente.</li>
</ul>
<p>Cambiano l’oggetto inferenziale immediato e il significato delle probabilità.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th>Domanda</th>
<th>Procedura frequentista</th>
<th>Modello bayesiano</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Quanto differiscono i gruppi?</td>
<td>Stima puntuale e intervallo di confidenza</td>
<td>Distribuzione a posteriori di <span class="math inline">\(\Delta\)</span>
</td>
</tr>
<tr class="even">
<td>Quanto è incompatibile lo zero?</td>
<td>Valore-<em>p</em> sotto <span class="math inline">\(H_0\)</span>
</td>
<td>Massa a posteriori rispetto a zero o confronto tra modelli</td>
</tr>
<tr class="odd">
<td>L’effetto supera una soglia pratica?</td>
<td>Intervallo, equivalenza o test dedicato</td>
<td>Probabilità a posteriori che <span class="math inline">\(\Delta\)</span> superi la soglia</td>
</tr>
<tr class="even">
<td>Il modello descrive adeguatamente i dati?</td>
<td>Diagnostica e controlli frequentisti</td>
<td>Controlli predittivi e confronto predittivo</td>
</tr>
</tbody>
</table>
<p>Nel modello bayesiano si possono calcolare quantità come:</p>
<p><span class="math display">\[
P(\Delta&gt;0\mid y)
\]</span></p>
<p>oppure:</p>
<p><span class="math display">\[
P(\Delta&gt;\delta_{\min}\mid y),
\]</span></p>
<p>dove <span class="math inline">\(\delta_{\min}\)</span> è una soglia sostantiva. Queste probabilità non sono valori-<em>p</em> e dipendono da prior, verosimiglianza e dati.</p>
<p>Il vantaggio di un’interpretazione diretta non elimina la necessità di controllare modello, misura, disegno e identificazione causale.</p>
</section><section id="sec-freq-two-samples-report" class="level2" data-number="6.14"><h2 data-number="6.14" class="anchored" data-anchor-id="sec-freq-two-samples-report">
<span class="header-section-number">6.14</span> Come riportare il risultato</h2>
<p>Un resoconto informativo dovrebbe includere:</p>
<ul>
<li>numerosità, media e deviazione standard dei gruppi;</li>
<li>ordine della differenza;</li>
<li>differenza grezza e intervallo;</li>
<li>test utilizzato;</li>
<li>statistica, gradi di libertà e valore-<em>p</em>;</li>
<li>dimensione dell’effetto;</li>
<li>interpretazione sostantiva e limiti del disegno.</li>
</ul>
<p>Per l’esempio:</p>
<blockquote class="blockquote">
<p>Il gruppo sottoposto all’intervento ha riportato un punteggio medio di benessere maggiore (<span class="math inline">\(M=31.25\)</span>, <span class="math inline">\(DS=2.83\)</span>, <span class="math inline">\(n=12\)</span>) rispetto al gruppo di controllo (<span class="math inline">\(M=26.25\)</span>, <span class="math inline">\(DS=2.18\)</span>, <span class="math inline">\(n=12\)</span>). La differenza intervento meno controllo è stata di 5.00 punti, <span class="math inline">\(IC\)</span> 95% [2.85, 7.15]. Il test <em>t</em> di Welch ha indicato incompatibilità con una differenza nulla, <span class="math inline">\(t(20.64)=4.85\)</span>, <span class="math inline">\(p&lt;.001\)</span>. La differenza standardizzata è risultata elevata nel campione, <span class="math inline">\(g=1.91\)</span>. L’interpretazione causale dipende dall’assegnazione e dalle altre caratteristiche del disegno.</p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled" title="Perché nominare Welch">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Perché nominare Welch
</div>
</div>
<div class="callout-body-container callout-body">
<p>Scrivere soltanto «test <em>t</em>» lascia implicita un’assunzione importante. Specificare «test <em>t</em> di Welch» comunica che non è stata imposta l’uguaglianza delle varianze.</p>
</div>
</div>
</section><section id="riflessioni-conclusive" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="riflessioni-conclusive">Riflessioni conclusive</h2>
<p>Il confronto tra due gruppi indipendenti conclude il percorso applicativo del modulo frequentista perché riunisce tutti gli elementi introdotti nei capitoli precedenti.</p>
<p>Abbiamo definito la differenza tra le medie come quantità bersaglio, distinto gruppi indipendenti e dati appaiati, confrontato il test classico con quello di Welch e interpretato congiuntamente:</p>
<ul>
<li>differenza grezza;</li>
<li>errore standard;</li>
<li>intervallo di confidenza;</li>
<li>valore-<em>p</em>;</li>
<li>dimensione dell’effetto.</li>
</ul>
<p>Il risultato di un test non esaurisce l’analisi. Occorre chiedersi quale differenza sia rilevante, quanto precisamente sia stimata, se il modello sia adeguato e se il disegno autorizzi un’interpretazione causale.</p>
<p>L’equivalenza tra test <em>t</em> e regressione con predittore dicotomico crea il ponte più naturale verso il progetto bayesiano. La domanda sostantiva rimane la stessa — quanto differiscono i gruppi? — ma l’incertezza viene rappresentata mediante la distribuzione a posteriori del coefficiente che codifica la differenza.</p>
<p>L’epilogo userà questo punto di arrivo per confrontare in modo complessivo controllo dell’errore, interpretazione dell’incertezza e workflow scientifico.</p>
</section><section id="esercizi" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="esercizi">Esercizi</h2>
<ol type="1">
<li><p>Qual è la differenza tra la quantità <span class="math inline">\(\Delta=\mu_1-\mu_0\)</span> e la stima <span class="math inline">\(\widehat{\Delta}=\bar X_1-\bar X_0\)</span>?</p></li>
<li><p>Perché un disegno prima-dopo sulle stesse persone non dovrebbe essere analizzato come confronto tra gruppi indipendenti?</p></li>
<li><p>Quale assunzione aggiuntiva distingue il test <em>t</em> classico dal test di Welch?</p></li>
<li><p>Perché non è consigliabile scegliere tra test classico e Welch sulla base di un test preliminare delle varianze?</p></li>
<li><p>Un intervallo per la differenza è [1.2, 6.8], mentre la soglia di rilevanza pratica è 5. Che cosa suggerisce l’intervallo?</p></li>
<li><p>Perché una differenza statisticamente significativa tra due gruppi osservazionali non dimostra un effetto causale?</p></li>
<li><p>Nel modello <span class="math inline">\(Y_i=\alpha+\beta X_i+\varepsilon_i\)</span>, con controllo codificato 0 e intervento codificato 1, che cosa rappresentano <span class="math inline">\(\alpha\)</span> e <span class="math inline">\(\beta\)</span>?</p></li>
<li><p>Qual è la differenza tra un valore-<em>p</em> piccolo per <span class="math inline">\(H_0:\Delta=0\)</span> e una probabilità a posteriori elevata per <span class="math inline">\(\Delta&gt;0\)</span>?</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzioni">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Soluzioni
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p><span class="math inline">\(\Delta\)</span> è la differenza tra le medie delle popolazioni o del modello. <span class="math inline">\(\widehat{\Delta}\)</span> è la differenza osservata tra le medie campionarie e varia da campione a campione.</p></li>
<li><p>Le due osservazioni della stessa persona sono dipendenti. Un test indipendente ignora l’abbinamento e usa un errore standard non coerente con il disegno.</p></li>
<li><p>Il test classico assume una varianza comune nelle due popolazioni. Welch permette varianze differenti e modifica errore standard e gradi di libertà.</p></li>
<li><p>La procedura risultante dipende da una decisione presa sugli stessi dati e ha proprietà inferenziali meno trasparenti. Welch può essere adottato direttamente senza imporre l’uguaglianza delle varianze.</p></li>
<li><p>I dati sono compatibili, secondo la procedura, sia con differenze inferiori sia con differenze superiori a 5. L’esclusione dello zero non consente di stabilire con precisione che la soglia pratica sia superata.</p></li>
<li><p>I gruppi possono differire per confondenti, selezione o condizioni precedenti all’esposizione. Il test quantifica una differenza, ma non identifica da solo il meccanismo che l’ha prodotta.</p></li>
<li><p><span class="math inline">\(\alpha\)</span> è la media del gruppo controllo. <span class="math inline">\(\beta\)</span> è la differenza intervento meno controllo.</p></li>
<li><p>Il valore-<em>p</em> riguarda risultati estremi sotto <span class="math inline">\(\Delta=0\)</span>. La probabilità a posteriori riguarda l’incertezza su <span class="math inline">\(\Delta\)</span> dopo avere combinato prior, modello e dati.</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Punti chiave">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Punti chiave
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Il confronto deve iniziare dalla definizione della differenza e del suo ordine.</li>
<li>Gruppi indipendenti, dati appaiati e misure ripetute richiedono strutture inferenziali diverse.</li>
<li>Il test di Welch non richiede una varianza comune ed è spesso una scelta predefinita adeguata.</li>
<li>L’indipendenza è soprattutto un’assunzione del disegno.</li>
<li>Differenza grezza, intervallo, valore-<em>p</em> e dimensione standardizzata comunicano informazioni diverse.</li>
<li>Un risultato significativo rispetto a zero non dimostra rilevanza pratica.</li>
<li>Un risultato non significativo non dimostra equivalenza.</li>
<li>Il test <em>t</em> non trasforma un confronto osservazionale in un effetto causale.</li>
<li>Il confronto tra due gruppi è equivalente a una regressione con predittore dicotomico.</li>
<li>Nel modello bayesiano, la posterior del coefficiente dicotomico rappresenta l’incertezza sulla differenza tra le medie.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Ambiente di sviluppo">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Ambiente di sviluppo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Le informazioni sull’ambiente R possono essere ottenute con:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.6.1 (2026-06-24)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin23</span></span>
<span><span class="co">#&gt; Running under: macOS Tahoe 26.5.2</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Zagreb</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          </span></span>
<span><span class="co">#&gt;  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         </span></span>
<span><span class="co">#&gt;  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        </span></span>
<span><span class="co">#&gt; [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      </span></span>
<span><span class="co">#&gt; [13] loo_2.10.1            rstan_2.32.7          StanHeaders_2.32.10  </span></span>
<span><span class="co">#&gt; [16] brms_2.23.0           Rcpp_1.1.2            sessioninfo_1.2.4    </span></span>
<span><span class="co">#&gt; [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    </span></span>
<span><span class="co">#&gt; [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          </span></span>
<span><span class="co">#&gt; [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         </span></span>
<span><span class="co">#&gt;  [4] S7_0.2.2              fastmap_1.2.0         tensorA_0.36.2.1     </span></span>
<span><span class="co">#&gt;  [7] digest_0.6.39         timechange_0.4.0      estimability_2.0.0   </span></span>
<span><span class="co">#&gt; [10] lifecycle_1.0.5       magrittr_2.0.5        compiler_4.6.1       </span></span>
<span><span class="co">#&gt; [13] rlang_1.3.0           tools_4.6.1           yaml_2.3.12          </span></span>
<span><span class="co">#&gt; [16] knitr_1.51            labeling_0.4.3        bridgesampling_1.2-1 </span></span>
<span><span class="co">#&gt; [19] htmlwidgets_1.6.4     pkgbuild_1.4.8        curl_7.1.0           </span></span>
<span><span class="co">#&gt; [22] RColorBrewer_1.1-3    abind_1.4-8           purrr_1.2.2          </span></span>
<span><span class="co">#&gt; [25] grid_4.6.1            stats4_4.6.1          xtable_1.8-8         </span></span>
<span><span class="co">#&gt; [28] inline_0.3.21         emmeans_2.0.4         scales_1.4.0         </span></span>
<span><span class="co">#&gt; [31] cli_3.6.6             mvtnorm_1.4-2         rmarkdown_2.31       </span></span>
<span><span class="co">#&gt; [34] generics_0.1.4        otel_0.2.0            RcppParallel_5.1.11-2</span></span>
<span><span class="co">#&gt; [37] cachem_1.1.0          stringr_1.6.0         parallel_4.6.1       </span></span>
<span><span class="co">#&gt; [40] vctrs_0.7.3           V8_8.2.0              Matrix_1.7-6         </span></span>
<span><span class="co">#&gt; [43] jsonlite_2.0.0        arrayhelpers_1.1-2    glue_1.8.1           </span></span>
<span><span class="co">#&gt; [46] codetools_0.2-20      distributional_0.8.1  lubridate_1.9.5      </span></span>
<span><span class="co">#&gt; [49] stringi_1.8.7         gtable_0.3.6          QuickJSR_1.10.0      </span></span>
<span><span class="co">#&gt; [52] pillar_1.11.1         htmltools_0.5.9       Brobdingnag_1.2-9    </span></span>
<span><span class="co">#&gt; [55] R6_2.6.1              textshaping_1.0.5     rprojroot_2.1.1      </span></span>
<span><span class="co">#&gt; [58] evaluate_1.0.5        lattice_0.22-9        backports_1.5.1      </span></span>
<span><span class="co">#&gt; [61] memoise_2.0.1         broom_1.0.13          snakecase_0.11.1     </span></span>
<span><span class="co">#&gt; [64] rstantools_2.6.0      coda_0.19-4.1         gridExtra_2.3.1      </span></span>
<span><span class="co">#&gt; [67] nlme_3.1-170          checkmate_2.3.4       xfun_0.60            </span></span>
<span><span class="co">#&gt; [70] pkgconfig_2.0.3</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:https?:)?//ccaudek\.github\.io/utet-prob/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/frequentist_inference/05_sample_size.html" class="pagination-link" aria-label="Dimensione campionaria, precisione e potenza">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Dimensione campionaria, precisione e potenza</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/epilogo/epilogo.html" class="pagination-link" aria-label="Conclusioni">
        <span class="nav-page-text">Conclusioni</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Inferenza frequentista in psicologia</strong> — Modulo del progetto UTET a supporto del manuale <em>Inferenza bayesiana in psicologia: Ragionare con l’incertezza</em>.</p>
</div>   
    <div class="nav-footer-center">

<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/utet-frequentista/blob/main/chapters/frequentist_inference/06_two_ind_samples.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/utet-frequentista/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div><div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Preferenze cookie</a></div></div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>