{
  "hash": "c4fbd6d7fb58c72fb91d80b9106f6e6a",
  "result": {
    "engine": "knitr",
    "markdown": "# Intervalli di confidenza {#sec-frequentism-confidence-intervals}\n\n::: {.callout-note title=\"In sintesi\"}\n**Da sapere**  Un intervallo di confidenza combina una stima puntuale e una misura della sua variabilità campionaria. Il livello di confidenza descrive la copertura della procedura sotto ripetizioni del campionamento e non assegna una probabilità al parametro nell'intervallo osservato.\n\n**Da saper fare**  Interpretare correttamente un intervallo di confidenza; distinguere copertura, precisione e validità; spiegare il ruolo di errore standard, valore critico e dimensione campionaria; confrontare intervalli di confidenza e intervalli di credibilità senza confonderli.\n:::\n\n## Introduzione {.unnumbered .unlisted}\n\nNel capitolo precedente abbiamo distinto **parametro**, **stimatore** e **stima**. Abbiamo inoltre visto che una stima puntuale, come una media campionaria, è incompleta se non viene accompagnata da una misura della sua precisione.\n\nL'intervallo di confidenza sviluppa questa idea. Parte dalla distribuzione campionaria dello stimatore e costruisce, intorno alla stima osservata, un intervallo mediante una procedura progettata per raggiungere una determinata frequenza di copertura.\n\nIl punto più delicato è interpretativo. Un intervallo di confidenza al 95% non significa che il parametro abbia il 95% di probabilità di trovarsi tra i due estremi osservati. Il 95% qualifica la procedura prima dell'osservazione dei dati: sotto il modello e il piano di campionamento assunti, il 95% degli intervalli prodotti in ripetizioni analoghe contiene il parametro vero.\n\n## Perché una stima puntuale non basta?\n\nSupponiamo di osservare una media campionaria pari a 24.8. Questo numero risponde alla domanda:\n\n> Quale valore ha assunto lo stimatore nel campione osservato?\n\nNon risponde però a una seconda domanda:\n\n> Quanto cambierebbe la stima se osservassimo un altro campione generato nelle stesse condizioni?\n\nDue studi possono ottenere la stessa media e avere precisioni molto diverse. L'intervallo di confidenza rende visibile questa seconda informazione, combinando:\n\n1. la stima puntuale;\n2. l'errore standard;\n3. un valore critico associato al livello di confidenza.\n\n::: {.callout-important title=\"Precisione, non garanzia di verità\"}\nUn intervallo stretto indica una bassa variabilità campionaria della procedura nelle condizioni assunte. Non garantisce che il campione sia rappresentativo, che la misura sia valida o che il modello sia corretto.\n\nUna stima può essere molto precisa e tuttavia sistematicamente fuorviante.\n:::\n\n::: {.callout-tip title=\"Prerequisiti\"}\nÈ utile avere letto:\n\n- @sec-freq-stime-parametri, per la distinzione tra parametro, stimatore, stima ed errore standard;\n- il capitolo [Dal campione all'evidenza](https://ccaudek.github.io/utet-prob/chapters/probability/13_from_sample_to_evidence.html), per il significato della distribuzione campionaria;\n- l'introduzione al modulo frequentista, per la distinzione tra probabilità della procedura e incertezza sul parametro.\n\nQui useremo questi concetti senza ripeterne la teoria probabilistica.\n:::\n\n## Panoramica del capitolo {.unnumbered .unlisted}\n\nIl capitolo procede in otto passaggi:\n\n1. introduce la forma generale di un intervallo di confidenza;\n2. deriva l'intervallo per una media con varianza nota;\n3. presenta l'intervallo *t* per una media con varianza ignota;\n4. calcola un esempio numerico in R;\n5. rende intuitiva la copertura mediante simulazione;\n6. discute i principali fraintendimenti;\n7. mostra che ampiezza e copertura dipendono da procedura e assunzioni;\n8. distingue l'intervallo di confidenza dall'intervallo di credibilità e prepara il passaggio ai test di ipotesi.\n\n::: {.callout-note title=\"Preparazione del notebook\"}\nPer eseguire gli esempi, prepara l'ambiente comune del progetto:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |>\n  source()\n```\n:::\n\n:::\n\n## Dalla stima all'intervallo {#sec-freq-from-point-to-interval}\n\nMolti intervalli di confidenza hanno la forma:\n\n$$\n\\text{stima}\n\\;\\pm\\;\n\\text{valore critico}\n\\times\n\\text{errore standard}.\n$$\n\nIl prodotto tra valore critico ed errore standard è il **margine di errore**.\n\nLa stima determina il centro dell'intervallo. L'errore standard descrive la variabilità campionaria dello stimatore. Il valore critico stabilisce quanto dobbiamo allontanarci dal centro per ottenere il livello di copertura desiderato.\n\nQuesta forma non è universale. Esistono intervalli asimmetrici, intervalli basati sulla verosimiglianza, intervalli bootstrap e procedure specifiche per proporzioni, varianze e coefficienti di regressione. Tuttavia, il caso della media rende visibile la logica fondamentale.\n\n## Caso ideale: media con varianza nota {#sec-freq-ci-known-variance}\n\nConsideriamo osservazioni indipendenti da una popolazione normale con media ignota $\\mu$ e deviazione standard nota $\\sigma$. La media campionaria ha distribuzione:\n\n$$\n\\bar X\n\\sim\n\\mathcal{N}\\!\\left(\n\\mu,\n\\frac{\\sigma^2}{n}\n\\right).\n$$\n\nDi conseguenza,\n\n$$\nZ\n=\n\\frac{\\bar X-\\mu}{\\sigma/\\sqrt n}\n\\sim\n\\mathcal{N}(0,1).\n$$\n\nPer un livello di confidenza del 95%:\n\n$$\nP(-1.96 \\le Z \\le 1.96)=0.95.\n$$\n\nSostituendo la definizione di $Z$ e riordinando la disuguaglianza:\n\n$$\nP\\!\\left(\n\\bar X-1.96\\frac{\\sigma}{\\sqrt n}\n\\le\n\\mu\n\\le\n\\bar X+1.96\\frac{\\sigma}{\\sqrt n}\n\\right)\n=\n0.95.\n$$\n\nPrima di osservare il campione, gli estremi sono variabili casuali perché dipendono da $\\bar X$. La procedura produce quindi un intervallo casuale con copertura 0.95.\n\nDopo aver osservato i dati, otteniamo due estremi numerici. Il parametro, nel modello frequentista, è fisso: l'intervallo osservato lo contiene oppure non lo contiene.\n\n::: {.callout-note title=\"Dove si trova la probabilità?\"}\nNell'espressione precedente, la probabilità riguarda gli estremi casuali dell'intervallo prima dell'osservazione dei dati. Non riguarda una distribuzione di probabilità assegnata a $\\mu$.\n:::\n\n## Caso usuale: media con varianza ignota {#sec-freq-ci-unknown-variance}\n\nNella ricerca psicologica, $\\sigma$ è quasi sempre ignota. La sostituiamo quindi con la deviazione standard campionaria $s$.\n\nSe le osservazioni sono indipendenti e provengono da una popolazione normale, la statistica\n\n$$\nT\n=\n\\frac{\\bar X-\\mu}{s/\\sqrt n}\n$$\n\nsegue esattamente una distribuzione *t* di Student con $n-1$ gradi di libertà:\n\n$$\nT\\sim t_{n-1}.\n$$\n\nL'intervallo bilaterale al livello $1-\\alpha$ è:\n\n$$\n\\bar X\n\\pm\nt_{1-\\alpha/2,\\;n-1}\n\\frac{s}{\\sqrt n}.\n$$\n\nLa distribuzione *t* ha code più pesanti della normale standard. Nei campioni piccoli, il valore critico è quindi più grande e l'intervallo più ampio. Al crescere dei gradi di libertà, la distribuzione *t* si avvicina alla normale standard.\n\n::: {.callout-warning title=\"Esatto e approssimato\"}\nL'intervallo *t* classico ha copertura esatta sotto indipendenza e normalità della popolazione.\n\nCon campioni grandi può essere usato come approssimazione anche in situazioni non perfettamente normali, ma la qualità dell'approssimazione dipende dalla forma della distribuzione, dalla presenza di valori estremi e dalla struttura di dipendenza. Un campione grande non rende irrilevante qualunque violazione.\n:::\n\n## Un esempio numerico {#sec-freq-ci-example-r}\n\nConsideriamo dieci punteggi di benessere psicologico:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npunteggi <- c(28, 22, 26, 18, 30, 24, 27, 17, 21, 25)\n\nn <- length(punteggi)\nmedia <- mean(punteggi)\ndev_std <- sd(punteggi)\nerrore_standard <- dev_std / sqrt(n)\n\nc(\n  media = media,\n  deviazione_standard = dev_std,\n  errore_standard = errore_standard,\n  n = n\n)\n#>               media deviazione_standard     errore_standard                   n \n#>               23.80                4.26                1.35               10.00\n```\n:::\n\n\nLa media osservata è 23.8, la deviazione standard campionaria è circa 4.26 e l'errore standard è circa 1.35.\n\nCalcoliamo manualmente l'intervallo di confidenza al 95%:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalpha <- 0.05\nt_star <- qt(1 - alpha / 2, df = n - 1)\nmargine_errore <- t_star * errore_standard\n\nlimite_inferiore <- media - margine_errore\nlimite_superiore <- media + margine_errore\n\nc(\n  t_critico = t_star,\n  margine_errore = margine_errore,\n  limite_inferiore = limite_inferiore,\n  limite_superiore = limite_superiore\n)\n#>        t_critico   margine_errore limite_inferiore limite_superiore \n#>             2.26             3.05            20.75            26.85\n```\n:::\n\n\nOtteniamo approssimativamente:\n\n$$\n23.8\n\\pm\n2.262\\times1.348\n=\n[20.75,\\;26.85].\n$$\n\nLa stessa procedura è disponibile in R:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(punteggi, conf.level = 0.95)\n#> \n#> \tOne Sample t-test\n#> \n#> data:  punteggi\n#> t = 18, df = 9, p-value = 3e-08\n#> alternative hypothesis: true mean is not equal to 0\n#> 95 percent confidence interval:\n#>  20.8 26.8\n#> sample estimates:\n#> mean of x \n#>      23.8\n```\n:::\n\n\n`t.test()` restituisce anche una statistica test e un valore-$p$. In questo capitolo usiamo soltanto l'intervallo; i test di ipotesi saranno introdotti nel capitolo successivo.\n\n::: {.callout-tip title=\"Come comunicare il risultato\"}\nUna formulazione appropriata è:\n\n> Nel campione, il punteggio medio di benessere è 23.8. L'intervallo di confidenza al 95% per la media, costruito con la procedura *t*, è [20.75, 26.85].\n\nÈ utile riportare anche unità di misura, numerosità campionaria e condizioni dell'analisi.\n\nDa evitare:\n\n> C'è il 95% di probabilità che la media vera sia compresa tra 20.75 e 26.85.\n:::\n\n## La logica della copertura {#sec-freq-coverage-logic}\n\nLa **copertura** è la proporzione di intervalli che contengono il parametro quando la procedura viene ripetuta secondo il modello e il piano di campionamento specificati.\n\nPer rendere visibile questa idea, simuliamo molti campioni da una popolazione normale con media nota e costruiamo un intervallo *t* per ciascun campione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\n\nmu_vero <- 50\nsigma_vera <- 10\nn <- 25\nn_simulazioni <- 1000\n\nintervalli <- replicate(n_simulazioni, {\n  campione <- rnorm(n, mean = mu_vero, sd = sigma_vera)\n  ic <- t.test(campione, conf.level = 0.95)$conf.int\n  c(inferiore = ic[1], superiore = ic[2])\n})\n\ncontiene_mu <- intervalli[\"inferiore\", ] <= mu_vero &\n  intervalli[\"superiore\", ] >= mu_vero\n\nmean(contiene_mu)\n#> [1] 0.948\n\nn_mostra <- 50\n\ndati_grafico <- data.frame(\n  campione = seq_len(n_mostra),\n  inferiore = intervalli[\"inferiore\", seq_len(n_mostra)],\n  superiore = intervalli[\"superiore\", seq_len(n_mostra)],\n  contiene = contiene_mu[seq_len(n_mostra)]\n)\n\nggplot(\n  dati_grafico,\n  aes(\n    x = campione,\n    y = inferiore,\n    yend = superiore,\n    linetype = contiene\n  )\n) +\n  geom_segment(aes(xend = campione), linewidth = 0.7) +\n  geom_hline(yintercept = mu_vero, linetype = \"dashed\") +\n  coord_flip() +\n  labs(\n    x = \"Campione simulato\",\n    y = \"Intervallo di confidenza\",\n    linetype = \"Contiene la media vera\"\n  )\n```\n\n::: {.cell-output-display}\n![Cinquanta intervalli di confidenza al 95% ottenuti da campioni ripetuti. La linea tratteggiata indica la media vera.](03_conf_interv_files/figure-pdf/fig-ci-coverage-1.png){#fig-ci-coverage fig-align='center' fig-pos='H' fig-alt='Cinquanta segmenti orizzontali rappresentano intervalli di confidenza; alcuni non attraversano la linea della media vera.' width=85%}\n:::\n:::\n\n\nNella simulazione, la copertura empirica oscilla intorno al 95%. Non deve risultare esattamente 0.95 in un numero finito di ripetizioni.\n\n@fig-ci-coverage mostra che alcuni intervalli non contengono il parametro. Il livello di confidenza non identifica quali siano. Dopo aver osservato un singolo intervallo, la proprietà di copertura non si trasforma in una probabilità riferita a quello specifico intervallo.\n\n::: {.callout-important title=\"Copertura nominale e copertura effettiva\"}\nIl 95% è una proprietà nominale della procedura sotto determinate assunzioni.\n\nSe il modello, l'indipendenza, il piano di campionamento o il metodo di calcolo non sono appropriati, la copertura effettiva può essere diversa dal valore nominale.\n:::\n\n## Interpretazioni corrette e fraintendimenti {#sec-freq-ci-misinterpretations}\n\n| Affermazione | Valutazione | Motivo |\n|---|---|---|\n| «La procedura produce intervalli che contengono il parametro nel 95% delle ripetizioni previste dal modello.» | Corretta | Descrive la copertura frequentista. |\n| «Il parametro ha il 95% di probabilità di trovarsi in questo intervallo.» | Scorretta | Il parametro è fisso nel modello frequentista; la probabilità riguarda la procedura. |\n| «Il 95% dei valori individuali si trova nell'intervallo.» | Scorretta | L'intervallo riguarda un parametro, non la dispersione dei punteggi individuali. |\n| «I valori centrali sono più probabili di quelli vicini agli estremi.» | Non giustificata | L'intervallo non è una distribuzione di probabilità sul parametro. |\n| «Un intervallo più stretto indica maggiore precisione campionaria, a parità di metodo e livello di confidenza.» | Corretta | L'ampiezza dipende dall'errore standard e dal valore critico. |\n| «Tutti i valori interni sono ugualmente plausibili.» | Non giustificata | La procedura non assegna probabilità o plausibilità ai singoli valori del parametro. |\n\nA volte un intervallo di confidenza viene descritto come insieme di valori **compatibili con i dati**. Questa espressione può essere utile, ma deve essere completata:\n\n> valori non esclusi dalla procedura, dato il modello, le assunzioni e il livello scelto.\n\nNon significa che tutti i valori interni siano ugualmente credibili, né che quelli esterni siano impossibili.\n\n## Che cosa determina l'ampiezza? {#sec-freq-ci-width}\n\n### Errore standard\n\nA parità di valore critico, un errore standard maggiore produce un intervallo più ampio. L'errore standard dipende dalla variabilità dei dati e dalla struttura dello stimatore.\n\n### Livello di confidenza\n\nAumentare il livello di confidenza richiede un valore critico più grande. Sullo stesso campione, un intervallo al 99% è quindi più ampio di uno al 95%, che a sua volta è più ampio di uno al 90%.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlivelli <- c(0.80, 0.90, 0.95, 0.99)\n\ndata.frame(\n  livello = livelli,\n  t_critico = qt(1 - (1 - livelli) / 2, df = n - 1)\n) |>\n  transform(\n    limite_inferiore =\n      media - t_critico * errore_standard,\n    limite_superiore =\n      media + t_critico * errore_standard,\n    ampiezza =\n      2 * t_critico * errore_standard\n  )\n#>   livello t_critico limite_inferiore limite_superiore ampiezza\n#> 1    0.80      1.32             22.0             25.6     3.55\n#> 2    0.90      1.71             21.5             26.1     4.61\n#> 3    0.95      2.06             21.0             26.6     5.57\n#> 4    0.99      2.80             20.0             27.6     7.54\n```\n:::\n\n\nUna copertura nominale più elevata viene ottenuta al prezzo di un intervallo più largo.\n\n### Dimensione campionaria\n\nNel caso elementare della media indipendente:\n\n$$\n\\operatorname{SE}(\\bar X)\n=\n\\frac{\\sigma}{\\sqrt n}.\n$$\n\nA parità di variabilità e metodo, quadruplicare $n$ dimezza l'errore standard. Per questo motivo ottenere intervalli molto più stretti richiede aumenti sostanziali della numerosità.\n\nL'aumento di $n$ riduce la variabilità campionaria, ma non corregge automaticamente:\n\n- campionamento distorto;\n- misurazione inadeguata;\n- dipendenza ignorata;\n- modello mal specificato.\n\n## Intervalli e validità del modello {#sec-freq-ci-assumptions}\n\nLa copertura non è una proprietà magica dei due estremi numerici. Dipende dall'intero procedimento:\n\n- definizione della popolazione;\n- disegno di campionamento o assegnazione;\n- stimatore usato;\n- formula dell'errore standard;\n- distribuzione di riferimento;\n- trattamento di dipendenza, eterogeneità e valori estremi.\n\nNel semplice intervallo *t* per una media, per esempio, l'indipendenza è essenziale. Se i dati provengono da studenti raggruppati in classi o da misure ripetute sulla stessa persona, la formula $s/\\sqrt n$ può sottostimare la variabilità dello stimatore.\n\n::: {.callout-warning title=\"Un intervallo ben calcolato può rispondere alla domanda sbagliata\"}\nLa copertura riguarda il parametro definito dal modello e dal processo di campionamento. Non garantisce che quel parametro corrisponda al costrutto psicologico che interessa realmente.\n\nPrecisione statistica e validità sostantiva devono essere valutate separatamente.\n:::\n\n## Intervalli di confidenza e intervalli di credibilità {#sec-freq-ci-vs-credible}\n\nI due strumenti possono produrre estremi numericamente simili, ma derivano da costruzioni differenti.\n\n| Aspetto | Intervallo di confidenza | Intervallo di credibilità |\n|---|---|---|\n| Oggetto probabilistico immediato | Intervallo casuale sotto campionamenti ripetuti | Parametro sotto la distribuzione a posteriori |\n| Significato del 95% | Copertura della procedura, sotto le assunzioni | Massa a posteriori contenuta nell'intervallo |\n| Dipendenza da una prior | Non nella procedura standard | Sì |\n| Dipendenza dal modello dei dati | Sì | Sì |\n| Interpretazione del singolo intervallo | Non assegna probabilità al parametro | Assegna probabilità a posteriori al parametro, condizionatamente a prior, modello e dati |\n\nUn intervallo di credibilità al 95% contiene il 95% della distribuzione a posteriori scelta. Questa interpretazione è diretta sul parametro, ma rimane condizionata alla prior, alla verosimiglianza e all'adeguatezza del modello.\n\n::: {.callout-important title=\"Non basta cambiare il nome\"}\nUn intervallo di confidenza non diventa un intervallo di credibilità perché viene interpretato in modo intuitivo. Allo stesso modo, un intervallo bayesiano non è automaticamente affidabile soltanto perché consente un'affermazione probabilistica sul parametro.\n\nEntrambi richiedono un modello adeguato e una comunicazione coerente con la procedura che li ha generati.\n:::\n\n## Dall'intervallo al test di ipotesi {#sec-freq-ci-to-hypothesis-testing}\n\nPer molte procedure standard, un intervallo bilaterale al livello $1-\\alpha$ è collegato al corrispondente test bilaterale di livello $\\alpha$.\n\nNel caso della media con test *t*:\n\n- se il valore ipotizzato $\\mu_0$ è fuori dall'intervallo al 95%, il test bilaterale di livello 0.05 rifiuta $H_0:\\mu=\\mu_0$;\n- se $\\mu_0$ è dentro l'intervallo, il test non rifiuta $H_0$ allo stesso livello.\n\nQuesta è una relazione tra procedure costruite in modo coerente. Non significa che i valori interni siano «veri» o che quelli esterni siano impossibili.\n\nIl capitolo successivo svilupperà la logica dei test, distinguendo:\n\n- ipotesi nulla e alternativa;\n- statistica test;\n- livello $\\alpha$;\n- valore-$p$;\n- errori di tipo I e II;\n- potenza.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nUn intervallo di confidenza collega una stima puntuale alla distribuzione campionaria dello stimatore. Il suo livello descrive la copertura della procedura sotto ripetizioni definite dal modello e dal disegno.\n\nLa distinzione più importante è tra:\n\n- la probabilità che una **procedura casuale** produca un intervallo contenente il parametro;\n- una probabilità assegnata al **parametro**, che non appartiene all'interpretazione frequentista standard.\n\nL'ampiezza dell'intervallo informa sulla precisione campionaria, ma non certifica rappresentatività, validità della misura o correttezza del modello. La copertura nominale è affidabile soltanto nella misura in cui la procedura e le sue assunzioni sono adeguate.\n\nQuesto capitolo completa il passaggio dalla stima puntuale all'inferenza intervallare. Il prossimo userà le stesse distribuzioni di riferimento per introdurre i test di ipotesi.\n\n## Esercizi {.unnumbered .unlisted}\n\n1. Che cosa aggiunge un intervallo di confidenza rispetto a una stima puntuale?\n\n2. Che cosa significa affermare che una procedura ha copertura del 95%?\n\n3. Perché non è corretto dire che il parametro ha il 95% di probabilità di trovarsi nell'intervallo osservato?\n\n4. Due studi riportano la stessa stima e lo stesso livello di confidenza. Il primo intervallo è molto più stretto. Che cosa puoi concludere e che cosa non puoi concludere?\n\n5. Perché quadruplicare la dimensione campionaria dimezza approssimativamente l'errore standard della media?\n\n6. Un intervallo al 99% è più ampio dell'intervallo al 95% costruito sugli stessi dati. Quale compromesso esprime questa differenza?\n\n7. Perché ignorare la dipendenza tra osservazioni può compromettere la copertura?\n\n8. Qual è la differenza fondamentale tra il 95% di un intervallo di confidenza e il 95% di un intervallo di credibilità?\n\n::: {.callout-tip title=\"Soluzioni\" collapse=\"true\"}\n1. Aggiunge informazione sulla precisione campionaria della procedura, combinando stima, errore standard e valore critico.\n\n2. Significa che, sotto il modello e il piano di campionamento assunti, il 95% degli intervalli costruiti in ripetizioni analoghe contiene il parametro vero.\n\n3. Dopo l'osservazione, gli estremi sono fissi e il parametro è trattato come fisso nel modello frequentista. Il 95% qualifica il comportamento della procedura prima dell'osservazione, non una distribuzione di probabilità sul parametro.\n\n4. Il primo studio ha maggiore precisione campionaria, a parità di metodo e assunzioni. Non puoi concludere, dai soli estremi, che la stima sia più accurata, che il campione sia più rappresentativo o che la misura sia più valida.\n\n5. L'errore standard della media è proporzionale a $1/\\sqrt n$. Sostituendo $4n$ a $n$, otteniamo $1/\\sqrt{4n}=1/(2\\sqrt n)$.\n\n6. Una copertura nominale più alta richiede un valore critico maggiore e quindi un intervallo più ampio. Si guadagna copertura procedurale e si perde precisione.\n\n7. La formula standard può trattare come informazione indipendente osservazioni che condividono fonti di variabilità. L'errore standard può risultare troppo piccolo e la copertura effettiva inferiore a quella nominale.\n\n8. Nel primo caso, il 95% descrive la frequenza di copertura della procedura. Nel secondo descrive la massa della distribuzione a posteriori contenuta nell'intervallo, condizionatamente a prior, modello e dati.\n:::\n\n::: {.callout-note title=\"Punti chiave\" collapse=\"true\"}\n- Un intervallo di confidenza combina stima, errore standard e valore critico.\n- Il livello di confidenza è una proprietà della procedura.\n- Il singolo intervallo osservato non assegna probabilità al parametro.\n- L'intervallo *t* classico è esatto sotto indipendenza e normalità.\n- La copertura effettiva può differire da quella nominale quando le assunzioni non sono adeguate.\n- Un intervallo stretto indica precisione campionaria, non necessariamente accuratezza o validità.\n- L'ampiezza aumenta con il livello di confidenza e diminuisce, in genere, con la dimensione campionaria.\n- Gli intervalli di confidenza e di credibilità possono essere numericamente simili ma hanno significati differenti.\n- Per procedure standard, intervalli e test bilaterali possono essere duali.\n:::\n\n::: {.callout-note title=\"Ambiente di sviluppo\" collapse=\"true\"}\nLe informazioni sull'ambiente R possono essere ottenute con:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.5.2\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.1            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.0           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.2              fastmap_1.2.0         tensorA_0.36.2.1     \n#>  [7] digest_0.6.39         timechange_0.4.0      estimability_2.0.0   \n#> [10] lifecycle_1.0.5       magrittr_2.0.5        compiler_4.6.1       \n#> [13] rlang_1.3.0           tools_4.6.1           yaml_2.3.12          \n#> [16] knitr_1.51            labeling_0.4.3        bridgesampling_1.2-1 \n#> [19] pkgbuild_1.4.8        curl_7.1.0            RColorBrewer_1.1-3   \n#> [22] abind_1.4-8           purrr_1.2.2           grid_4.6.1           \n#> [25] stats4_4.6.1          xtable_1.8-8          inline_0.3.21        \n#> [28] emmeans_2.0.4         scales_1.4.0          cli_3.6.6            \n#> [31] mvtnorm_1.4-2         rmarkdown_2.31        generics_0.1.4       \n#> [34] otel_0.2.0            RcppParallel_5.1.11-2 cachem_1.1.0         \n#> [37] stringr_1.6.0         parallel_4.6.1        vctrs_0.7.3          \n#> [40] V8_8.2.0              Matrix_1.7-6          jsonlite_2.0.0       \n#> [43] arrayhelpers_1.1-2    glue_1.8.1            codetools_0.2-20     \n#> [46] distributional_0.8.1  lubridate_1.9.5       stringi_1.8.7        \n#> [49] gtable_0.3.6          QuickJSR_1.10.0       pillar_1.11.1        \n#> [52] htmltools_0.5.9       Brobdingnag_1.2-9     R6_2.6.1             \n#> [55] textshaping_1.0.5     rprojroot_2.1.1       evaluate_1.0.5       \n#> [58] lattice_0.22-9        backports_1.5.1       memoise_2.0.1        \n#> [61] broom_1.0.13          snakecase_0.11.1      rstantools_2.6.0     \n#> [64] coda_0.19-4.1         gridExtra_2.3.1       nlme_3.1-170         \n#> [67] checkmate_2.3.4       xfun_0.60             pkgconfig_2.0.3\n```\n:::\n\n:::\n",
    "supporting": [
      "03_conf_interv_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}