{
  "hash": "270ec30ed935ed5b2c2264850f268407",
  "result": {
    "engine": "knitr",
    "markdown": "# Test t di Student per campioni indipendenti {#sec-freq-two-samples}\n\n::: {.callout-note appearance=\"minimal\"}\nIl [test t di Student](https://www.scientificamerican.com/article/how-the-guinness-brewery-invented-the-most-important-statistical-method-in/) per campioni indipendenti è uno strumento fondamentale nella ricerca psicologica. Consente di confrontare le medie di due gruppi e di valutare se la differenza osservata possa essere attribuita semplicemente alla variabilità campionaria oppure rifletta una reale differenza tra le popolazioni da cui i campioni provengono.\n:::\n\n::: callout-important\n\n## In questo capitolo imparerai a\n\n* eseguire un test t di Student per confrontare le medie di due gruppi indipendenti;\n* interpretare correttamente i risultati, includendo intervalli di confidenza e dimensione dell’effetto;\n* comprendere i limiti del test e le principali alternative.\n:::\n\n::: callout-tip\n\n## Prerequisiti\n\n* Conoscere la logica generale del test di ipotesi.\n* Leggere *Bayesian estimation supersedes the t test* [@kruschke2013bayesian].\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n```\n:::\n\n:::\n\n## Assunzioni del test\n\nNel confronto tra due gruppi indipendenti, il test $t$ di Student richiede che le osservazioni siano indipendenti tra loro, che ciascun gruppo provenga da una popolazione che può essere ragionevolmente approssimata con una distribuzione normale e che le varianze delle due popolazioni siano uguali. Quando quest’ultima condizione non è plausibile, si utilizza la variante proposta da Welch, che corregge la statistica test e i gradi di libertà senza richiedere omoschedasticità.\n\n## Formulazione del test\n\n### Ipotesi\n\nL’ipotesi nulla afferma che le due popolazioni abbiano la stessa media, cioè $H_0: \\mu_1 = \\mu_2$. L’ipotesi alternativa considera la possibilità che le medie differiscano, $H_1: \\mu_1 \\neq \\mu_2$.\n\n### Statistica test\n\nLa statistica t confronta la differenza tra le due medie con la variabilità attesa sotto l’ipotesi nulla. La formula è:\n\n$$\nt = \\frac{\\bar{X}_1 - \\bar{X}_2}{s_p \\sqrt{\\frac{1}{n_1} + \\frac{1}{n_2}}},\n$$\ndove $s_p$ è la deviazione standard pooled:\n\n$$\ns_p = \\sqrt{\\frac{(n_1 - 1)s_1^2 + (n_2 - 1)s_2^2}{n_1 + n_2 - 2}}.\n$$\n\nSotto l’ipotesi nulla, la statistica $t$ segue una distribuzione $t$ di Student con $n_1 + n_2 - 2$ gradi di libertà.\n\n## Esempio pratico\n\nConsideriamo un confronto tra il peso corporeo di un gruppo di donne e un gruppo di uomini.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npeso_donne <- c(38.9, 61.2, 73.3, 21.8, 63.4, 64.6, 48.4, 48.8, 48.5)\npeso_uomini <- c(67.8, 60, 63.4, 76, 89.4, 73.3, 67.3, 61.3, 62.4)\n\ncat(\"Donne:\\n\")\n#> Donne:\ncat(\"  Media:\", round(mean(peso_donne), 2), \"kg\\n\")\n#>   Media: 52.1 kg\ncat(\"  Dev. std:\", round(sd(peso_donne), 2), \"kg\\n\")\n#>   Dev. std: 15.6 kg\ncat(\"  n:\", length(peso_donne), \"\\n\\n\")\n#>   n: 9\n\ncat(\"Uomini:\\n\")\n#> Uomini:\ncat(\"  Media:\", round(mean(peso_uomini), 2), \"kg\\n\")\n#>   Media: 69 kg\ncat(\"  Dev. std:\", round(sd(peso_uomini), 2), \"kg\\n\")\n#>   Dev. std: 9.38 kg\ncat(\"  n:\", length(peso_uomini), \"\\n\")\n#>   n: 9\n```\n:::\n\n\n### Calcolo manuale\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn1 <- length(peso_donne)\nn2 <- length(peso_uomini)\n\ns_pool <- sqrt(((n1 - 1) * var(peso_donne) + (n2 - 1) * var(peso_uomini)) / \n               (n1 + n2 - 2))\n\nt_stat <- (mean(peso_donne) - mean(peso_uomini)) / \n          (s_pool * sqrt(1/n1 + 1/n2))\n\ndf <- n1 + n2 - 2\n\np_value <- 2 * pt(abs(t_stat), df = df, lower.tail = FALSE)\n\ncat(\"Deviazione standard pooled:\", round(s_pool, 2), \"\\n\")\n#> Deviazione standard pooled: 12.9\ncat(\"Statistica t:\", round(t_stat, 3), \"\\n\")\n#> Statistica t: -2.78\ncat(\"Gradi di libertà:\", df, \"\\n\")\n#> Gradi di libertà: 16\ncat(\"P-value:\", round(p_value, 4), \"\\n\")\n#> P-value: 0.0133\n```\n:::\n\n\n### Utilizzo di `t.test()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(peso_donne, peso_uomini, var.equal = TRUE)\n#> \n#> \tTwo Sample t-test\n#> \n#> data:  peso_donne and peso_uomini\n#> t = -3, df = 16, p-value = 0.01\n#> alternative hypothesis: true difference in means is not equal to 0\n#> 95 percent confidence interval:\n#>  -29.75  -4.03\n#> sample estimates:\n#> mean of x mean of y \n#>      52.1      69.0\n```\n:::\n\n\n### Test di Welch\n\nIl test di Welch è una variante del test $t$ di Student che non richiede l’uguaglianza delle varianze tra i due gruppi. Invece di stimare una varianza *pooled*, calcola la variabilità separatamente per ciascun gruppo e utilizza una formula adattiva per i gradi di libertà. Ciò rende il test più affidabile quando le varianze sono diverse o quando la dimensione dei campioni è sbilanciata. In R è l'impostazione predefinita.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(peso_donne, peso_uomini, var.equal = FALSE)\n#> \n#> \tWelch Two Sample t-test\n#> \n#> data:  peso_donne and peso_uomini\n#> t = -3, df = 13, p-value = 0.02\n#> alternative hypothesis: true difference in means is not equal to 0\n#> 95 percent confidence interval:\n#>  -30.0  -3.8\n#> sample estimates:\n#> mean of x mean of y \n#>      52.1      69.0\n```\n:::\n\n\n## Interpretazione dei risultati\n\nIl confronto mostra un valore-$p$ di circa, il che suggerisce che la differenza tra le medie osservate sarebbe difficilmente attribuibile alla sola variabilità campionaria, se si assume l’ipotesi nulla. Per un'interpretazione completa, è però necessario considerare anche l'intervallo di confidenza sulla differenza e la grandezza dell'effetto, che aiutano a valutare la rilevanza pratica del risultato.\n\n### Dimensione dell’effetto: $d$ di Cohen\n\nLa grandezza della differenza in unità di deviazione standard può essere espressa tramite il $d$ di Cohen:\n\n$$\nd = \\frac{\\bar{X}_1 - \\bar{X}_2}{s_p}.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncohens_d <- (mean(peso_donne) - mean(peso_uomini)) / s_pool\ncat(\"Cohen's d:\", round(cohens_d, 2), \"\\n\")\n#> Cohen's d: -1.31\n```\n:::\n\n\nUn valore pari a 1.31 indica una differenza molto ampia tra i gruppi.\n\n### Intervallo di confidenza per la differenza\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntest_result <- t.test(peso_donne, peso_uomini, var.equal = TRUE)\ncat(\"Differenza delle medie:\", round(test_result$estimate[1] - test_result$estimate[2], 2), \"kg\\n\")\n#> Differenza delle medie: -16.9 kg\ncat(\"IC al 95%: [\", round(test_result$conf.int[1], 2), \", \", \n    round(test_result$conf.int[2], 2), \"] kg\\n\")\n#> IC al 95%: [ -29.8 ,  -4.03 ] kg\n```\n:::\n\n\n## Come riportare i risultati\n\n### Versione sconsigliata\n\nUna formulazione che si limiti a riportare la sola significatività statistica fornisce un resoconto incompleto:\n\n> \"I risultati mostrano una differenza significativa tra i pesi medi delle donne e degli uomini ($t$(16) = −2.78, $p$ = 0.01).\"\n\n### Versione consigliata\n\nUna comunicazione completa è più trasparente e più informativa:\n\n> \"Il peso medio delle donne ($M$ = 52.1 kg, $DS$ = 15.6) risulta inferiore a quello degli uomini ($M$ = 69.0 kg, $DS$ = 9.0) di 16.9 kg ($IC$ 95%: [4.0, 29.8]). La differenza è associata a una dimensione dell’effetto molto ampia ($d$ = 1.31).\"\n\nQuesta forma integra statistiche descrittive, stima puntuale, intervallo di confidenza e grandezza dell’effetto, offrendo un quadro più completo.\n\n## Limiti del test $t$\n\nIl test t si fonda su assunzioni che, se violate, possono alterare l’affidabilità dei risultati. La procedura conduce inoltre a una decisione dicotomica basata su una soglia arbitraria e non consente di quantificare l’evidenza empirica a favore dell’ipotesi nulla. La sensibilità alla dimensione campionaria è marcata: con campioni molto grandi, differenze minime risultano rilevabili; con campioni piccoli, differenze sostanziali possono non emergere.\n\n## L’alternativa bayesiana\n\nL’approccio bayesiano, come discusso da @kruschke2013bayesian, rappresenta una valida alternativa. Fornisce distribuzioni posteriori complete, consente di esprimere direttamente le probabilità delle ipotesi, integra le informazioni pregresse, gestisce gli outlier con modelli più flessibili e permette di quantificare in modo simmetrico l’evidenza a favore di ciascuna ipotesi tramite il fattore di Bayes.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIl test $t$ di Student è una procedura statistica ampiamente utilizzata in ambito frequentista per il confronto delle medie tra due gruppi. La sua utilità pratica viene migliorata quando l’esito del test viene interpretato in modo integrato, affiancando al valore di significatività statistica l’analisi degli intervalli di confidenza e la stima dell’entità dell’effetto. Questo approccio consente una valutazione più completa che distingue la rilevanza pratica dalla mera significatività campionaria.\n\nLa struttura decisionale del test, di tipo dicotomico e basata su soglie arbitrarie, presenta dei limiti di rigidità che sono stati ampiamente discussi in letteratura. Queste criticità, insieme all'interpretazione spesso ambigua del valore-$p$, evidenziano la necessità di integrare o affiancare a questo approccio metodologie statistiche che forniscano una quantificazione più diretta e informativa dell'incertezza. Di conseguenza, l'adozione di paradigmi alternativi, in particolare quello bayesiano, rappresenta una risposta metodologicamente migliore e concettualmente più solida.\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.5.2 (2025-10-31)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Tahoe 26.1\n#> \n#> Matrix products: default\n#> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] pillar_1.11.1         tinytable_0.15.1      patchwork_1.3.2      \n#>  [4] ggdist_3.3.3          tidybayes_3.0.7       bayesplot_1.14.0     \n#>  [7] ggplot2_4.0.1         reliabilitydiag_0.2.1 priorsense_1.2.0     \n#> [10] posterior_1.6.1       loo_2.8.0             rstan_2.32.7         \n#> [13] StanHeaders_2.32.10   brms_2.23.0           Rcpp_1.1.0           \n#> [16] sessioninfo_1.2.3     conflicted_1.2.0      janitor_2.2.1        \n#> [19] matrixStats_1.5.0     modelr_0.1.11         tibble_3.3.0         \n#> [22] dplyr_1.1.4           tidyr_1.3.1           rio_1.2.4            \n#> [25] here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.1              fastmap_1.2.0         TH.data_1.1-5        \n#>  [7] tensorA_0.36.2.1      digest_0.6.39         timechange_0.3.0     \n#> [10] estimability_1.5.1    lifecycle_1.0.4       survival_3.8-3       \n#> [13] magrittr_2.0.4        compiler_4.5.2        rlang_1.1.6          \n#> [16] tools_4.5.2           knitr_1.50            bridgesampling_1.2-1 \n#> [19] htmlwidgets_1.6.4     curl_7.0.0            pkgbuild_1.4.8       \n#> [22] RColorBrewer_1.1-3    abind_1.4-8           multcomp_1.4-29      \n#> [25] withr_3.0.2           purrr_1.2.0           grid_4.5.2           \n#> [28] stats4_4.5.2          colorspace_2.1-2      xtable_1.8-4         \n#> [31] inline_0.3.21         emmeans_2.0.0         scales_1.4.0         \n#> [34] MASS_7.3-65           cli_3.6.5             mvtnorm_1.3-3        \n#> [37] rmarkdown_2.30        ragg_1.5.0            generics_0.1.4       \n#> [40] RcppParallel_5.1.11-1 cachem_1.1.0          stringr_1.6.0        \n#> [43] splines_4.5.2         parallel_4.5.2        vctrs_0.6.5          \n#> [46] V8_8.0.1              Matrix_1.7-4          sandwich_3.1-1       \n#> [49] jsonlite_2.0.0        arrayhelpers_1.1-0    systemfonts_1.3.1    \n#> [52] glue_1.8.0            codetools_0.2-20      distributional_0.5.0 \n#> [55] lubridate_1.9.4       stringi_1.8.7         gtable_0.3.6         \n#> [58] QuickJSR_1.8.1        htmltools_0.5.9       Brobdingnag_1.2-9    \n#> [61] R6_2.6.1              textshaping_1.0.4     rprojroot_2.1.1      \n#> [64] evaluate_1.0.5        lattice_0.22-7        backports_1.5.0      \n#> [67] memoise_2.0.1         broom_1.0.11          snakecase_0.11.1     \n#> [70] rstantools_2.5.0      gridExtra_2.3         coda_0.19-4.1        \n#> [73] nlme_3.1-168          checkmate_2.3.3       xfun_0.54            \n#> [76] zoo_1.8-14            pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n\n",
    "supporting": [
      "06_two_ind_samples_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}