{
  "hash": "53e113e805e7821bd7f1846557671d78",
  "result": {
    "engine": "knitr",
    "markdown": "# Confrontare due gruppi indipendenti {#sec-freq-two-samples}\n\n::: {.callout-note appearance=\"minimal\"}\n\nIl confronto tra due gruppi indipendenti è una delle situazioni più comuni nella ricerca psicologica: un gruppo sperimentale viene messo a confronto con un gruppo di controllo, due condizioni di trattamento vengono messe a confronto o si confrontano sottogruppi definiti da una caratteristica osservata.\n\nNel quadro frequentista, il test *t* per campioni indipendenti risponde a una domanda specifica:\n\n> Se, nella popolazione, le due medie fossero uguali, quanto sarebbe sorprendente osservare una differenza almeno grande quanto quella trovata nel campione?\n\nTale domanda non coincide con la probabilità che le due medie siano uguali né con la probabilità che un trattamento funzioni. Il test *t* è una procedura che permette di valutare la compatibilità dei dati con un modello nullo e di controllare gli errori decisionali nel lungo periodo.\n\n:::\n\n::: callout-important\n## In questo capitolo imparerai a\n\n- riconoscere quando è appropriato un confronto tra due gruppi indipendenti;\n- formulare ipotesi nulla e ipotesi alternativa per il test *t*;\n- distinguere il test *t* classico dal test *t* di Welch;\n- interpretare insieme differenza tra medie, intervallo di confidenza, valore-*p* e dimensione dell'effetto;\n- riportare i risultati in modo completo, evitando una lettura basata solo sulla significatività statistica;\n- comprendere quali domande restano aperte e saranno affrontate in modo più diretto dall'inferenza bayesiana.\n:::\n\n::: callout-tip\n## Prerequisiti\n\nPer seguire questo capitolo è utile aver letto:\n\n- il capitolo su stime, stimatori e stima puntuale;\n- il capitolo sugli intervalli di confidenza;\n- il capitolo sui test di ipotesi e valore-*p*;\n- il capitolo sulla numerosità campionaria, errore e potenza.\n\nIl capitolo applica questi concetti a un caso concreto. Non introduce una nuova filosofia dell'inferenza, ma mostra come i diversi elementi del ragionamento frequentista si combinino in una procedura ampiamente utilizzata nella letteratura psicologica.\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n```\n:::\n\n:::\n\n## Perché confrontare due gruppi\n\nImmaginiamo uno studio in cui si valuta l'efficacia di un breve intervento di regolazione emotiva. Un gruppo di studenti riceve l'intervento, mentre un secondo gruppo segue una condizione di controllo. Al termine dello studio, tutti i partecipanti compilano una scala di benessere psicologico.\n\nIl ricercatore osserva due medie campionarie:\n\n$$\n\\bar{x}_1 \\quad \\text{e} \\quad \\bar{x}_2.\n$$\n\nLa differenza osservata è:\n\n$$\n\\bar{x}_1 - \\bar{x}_2.\n$$\n\nQuesta differenza è una **stima puntuale** della differenza tra le medie delle popolazioni:\n\n$$\n\\mu_1 - \\mu_2.\n$$\n\nTuttavia, come abbiamo visto nei capitoli precedenti, una stima puntuale non è sufficiente. Due campioni estratti dalla stessa popolazione possono produrre medie diverse, anche quando non esiste alcuna differenza reale tra i gruppi. Per questo motivo, il confronto tra due gruppi richiede sempre tre componenti:\n\n1. una **stima** della differenza osservata;\n2. una misura dell'**incertezza** associata a quella stima;\n3. una procedura per valutare la **compatibilità** dei dati con l'ipotesi nulla.\n\nIl test *t* per campioni indipendenti combina questi elementi in una procedura frequentista standard.\n\n## Il modello inferenziale del test *t*\n\n### Ipotesi nulla e ipotesi alternativa\n\nNel confronto tra due gruppi, l'ipotesi nulla afferma di solito che le due popolazioni abbiano la stessa media:\n\n$$\nH_0: \\mu_1 = \\mu_2.\n$$\n\nIn modo equivalente:\n\n$$\nH_0: \\mu_1 - \\mu_2 = 0.\n$$\n\nL'ipotesi alternativa può essere bidirezionale:\n\n$$\nH_1: \\mu_1 - \\mu_2 \\neq 0,\n$$\noppure direzionale:\n\n$$\nH_1: \\mu_1 - \\mu_2 > 0\n$$\noppure\n\n$$\nH_1: \\mu_1 - \\mu_2 < 0.\n$$\n\nIn un contesto introduttivo, è preferibile partire dal test bidirezionale, in quanto evita di introdurre una direzione dell'effetto dopo aver osservato i dati.\n\n### La statistica test\n\nLa logica del test *t* è semplice: la differenza osservata tra le medie viene confrontata con la variabilità che ci aspetteremmo se l'ipotesi nulla fosse vera.\n\nIn forma generale:\n\n$$\nt = \\frac{\\text{differenza osservata}}{\\text{errore standard della differenza}}.\n$$\n\nNel caso del test *t* classico con varianze uguali, la statistica è:\n\n$$\nt = \\frac{\\bar{X}_1 - \\bar{X}_2}{s_p \\sqrt{\\frac{1}{n_1} + \\frac{1}{n_2}}},\n$$\ndove $s_p$ è la deviazione standard pooled:\n\n$$\ns_p = \\sqrt{\\frac{(n_1 - 1)s_1^2 + (n_2 - 1)s_2^2}{n_1 + n_2 - 2}}.\n$$\n\nSotto $H_0$, e se le assunzioni del modello sono ragionevoli, questa statistica segue una distribuzione *t* di Student con:\n\n$$\ndf = n_1 + n_2 - 2\n$$\ngradi di libertà.\n\n::: callout-note\n## Una formula già familiare\n\nLa struttura del test *t* non è nuova. Si tratta della stessa logica vista nel test per una media:\n\n$$\n\\text{statistica test} = \\frac{\\text{stima} - \\text{valore atteso sotto } H_0}{\\text{errore standard}}.\n$$\n\nNel confronto tra due gruppi, la stima è la differenza tra le due medie. Il denominatore misura quanto tale differenza può variare da un campione all'altro quando $H_0$ è vera.\n:::\n\n## Assunzioni del confronto tra due gruppi\n\nPer interpretare correttamente il test, è necessario chiedersi se il modello sia plausibile per i dati osservati e per il disegno dello studio.\n\n### Indipendenza delle osservazioni\n\nLe osservazioni devono essere indipendenti sia all'interno di ciascun gruppo sia tra i gruppi. Questa è soprattutto un'assunzione di **disegno**: dipende da come sono stati reclutati i partecipanti e da come è stato condotto lo studio.\n\nAd esempio, se più osservazioni provengono dagli stessi partecipanti, da coppie, da classi scolastiche o da terapeuti comuni, l'indipendenza può essere violata. In questi casi, un semplice test *t* per campioni indipendenti potrebbe non essere adeguato.\n\n### Variabile quantitativa\n\nIl test *t* confronta le medie. La variabile dipendente dovrebbe quindi essere quantitativa o trattata come approssimativamente quantitativa. In psicologia, questo accade spesso con i punteggi delle scale, i tempi di risposta, i punteggi clinici o gli indici compositi.\n\n### Forma della distribuzione\n\nIl test *t* assume che, in ciascun gruppo, la variabile sia approssimativamente normale nella popolazione. In pratica, il test è spesso abbastanza robusto di fronte a deviazioni moderate dalla normalità, soprattutto quando i campioni non sono molto piccoli e non ci sono outlier estremi.\n\n### Uguaglianza delle varianze\n\nIl test *t* classico presuppone che le due popolazioni abbiano la stessa varianza. Quando questa assunzione non è plausibile, è preferibile utilizzare il **test *t* di Welch**, che non richiede varianze uguali e modifica i gradi di libertà.\n\nIn R, la funzione `t.test()` usa per impostazione predefinita il test di Welch. Questa scelta è spesso consigliabile nella pratica applicata.\n\n::: callout-tip\n## Regola pratica\n\nNel lavoro applicato, il test di Welch è spesso una buona scelta predefinita per il confronto tra due gruppi indipendenti. Il test classico con varianze uguali richiede un'ulteriore assunzione che non sempre è giustificata.\n:::\n\n## Un esempio guidato\n\nConsideriamo uno studio simulato sul benessere psicologico. Un gruppo di studenti segue un breve intervento di regolazione emotiva, mentre un secondo gruppo segue una condizione di controllo. Il punteggio finale viene misurato su una scala in cui i valori più alti indicano un maggiore benessere.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbenessere_intervento <- c(27, 31, 29, 33, 35, 30, 32, 28, 34, 31, 36, 29)\nbenessere_controllo  <- c(24, 26, 28, 25, 29, 27, 23, 30, 26, 25, 28, 24)\n\ncat(\"Gruppo intervento:\\n\")\n#> Gruppo intervento:\ncat(\"  Media:\", round(mean(benessere_intervento), 2), \"\\n\")\n#>   Media: 31.2\ncat(\"  Deviazione standard:\", round(sd(benessere_intervento), 2), \"\\n\")\n#>   Deviazione standard: 2.83\ncat(\"  n:\", length(benessere_intervento), \"\\n\\n\")\n#>   n: 12\n\ncat(\"Gruppo controllo:\\n\")\n#> Gruppo controllo:\ncat(\"  Media:\", round(mean(benessere_controllo), 2), \"\\n\")\n#>   Media: 26.2\ncat(\"  Deviazione standard:\", round(sd(benessere_controllo), 2), \"\\n\")\n#>   Deviazione standard: 2.18\ncat(\"  n:\", length(benessere_controllo), \"\\n\")\n#>   n: 12\n```\n:::\n\n\nLa prima cosa da fare non è calcolare il valore-*p*, ma osservare le stime descrittive. Il gruppo di intervento presenta una media più alta rispetto al gruppo di controllo. La domanda inferenziale è se questa differenza sia abbastanza grande rispetto alla variabilità attesa da risultare poco compatibile con $H_0$.\n\n### Visualizzazione descrittiva\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\ndati_benessere <- data.frame(\n  gruppo = rep(c(\"Intervento\", \"Controllo\"), each = 12),\n  benessere = c(benessere_intervento, benessere_controllo)\n)\n\nggplot(dati_benessere, aes(x = gruppo, y = benessere)) +\n  geom_boxplot(width = 0.45, alpha = 0.6, outlier.shape = NA) +\n  geom_jitter(width = 0.08, alpha = 0.8, size = 2) +\n  stat_summary(fun = mean, geom = \"point\", shape = 18, size = 4) +\n  labs(\n    title = \"Punteggi di benessere nei due gruppi\",\n    subtitle = \"Il rombo indica la media campionaria\",\n    x = \"Gruppo\",\n    y = \"Punteggio di benessere\"\n  )\n```\n\n::: {.cell-output-display}\n![](06_two_ind_samples_files/figure-pdf/unnamed-chunk-3-1.png){fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\nLa visualizzazione aiuta a vedere insieme posizione, variabilità e possibili valori anomali. Tale ispezione non sostituisce il test, ma rende l'interpretazione più trasparente.\n\n## Il test *t* classico\n\nCalcoliamo prima il test *t* nella versione classica con varianze uguali.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn1 <- length(benessere_intervento)\nn2 <- length(benessere_controllo)\n\nm1 <- mean(benessere_intervento)\nm2 <- mean(benessere_controllo)\n\ns1 <- sd(benessere_intervento)\ns2 <- sd(benessere_controllo)\n\ns_pool <- sqrt(((n1 - 1) * s1^2 + (n2 - 1) * s2^2) / (n1 + n2 - 2))\nse_diff <- s_pool * sqrt(1/n1 + 1/n2)\n\nt_stat <- (m1 - m2) / se_diff\ndf <- n1 + n2 - 2\np_value <- 2 * pt(abs(t_stat), df = df, lower.tail = FALSE)\n\ncat(\"Differenza tra medie:\", round(m1 - m2, 2), \"\\n\")\n#> Differenza tra medie: 5\ncat(\"Errore standard della differenza:\", round(se_diff, 2), \"\\n\")\n#> Errore standard della differenza: 1.03\ncat(\"Statistica t:\", round(t_stat, 3), \"\\n\")\n#> Statistica t: 4.85\ncat(\"Gradi di libertà:\", df, \"\\n\")\n#> Gradi di libertà: 22\ncat(\"Valore-p:\", round(p_value, 4), \"\\n\")\n#> Valore-p: 0.0001\n```\n:::\n\n\nIl valore-*p* va letto in modo condizionale: indica quanto sarebbero rari risultati almeno così estremi se, nella popolazione, le due medie fossero uguali e se il modello del test fosse appropriato.\n\n### Uso di `t.test()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt_classico <- t.test(benessere_intervento, benessere_controllo, var.equal = TRUE)\nt_classico\n#> \n#> \tTwo Sample t-test\n#> \n#> data:  benessere_intervento and benessere_controllo\n#> t = 5, df = 22, p-value = 0.00008\n#> alternative hypothesis: true difference in means is not equal to 0\n#> 95 percent confidence interval:\n#>  2.86 7.14\n#> sample estimates:\n#> mean of x mean of y \n#>      31.2      26.2\n```\n:::\n\n\nIl risultato riporta la statistica test, i gradi di libertà, il valore-*p*, la differenza tra le medie e un intervallo di confidenza per tale differenza.\n\n## Il test *t* di Welch\n\nNella pratica, spesso è preferibile utilizzare il test di Welch, che non richiede l'uguaglianza delle varianze. In R, questa è l'impostazione predefinita di `t.test()`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt_welch <- t.test(benessere_intervento, benessere_controllo)\nt_welch\n#> \n#> \tWelch Two Sample t-test\n#> \n#> data:  benessere_intervento and benessere_controllo\n#> t = 5, df = 21, p-value = 0.00009\n#> alternative hypothesis: true difference in means is not equal to 0\n#> 95 percent confidence interval:\n#>  2.85 7.15\n#> sample estimates:\n#> mean of x mean of y \n#>      31.2      26.2\n```\n:::\n\n\nSe le varianze dei gruppi sono simili, i risultati del test classico e del test di Welch sono molto simili. Se invece le varianze o le numerosità dei gruppi sono molto diverse, il test di Welch è più prudente.\n\n::: callout-note\n## Quale test riportare?\n\nPer molti studi applicati, è ragionevole riportare il test di Welch, specificando che l'uguaglianza delle varianze non è stata assunta. Il test classico con varianze uguali può essere utilizzato quando tale assunzione è giustificata dal disegno dello studio o da ragioni sostanziali.\n:::\n\n## Interpretare i risultati oltre il valore-*p*\n\nUn confronto tra due gruppi non dovrebbe essere riassunto solo dicendo se il risultato è \"significativo\" o \"non significativo\". Una lettura più informativa dovrebbe integrare quattro elementi:\n\n1. la **differenza osservata** tra le medie;\n2. l'**intervallo di confidenza** per la differenza;\n3. il **valore-*p***;\n4. la **dimensione dell'effetto**.\n\n### Differenza tra medie e intervallo di confidenza\n\nL'intervallo di confidenza descrive la precisione della stima della differenza tra le medie.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndiff_medie <- m1 - m2\nic_diff <- t_welch$conf.int\n\ncat(\"Differenza tra medie:\", round(diff_medie, 2), \"\\n\")\n#> Differenza tra medie: 5\ncat(\"IC 95%:\", \"[\", round(ic_diff[1], 2), \",\", round(ic_diff[2], 2), \"]\\n\")\n#> IC 95%: [ 2.85 , 7.15 ]\n```\n:::\n\n\nIn termini frequentisti, un intervallo di confidenza al 95% è costruito con una procedura che, nel lungo periodo, contiene il valore vero nel 95% dei campioni ripetuti. Ciò non significa che vi sia il 95% di probabilità che il valore vero cada nell'intervallo osservato.\n\n### Dimensione dell'effetto\n\nLa dimensione dell'effetto aiuta a distinguere la significatività statistica dalla rilevanza sostantiva. Nel confronto tra due medie, una misura comune è il $d$ di Cohen:\n\n$$\nd = \\frac{\\bar{x}_1 - \\bar{x}_2}{s_p}.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncohens_d <- diff_medie / s_pool\ncat(\"Cohen's d:\", round(cohens_d, 2), \"\\n\")\n#> Cohen's d: 1.98\n```\n:::\n\n\nQuesta quantità esprime la differenza tra i gruppi in unità di deviazione standard pooled. È una misura descrittiva standardizzata utile, ma non deve essere interpretata in modo meccanico. Un effetto piccolo può essere importante in alcuni contesti clinici o educativi, mentre un effetto grande può essere poco rilevante se riguarda una misura secondaria o un campione non rappresentativo.\n\n::: callout-warning\n## Significativo non significa importante\n\nUn test può risultare statisticamente significativo anche quando la differenza è trascurabile sul piano teorico o pratico, se il campione è molto grande. Al contrario, un risultato non significativo può dipendere da una bassa potenza e non dimostra che le due popolazioni siano uguali.\n:::\n\n## Come riportare il risultato\n\nUna comunicazione trasparente dovrebbe evitare sia l'eccesso di formule sia la riduzione del risultato al solo valore-*p*.\n\n### Formulazione incompleta\n\n> Il gruppo di intervento ha ottenuto punteggi significativamente più alti rispetto al gruppo di controllo, $p < .05$.\n\nQuesta frase è incompleta: non specifica l'entità della differenza, la precisione della stima e il metodo utilizzato.\n\n### Formulazione consigliata\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\n  \"Il gruppo sottoposto all'intervento ha riportato un punteggio medio di \", round(m1, 2),\n  \" (DS = \", round(s1, 2), \"), mentre il gruppo controllo ha riportato un punteggio medio di \",\n  round(m2, 2), \" (DS = \", round(s2, 2), \"). \",\n  \"La differenza media è pari a \", round(diff_medie, 2),\n  \" punti, IC 95% [\", round(ic_diff[1], 2), \", \", round(ic_diff[2], 2),\n  \"], t(\", round(t_welch$parameter, 2), \") = \", round(t_welch$statistic, 2),\n  \", p = \", signif(t_welch$p.value, 3),\n  \", d = \", round(cohens_d, 2), \".\\n\",\n  sep = \"\"\n)\n#> Il gruppo sottoposto all'intervento ha riportato un punteggio medio di 31.2 (DS = 2.83), mentre il gruppo controllo ha riportato un punteggio medio di 26.2 (DS = 2.18). La differenza media è pari a 5 punti, IC 95% [2.85, 7.15], t(20.6) = 4.85, p = 0.0000901, d = 1.98.\n```\n:::\n\n\nIn un testo scientifico, il risultato potrebbe essere riportato così:\n\n> Il gruppo sottoposto all'intervento ha riportato un punteggio medio più alto ($M$ = 31.25, $DS$ = 2.83) rispetto al gruppo di controllo ($M$ = 26.25, $DS$ = 2.18). La differenza media è pari a 5.00 punti, $IC$ 95% [2.85, 7.15], $t$(20.64) = 4.85, $p < .001$, $d$ = 1.98.\n\nI valori numerici dipendono dai dati utilizzati nell'esempio. Il punto didattico è la struttura del resoconto: stima, incertezza, test e dimensione dell'effetto.\n\n## Cosa il test non dice\n\nIl test *t* per campioni indipendenti è utile, ma risponde a una domanda circoscritta. In particolare, il test non risponde alla domanda:\n\n- qual è la probabilità che $H_0$ sia vera;\n- qual è la probabilità che $H_1$ sia vera;\n- qual è la probabilità che la differenza vera sia positiva;\n- quanto sia probabile che l'effetto superi una soglia di rilevanza clinica;\n- se il disegno dello studio sia valido;\n- se la differenza osservata sia priva di bias sistematici.\n\nQuesti limiti non rendono il test inutile. Tuttavia, indicano che il valore-*p* deve essere interpretato insieme al disegno dello studio, alle stime, agli intervalli di confidenza, alla potenza e alla plausibilità teorica dell'effetto.\n\n## Collegamento con la prospettiva bayesiana\n\nIn una prospettiva bayesiana, il confronto tra due gruppi viene formulato in modo diverso. Invece di chiedersi quanto i dati siano sorprendenti sotto $H_0$, si costruisce un modello probabilistico per i dati e si ottiene una distribuzione a posteriori per la differenza tra le medie:\n\n$$\n\\Delta = \\mu_1 - \\mu_2.\n$$\n\nQuesta distribuzione permette di rispondere direttamente a domande come:\n\n- qual è la probabilità che $\\Delta > 0$?\n- qual è un intervallo di credibilità per $\\Delta$?\n- qual è la probabilità che $\\Delta$ superi una soglia clinicamente rilevante?\n- quanto sono sensibili le conclusioni alle assunzioni del modello e alla scelta del prior?\n\nIl test *t* frequentista rimane quindi importante da conoscere perché è molto diffuso nella letteratura psicologica. Tuttavia, nel percorso bayesiano, il test *t* frequentista funziona soprattutto come termine di confronto, mostrando chiaramente la differenza tra una procedura basata sul controllo dell'errore nel lungo periodo e una procedura basata sull'aggiornamento delle credenze sui parametri.\n\n::: callout-tip\n## Lettura complementare\n\nUn confronto esplicito tra il test *t* tradizionale e una formulazione bayesiana del confronto tra due gruppi è discusso da @kruschke2013bayesian.\n:::\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIl test *t* per campioni indipendenti è uno strumento fondamentale dell'inferenza frequentista. Consente di confrontare due gruppi quando l'esito è di tipo quantitativo e quando il disegno dello studio rende plausibile l'indipendenza delle osservazioni.\n\nIn questo capitolo lo abbiamo interpretato come applicazione finale della logica introdotta nei capitoli precedenti: a una stima puntuale sono associati un intervallo di confidenza, una statistica di test, un valore p e una dimensione dell'effetto. Nessuno di questi elementi, preso singolarmente, esaurisce il significato del risultato.\n\nIl messaggio principale è che un buon resoconto non dovrebbe limitarsi a dichiarare se un risultato è significativo. Dovrebbe invece comunicare **quanto** differiscono i gruppi, **con quale incertezza**, **rispetto a quale procedura di test** e **con quale rilevanza sostantiva**.\n\nDa qui, il passaggio alla prospettiva bayesiana è naturale: anziché domandarsi se una differenza sia abbastanza sorprendente sotto un'ipotesi nulla, è possibile modellare direttamente l'incertezza sulla differenza tra i gruppi e aggiornare le proprie credenze alla luce dei dati osservati.\n\n## Punti chiave da ricordare {.unnumbered}\n\n::: callout-important\n\n- Il test *t* per campioni indipendenti confronta le medie di due gruppi distinti.\n- La domanda frequentista è condizionale a $H_0$: quanto sarebbero sorprendenti dati come quelli osservati se le due medie fossero uguali?\n- Il test di Welch è spesso preferibile perché non richiede l'assunzione di varianze uguali.\n- Il valore-*p* non è la probabilità che l'ipotesi nulla sia vera.\n- L'intervallo di confidenza descrive la precisione della stima secondo una procedura con copertura nel lungo periodo.\n- La dimensione dell'effetto aiuta a valutare la rilevanza sostantiva della differenza.\n- Un risultato completo integra stima, incertezza, test, valore-*p* e dimensione dell'effetto.\n- La prospettiva bayesiana permette di formulare direttamente domande sulla differenza tra le medie e sulla probabilità di effetti rilevanti.\n\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.5.2\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.0            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.0           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.2              fastmap_1.2.0         tensorA_0.36.2.1     \n#>  [7] digest_0.6.39         timechange_0.4.0      estimability_2.0.0   \n#> [10] lifecycle_1.0.5       magrittr_2.0.5        compiler_4.6.1       \n#> [13] rlang_1.3.0           tools_4.6.1           yaml_2.3.12          \n#> [16] knitr_1.51            labeling_0.4.3        bridgesampling_1.2-1 \n#> [19] pkgbuild_1.4.8        curl_7.1.0            RColorBrewer_1.1-3   \n#> [22] abind_1.4-8           purrr_1.2.2           grid_4.6.1           \n#> [25] stats4_4.6.1          xtable_1.8-8          inline_0.3.21        \n#> [28] emmeans_2.0.3         scales_1.4.0          cli_3.6.6            \n#> [31] mvtnorm_1.4-1         rmarkdown_2.31        generics_0.1.4       \n#> [34] otel_0.2.0            RcppParallel_5.1.11-2 cachem_1.1.0         \n#> [37] stringr_1.6.0         parallel_4.6.1        vctrs_0.7.3          \n#> [40] V8_8.2.0              Matrix_1.7-5          jsonlite_2.0.0       \n#> [43] arrayhelpers_1.1-1    glue_1.8.1            codetools_0.2-20     \n#> [46] distributional_0.8.1  lubridate_1.9.5       stringi_1.8.7        \n#> [49] gtable_0.3.6          QuickJSR_1.10.0       pillar_1.11.1        \n#> [52] htmltools_0.5.9       Brobdingnag_1.2-9     R6_2.6.1             \n#> [55] textshaping_1.0.5     rprojroot_2.1.1       evaluate_1.0.5       \n#> [58] lattice_0.22-9        backports_1.5.1       memoise_2.0.1        \n#> [61] broom_1.0.13          snakecase_0.11.1      rstantools_2.6.0     \n#> [64] coda_0.19-4.1         gridExtra_2.3.1       nlme_3.1-169         \n#> [67] checkmate_2.3.4       xfun_0.60             pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "06_two_ind_samples_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}